### PR TITLE
fix undefined local variable or method `variants'

### PR DESCRIPTION
**Pull request by wuboy0307**
undefined local variable or method `variants' for #<AddDiscontinuedToProductsAndVariants:0x007fa2fa434ff0>/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:661:in`block in method_missing'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in `block in say_with_time'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in`say_with_time'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:652:in `method_missing'
/Users/wuboy/workspace/hiway_backend/db/migrate/20151201195635_add_discontinued_to_products_and_variants.spree.rb:34:in`block in up'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/relation/delegation.rb:46:in `each'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/relation/delegation.rb:46:in`each'
/Users/wuboy/workspace/hiway_backend/db/migrate/20151201195635_add_discontinued_to_products_and_variants.spree.rb:18:in `up'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:609:in`exec_migration'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:589:in`block in migrate'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:588:in`migrate'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:765:in `migrate'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:995:in`block in execute_migration_in_transaction'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:1043:in `ddl_transaction'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:994:in`execute_migration_in_transaction'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:956:in `block in migrate'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:952:in`each'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:952:in `migrate'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:820:in`up'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:798:in `migrate'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:137:in`migrate'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
NameError: undefined local variable or method`variants' for #AddDiscontinuedToProductsAndVariants:0x007fa2fa434ff0
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:661:in `block in method_missing'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in`block in say_with_time'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in `say_with_time'
/Users/wuboy/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:652:in`method_missing'
/Users/wuboy/workspace/hiway_backend/db/migrate/20151201195635_add_discontinued_to_products_and_variants.spree.rb:34:in `block in up'

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://wuboy0307-patch-27.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://wuboy0307-patch-27.spree-spree-9ed724b77adec04c49c2.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by priyank-gupta** [comment]
@wuboy0307 The error seems to be generated from `20151201195635_add_discontinued_to_products_and_variants.spree.rb:34` while you have provided a fix at line number 54. You shall revisit this.

**Comment by wuboy0307** [comment]
Sorry, I only test my own migration script. 
I already revised it, thanks!

**Comment by Mafi88** [comment]
It seem to be fixed now.

What do you think @damianlegawiec, @priyank-gupta?

**Comment by priyank-gupta** [comment]
:+1: 
Seems fine. Failing specs found, rebuild checks.

**Comment by mbj** [comment]
Another PR merged on red CI? What is the policy on CI usage?

**Comment by priyank-gupta** [comment]
@mbj As the failure specs are two feature specs which fail intermittently and we are working to fix that separately. Rebuilding check should fix this.

Rebuilding now.

**Pull request merged**
