### PR TITLE
Need to permit an array for option_value_ids

### PR DESCRIPTION
**Pull request by huoxito**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://huoxito-permit-array-for-option-value-ids.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://huoxito-permit-array-for-option-value-ids.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by huoxito** [comment]
and I was about to comment _zomg houndci is quiet_

**Comment by JDutil** [comment]
Thanks @huoxito knew a second set of eyes was going to spot something simple I missed

**Comment by vmatekole** [comment]
@huoxito this seemingly does not work for multiple option_value_ids. This is a big issue for us as we have unnecessary round trips for each option_value for a given variant - please refer #6331

**Comment by huoxito** [comment]
@vmatekole I'm not sure I understand what you mean I thought this would work for multiple ids too, thanks for letting us know though, will try a closer look at some point today

**Comment by vmatekole** [comment]
@huoxito Here is a script to test against my use case 
https://github.com/GROK7/spree-vend/blob/20ddc3627f11954627f81e8eadb073fb1b2186ff/scripts/create_spree_variant.sh

https://github.com/GROK7/spree-vend/blob/20ddc3627f11954627f81e8eadb073fb1b2186ff/scripts/example-variants.json

**Pull request closed without merging**
