### PR TITLE
Deprecate Spree::Tracker and move it to a preference in Spree::Store

### PR DESCRIPTION
**Pull request by BenMorganIO**
- [x] Add preferences column to `Spree::Store`
- [x] Add tracker preference
- [x] Port the data from `Spree::Tracker` to `Spree::Store` preferences
- [x] Add warning about the removal of the `Spree::Tracker` model and table
- [x] Update the GA partial and respective views.

### CODE REVIEW

**Comment by JDutil** [comment]
@BenMorganIO I think we should just drop the env like with payment methods.

**Comment by BenMorganIO** [comment]
I think that's all. I think we can remove the `Spree::Tracker` model entirely in Spree 3.1. This should give people on custom storefronts with a modified `spree_trackers` table time to think about how they're going to deal with this.

**Comment by JDutil** [comment]
I think we should name the preference something like google_analtyics_id or something more descriptive.

**Comment by BenMorganIO** [comment]
I think `analytics_id` would be better. Its inferred that its GA...

**Comment by JDutil** [comment]
I think we may want to just use ActiveRecord::Store here.  Not sure we want to go through the preference code to lookup a value when we should have it loaded already on the store instance.

**Comment by BenMorganIO** [comment]
@JDutil 4dcbad0 might cause some problems in the future. Do you know a cleanway to silence AR Deprecations?

**Comment by BenMorganIO** [comment]
Did we want it to be a `preferences` column with `{ "analytics_id": "UA-123456" }` or a `tracker` column with:

```json
{
  "analytics_id": "UA-123456",
  "active": true
}
```

**Comment by BenMorganIO** [comment]
When migrating to AR Store, I'll add an if statement for PG users so they get their hstore awesomeness.

**Comment by JDutil** [comment]
I think we want a preferences column so it can be used for other things as well.

**Pull request closed without merging**
