### PR TITLE
Update friendly_id to v5.2.0

### PR DESCRIPTION
**Pull request by ezekg**
This is in response to #7756. Prior to v5.2, friendly_id did not have full Rails 5 support. As it stands, there are still a few broken tests due to other changes within v5.2 (unfortunately).

We need to wait until https://github.com/norman/friendly_id/pull/779 is merged before our tests will pass. I've confirmed that the following monkey patch works when applied to `core/config/initializers/friendly_id.rb` (which is the fix the above PR contains):

```ruby
# Monkey patch: https://github.com/norman/friendly_id/pull/779
module FriendlyId
  module Slugged
    def unset_slug_if_invalid
      if errors.present? && attribute_changed?(friendly_id_config.query_field)
        diff = changes[friendly_id_config.query_field]
        send "#{friendly_id_config.slug_column}=", diff.first
      end
    end
    private :unset_slug_if_invalid
  end
end
```

I doubt we'd want to implement the monkey patch, especially considering v5.2 was only released 2 weeks ago, so it's probably better to just wait on that PR. 👍

### CODE REVIEW

**Comment by damianlegawiec** [comment]
@ezekg thanks for the full explanation, will wait for the `5.2.1` and include this PR for Spree `3.3.0`

**Comment by ezekg** [comment]
Sounds good. I'll keep an eye on that PR and make sure nothing else crops up when the time comes.

**Comment by ezekg** [comment]
Just an update: the PR we need has been merged, but we're waiting on a patch release now.

**Comment by vfonic** [comment]
@ezekg  @damianlegawiec The new version of friendly_id has just been released. It includes mentioned fix.
https://github.com/norman/friendly_id/pull/779#issuecomment-292774628

**Comment by krzysiek1507** [comment]
@ezekg if you don't have time, please ping me and I do it! Thanks!

**Comment by ezekg** [comment]
Not sure what the deal is here with the failing CI tests. All green locally.

Any idea on how to fix?

**Comment by vfonic** [comment]
@ezekg `rspec spec/controllers/spree/api/v1/product_properties_controller_spec.rb` is passing for me locally as well. I'm running on ruby 2.4.0. Maybe it's something specifict to ruby 2.3.0? I tried both pg 0.20.0 and pg 0.19.0.

Did you try re-running the failing build(s)?

**Comment by ezekg** [comment]
From what I could see, I don't have permission to re-run the build.

**Comment by krzysiek1507** [comment]
@ezekg there is also changed migration in >= 5.2.0 https://github.com/norman/friendly_id/pull/694

**Comment by krzysiek1507** [comment]
@ezekg they've added order [here](https://github.com/norman/friendly_id/blob/718b1bcad8e47ccde8a4b559b734505a49d313a7/lib/friendly_id/history.rb#L100) and it could conflict with distinct

**Comment by ezekg** [comment]
I've duplicated the CI environment locally and am still unable to reproduce the failures.

Will continue to dig in more soon. Feel free to chip in if you know how to resolve.

**Comment by ezekg** [comment]
I added the index changes from friendly id in a migration. Is that correct? I'm not sure how you guys normally pull in upstream migration changes. Let me know if that's incorrect. 👍

**Comment by ezekg** [comment]
Okay, so I got API spec passing (frontend is still failing) but [the solution is rather hacky](https://github.com/spree/spree/pull/7758/commits/31a7c4ec0ea6282b5050b60ab2ab9ee991a8ba01)… I removed the distinct call, since we're looking up a single model anyways. The workaround is similar to a workaround implemented in [`core/app/models/spree/product/scopes.rb`](https://github.com/spree/spree/blob/94e9e42526724eeedb8bdbf4216efb0a9ffb193f/core/app/models/spree/product/scopes.rb?ts=2#L216-L236). I can go through and implement the same for the other failing specs, but not sure if it's the right direction to take.

Honestly, I'm not super familiar with Spree's codebase so could use a hand!

**Comment by ezekg** [comment]
@krzysiek1507 do you have any input here? I don't think the failing specs are related to my PR, seeing as most of the other PRs have the same failure.

**Comment by damianlegawiec** [comment]
Closd in favour of https://github.com/spree/spree/pull/8005

**Pull request closed without merging**
