### PR TITLE
ADMIN: Bounce-in / fade-out alerts.

### PR DESCRIPTION
**Pull request by MatthewKennedy**
Bounce-in / fade-out alerts.

### CODE REVIEW

**Review by damianlegawiec — APPROVED** [review]
There are some places still where the old alerts are used / rendered eg. after executing an ajax action 
Screenshot 2020-07-12 at 1 06 40 PM

**Comment by MatthewKennedy** [comment]
> There are some places still where the old alerts are used / rendered eg. after executing an ajax action
> Screenshot 2020-07-12 at 1 06 40 PM

I'll look at that now.

**Comment by MatthewKennedy** [comment]
@damianlegawiec the tests fail in this PR because they are looking for the text in the pop up notifications, but the notification is removed from the DOM once it has faded from view.

This is intentional so that when dealing with multiple alerts such as deleting one property, and then another, the cycle is repeatable with a fresh instance each time, rather than adding animations to elements with the same class lingering in the DOM from previous use.

Any suggestions on how to deal with the two failures?

**Comment by MatthewKennedy** [comment]
Could leave them in the DOM and if another alert is fired then check for existing and remove before creating the new alert.

**Review by kaliszKrzysztof — APPROVED** [review]

**Comment by damianlegawiec** [comment]
@MatthewKennedy could you rebase this PR with main branch? Thank you!

**Comment by MatthewKennedy** [comment]
Sure no problem

**Pull request merged**
