### PR TITLE
move stock items creation to a job

### PR DESCRIPTION
**Pull request by BenMorganIO**
- [x] Job for Stock Location
- [ ] Spec for Job
- [ ] Updated specs for stock location

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://benmorganio-stock-items-job.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by JDutil** [comment]
The job should have an associated spec, and the stock location spec should now ensure the job is called.

**Comment by BenMorganIO** [comment]
Will do.

**Comment by BenMorganIO** [comment]
Accidentally merged master, did a hard reset, Github then did an automatic close, cherry picked the commit which worked, but not showing in this PR since its closed now. This was my fault.

**Pull request closed without merging**
