### PR TITLE
Squash setup

### PR DESCRIPTION
**Pull request by emiquelito**
This is a patch to integrate Spree with Squash.io I believe this is going to be handy to the project so any project maintainers and developers can quickly check the branch changes on its own VM.

Example of Spree working with Squash: https://squash-setup-xkr8a.squash.io/

Squash is free for Open Source, maintainers just need to signup and reach out to the support through the chat window and we will enable a forever free Open Source account. Once this is done, Squash will post a comment on each Pull Request like this:

squash-pr-comment

When you click on the Squash link in a new PR it will deploy the branch of code into a brand new VM, **this process takes about 2 minutes**.  

@damianlegawiec let me know what you think please. Thanks.

### CODE REVIEW

**Comment by emiquelito** [comment]
Hey @damianlegawiec any thoughts on this PR?

**Review by damianlegawiec — APPROVED** [review]

**Comment by emiquelito** [comment]
Hi @damianlegawiec sounds great, thanks for this.

Just a friendly reminder to sign up on https://squash.io/signup/ so you can start getting the automatic Squash comments on each PR. I will keep an eye when you signup and make sure to enable our "forever free" open source plan for your repo.

**Comment by damianlegawiec** [comment]
Thanks @emiquelito - I've authorized Squash app to the Spree repo - it should be all setup :)

**Comment by emiquelito** [comment]
@damianlegawiec sounds great! I just enabled the Open Source account type for you. Please do let me know if you need any assistance moving forward. You can use the chat window within the Squash or feel free to shoot me an email at emiquelito@squash.io

Have a great rest of the weekend.

**Pull request merged**
