### PR TITLE
Add destroy functionality to refund_reason and return_authorization_r…

### PR DESCRIPTION
**Pull request by tanmay3011**
…eason #6878

### CODE REVIEW

**Comment by priyank-gupta** [comment]
@tanmay3011 Rebase with latest master.

**Comment by tanmay3011** [comment]
@Mafi88 Specs Added

**Comment by Mafi88** [comment]
@tanmay3011 It would be great if you could also add feature specs to test process of successful and failed deletion.

**Comment by tanmay3011** [comment]
@Mafi88 Feature specs added.

**Comment by Mafi88** [comment]
@tanmay3011 I know it's basicaly the same functionality but I think there should be also similar feature specs for return_authorization_reasons

**Comment by tanmay3011** [comment]
@Mafi88 Done! Added.

**Comment by Mafi88** [comment]
:+1: 
@priyank-gupta ?

**Comment by priyank-gupta** [comment]
:+1:

**Pull request merged**
