### PR TITLE
Modify rspec-activemodel-mocks-patch.rb to also allow upper versions of …

### PR DESCRIPTION
**Pull request by nishant-cyro**
…1.0.1

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://nishant-cyro-modify-rspec-activemodel-mocks-patch.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://nishant-cyro-modify-rspec-activemodel-mocks-patch.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
If they've released a fixed version please remove this file altogether and update the gemspec to require the fixed version instead.

**Comment by nishant-cyro** [comment]
@JDutil - Done. The issue has been fixed in the new version. Refer this pull request - https://github.com/rspec/rspec-activemodel-mocks/pull/19.

**Comment by JDutil** [comment]
Thanks

**Pull request merged**
