### PR TITLE
Allow admin to edit product's SKU even if variants are present

### PR DESCRIPTION
**Pull request by nishant-cyro**
Fixes https://github.com/spree/spree/issues/7229

### CODE REVIEW

**Comment by priyank-gupta** [comment]
@nishant-cyro Not sure why we need SKU of product if we have variants for that product.
I am inclined to either nullify or hide the product SKU if it has variants.
SKU represents a physical entity which represents product (master variant) when no variant and represents variants otherwise.

@damianlegawiec @Mafi88 Thoughts ?

**Comment by damianlegawiec** [comment]
@priyank-gupta you're right. I think maybe once I stumbled upon a setup where there was a need for such a feature. But let's others share their thoughts.

**Comment by Mafi88** [comment]
@nishant-cyro @damianlegawiec @priyank-gupta I agree that there is no need to change SKU for such products. And it's already hidden :)

However I responded in issue in question, maybe we should wait for creator's answer?

**Comment by nishant-cyro** [comment]
Closing this one. I will create a new PR as per the discussion in #7229.

**Pull request closed without merging**
