### PR TITLE
Add pagination for resource controller

### PR DESCRIPTION
**Pull request by dilpreet92**

### CODE REVIEW

**Comment by Mafi88** [comment]
@dilpreet92 Could you please describe shortly why this change is needed?

**Comment by dilpreetwal** [comment]
@Mafi88 Currently when a resource is made in the admin end inheriting from the resource controller , it does not supports pagination, this change will provide support for pagination.

**Comment by dilpreet92** [comment]
@Mafi88 Currently when a resource is made in the admin end inheriting from the resource controller , it does not supports pagination, this change will provide support for pagination

**Comment by Mafi88** [comment]
@dilpreet92 yes, but each controller (currently added) has pagination added at some point of query building. So now ```page``` method is doubled? Am I getting it wrong?

@damianlegawiec @priyank-gupta @nishant-cyro and what do you think?

**Comment by dilpreet92** [comment]
@Mafi88 - This only sets the limit to the query as per the params[:page] and because it returns the ActiveRecord::Relation object, there would be no need for using it again in the query building for the admin resources.

**Comment by Mafi88** [comment]
@damianlegawiec @priyank-gupta Any thoughts?

**Comment by priyank-gupta** [comment]
Seems fine to me.
@damianlegawiec ?

**Comment by nishant-cyro** [comment]
@dilpreet92 @priyank-gupta @Mafi88 @damianlegawiec - I guess we shouldn't add pagination in ResourceController because there are controllers like ContriesController and PaymentMethodsController which inherits from ResourceController but doesn't have pagination.

**Comment by damianlegawiec** [comment]
@nishant-cyro you're right

**Pull request closed without merging**
