### PR TITLE
use aws-sdk-v1 gem so version 2 of aws-sdk can be used

### PR DESCRIPTION
**Pull request by thogg4**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://thogg4-2-3-stable.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://thogg4-2-3-stable.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
Why can't you use aws-sdk it has v2:
https://github.com/aws/aws-sdk-ruby

I think you just need to bump the version not change the library.

**Comment by thogg4** [comment]
@JDutil sorry, i should have explained better:
Using the aws-sdk-v1 gem enables you to use both gems at the same time. This is required because they changed the gem namespace from AWS to Aws.

http://ruby.awsblog.com/post/TxFKSK2QJE6RPZ/Upcoming-Stable-Release-of-AWS-SDK-for-Ruby-Version-2

**Comment by JDutil** [comment]
Merged adfc0d3aa3acc38efae9c11a50d67d4361338997

**Pull request closed without merging**
