### PR TITLE
Improve Flash Alerts

### PR DESCRIPTION
**Pull request by MatthewKennedy**
- Add the ability to hover over notification to keep on screen longer
- Add notification close button to get rid of notification.
- Last notification messages get stored in DOM for testing.

```html
<!-- useful for capybara tests -->
<div id="FlashAlertsContainer" class="d-none">
  <span class="d-none expired-flash-alert" data-alert-type="success">Cache was flushed.</span>
</div>
```

If someone is fast on the messages, messages stack.

alerts

### CODE REVIEW

**Review by damianlegawiec — APPROVED** [review]
Look great 👏

**Comment by MatthewKennedy** [comment]
@damianlegawiec Thanks, just thinking about that jQuery that was looking for the flash alert class in the DOM before deleting the table row.

Maybe I should write the JavaScript to leave only the last triggered alert in the holder at the bottom of the body for reference, rather than a history of alerts, then it has a use of truly showing the last event success or fail.

I think that would be more useful.

**Comment by MatthewKennedy** [comment]
A  little bit more work on this yet..

**Comment by MatthewKennedy** [comment]
This should be good now.

**Comment by damianlegawiec** [comment]
@MatthewKennedy it seems noty is longer maintained - https://github.com/needim/noty/

**Comment by MatthewKennedy** [comment]
@damianlegawiec Yeah I saw that but figured I wasn't going to top five years of dedicated JS pop-up alert work in a weekend.

I don't know why he stopped minting it, as it seems to be one of the best vanilla JS pop up alert options around, I think the maintainer is extremely busy with his full time job and just sacked it off rather than looking for a new maintainer.

Let me know if you want me to swap Noty for something else but it seems pretty robust.

**Comment by MatthewKennedy** [comment]
Putting this into draft to test another lib.

**Pull request closed without merging**
