### PR TITLE
refs#7399

### PR DESCRIPTION
**Pull request by odk211**

### CODE REVIEW

**Comment by priyank-gupta** [comment]
@odk211 CircleCI build fails from this change. Have look please.

**Comment by odk211** [comment]
@priyank-gupta It seems some performance tuning is there, so we can not use `touch: true` option, I think.
 https://github.com/spree/spree/blob/dcc0396e2f77ec013f832f29f8ab2a9e7c2cf8d2/core/app/models/spree/stock_item.rb#L81

I changed this PR to use `after_destroy`.

**Comment by damianlegawiec** [comment]
Thanks @odk211 👍

**Comment by odk211** [comment]
@priyank-gupta @damianlegawiec :)
PR against `3-1-stable` is created https://github.com/spree/spree/pull/7404

**Pull request merged**
