### PR TITLE
codebeat badge

### PR DESCRIPTION
**Pull request by korzonek**
Is it fine to add codebeat badge to README? 

codebeat is automated code review tool for Swift,Ruby,Go & Python that helps get instant feedback on code quality. 

"Quick wins" suggested by codebeat could be a nice candidate for a pull request and help other developers become contributors.

FYI. To be fully open and honest. I'm co-founder of codebeat.

### CODE REVIEW

**Comment by damianlegawiec** [comment]
:+1: 

@korzonek can you move it after codeclimate one? It would look nicer :)

**Comment by korzonek** [comment]
@damianlegawiec done :)

**Comment by damianlegawiec** [comment]
@korzonek can you also rebase/squash into single commit? Thanks :)

**Comment by korzonek** [comment]
@damianlegawiec done :)

**Comment by Mafi88** [comment]
:+1:

**Pull request merged**
