### PR TITLE
remove pagination for zero records found and save a count query

### PR DESCRIPTION
**Pull request by vinay-mittal**

### CODE REVIEW

**Comment by priyank-gupta** [comment]
:+1: 
@damianlegawiec @Mafi88 ?

**Comment by nishant-cyro** [comment]
:+1:

**Comment by damianlegawiec** [comment]
I think we should leave as it is. The same behaviour is on any other admin panel's lists, so changing just one and leaving the rest is a no-no. This also prevents situations when user paginates resources and at the same time other admin deletes/changes them and the first one ends up on a page without records.This way he can easily paginate back.

**Comment by Mafi88** [comment]
I agree, we shouldn't change this

**Pull request closed without merging**
