### PR TITLE
Rubocop refactor and Hash syntax change

### PR DESCRIPTION
**Pull request by priyank-gupta**
- Refactor -> `rubocop -a`.
- Hashrockets -> new syntax upgrade.

### CODE REVIEW

**Comment by krzysiek1507** [comment]
@priyank-gupta `render(something) and return` != `render(something) && return`

**Comment by vishalzambre** [comment]
@priyank-gupta Why we'r not following Rubocop all practices for single quotes/Double quotes, long line
If you want I can contribute to beautify code :)

**Comment by damianlegawiec** [comment]
I think this one should be closed in favor of a several smaller PRs focused on particular spree part. Like @krzysiek1507 noted not everything can be done automatically.

**Comment by priyank-gupta** [comment]
@damianlegawiec Or, lets only focus on Hash syntax change in this PR and move out other changes to separate PR's.

**Comment by damianlegawiec** [comment]
@priyank-gupta sure, let's do it 👍

**Comment by vishalzambre** [comment]
@priyank-gupta  @damianlegawiec Can you please update rubocop.yml with requried options, then we can consider only auto correction from rubocop as well

**Pull request closed without merging**
