### PR TITLE
Allow feedback from customer details update.

### PR DESCRIPTION
**Pull request by somecodemonkey**
Currently there is no/false feedback when updating customer details. The
success flash message would appear whether or not the next/update was successful.
This allows next/update to happen while allowing appropriate feedback.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://pervino-customer-update-fix.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://pervino-customer-update-fix.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by BenMorganIO** [comment]
Can you fix the specs, add some specs for your changes, update the changelog, and update the documentation (if needed) for this? I'm having trouble trying to figure out what this PR fixes via the code.

**Comment by darbs** [comment]
These changes have nothing to do with any taxon views which is what the single failed spec is, no idea why thats failing and i cannot replicate it locally.

Currently if you update the customer details page in the backend the only feedback is success regardless if it was actually successful or not. So for example if you updated a the address with invalid information it would still prompt a success even though the state may have not transitioned at all or the address was invalid. I will update the changelog appropriately.

**Comment by BenMorganIO** [comment]
Apologies, but we might actually be removing the changelog instead in favour of the Release Notes. Can you add it there with a bit more description? An example "changleog" for release notes can be found here: https://github.com/rails/rails/blob/master/activerecord/CHANGELOG.md. The release notes can be found here: https://github.com/spree/spree/blob/master/guides/content/release_notes/3_1_0.md

**Pull request closed without merging**
