### PR TITLE
Fix intermittent failure specs

### PR DESCRIPTION
**Pull request by priyank-gupta**
- This fixes all intermittent failing specs.
- Speeds up test suite a bit by using js: true/false where required.
- Some refactoring of specs.
- Decreased `Capybara.default_max_wait_time` to 10.
- Fix return authorization reasons and refund reasons feature specs.

### CODE REVIEW

**Comment by priyank-gupta** [comment]
@damianlegawiec @Mafi88 This needs urgent attention as master's build is failing.

**Comment by Mafi88** [comment]
Those spec are testing non-javascript code anyway, but I'm not sure if removing javascript from them won't possibly result with specs not catching some js problems (for example if js removes too many rows, or something like this).

@damianlegawiec what do you think?

**Comment by priyank-gupta** [comment]
@Mafi88 I have used `js: false` in places where page load or record/row existence is in question (non-javascript). Cases where ajax request, icon (delete/edit) check, select2 check and others which are dependent on javascript still use `js: true`.

**Comment by Mafi88** [comment]
@priyank-gupta yes, I know, I only meant that with ```js: false``` specs won't detect if row is removed by js by accident. But on the other hand it's not their purpose.

**Pull request merged**
