### PR TITLE
Add presence and uniqueness validation with multiple belongs_to assoc…

### PR DESCRIPTION
**Pull request by tanmay3011**
…iation

### CODE REVIEW

**Comment by priyank-gupta** [comment]
:+1:

**Comment by nishant-cyro** [comment]
:+1:

**Comment by Mafi88** [comment]
@tanmay3011 Could you please remove blank line houndci is complaining at?

**Comment by tanmay3011** [comment]
@Mafi88  okay!

**Comment by tanmay3011** [comment]
@Mafi88 Done!

**Pull request merged**
