### PR TITLE
Use scope to select payment states

### PR DESCRIPTION
**Pull request by lifelofranco**
The current behaviour loops over the payments object and calls checkout scope method or the pending scope method multiple times. This commit removes the loop and uses the scope directly, optimizing the current behaviour.

### CODE REVIEW

**Review by damianlegawiec — APPROVED** [review]
Thanks @lifelofranco - there is one failing test - could you fix it?

**Comment by lifelofranco** [comment]
Hey @damianlegawiec, can I ask if you know the purpose of this specific test case? It says "For the reason of this test, please see spree/spree_gateway#132" but I can't seem to find it.

Checked and in both scenarios, it returns the same `Spree::CreditCard` object. I am a bit stumped why the current behaviour returns the `number`. However, issuing a separate query `Spree::CreditCard.first.number` indeed returns `nil`, same as the proposed change

**Comment by lifelofranco** [comment]
It seems like the code for `unprocessed_payments` was intentional. See [here](unprocessed_payments). In any case, the change just adds an improvement on the `pending_payments` method call.

**Comment by damianlegawiec** [comment]
Thanks @lifelofranco 👍

**Pull request merged**
