### PR TITLE
Only support array of line items in order importer

### PR DESCRIPTION
**Pull request by smartacus**
This can be removed since the master branch is Spree 3.1. Right?

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://trialguides-order-importer-deprecation-removal.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://trialguides-order-importer-deprecation-removal.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
Yea although I'm wondering if we should wait until Spree 4 to remove this instead.

**Comment by smartacus** [comment]
Fair enough. I just pushed a commit with an updated deprecation message. I also flattened the Hash and Array line item iterators into one.

**Comment by JDutil** [comment]
Thanks

**Pull request closed without merging**
