### PR TITLE
Allow non credit card payment sources

### PR DESCRIPTION
**Pull request by mamhoff**
We have a number of reusable payment sources that are not credit cards. However, the `payment_sources` method on the `Spree.user_class` model is a simple `has_many` that can only get Credit cards.

This PR adds a join table between the user and the different payment source models to accomodate for the ensuing Polymorphism. Common code for all payment sources is abstracted into a `Spree::PaymentSource` base class, and the common tests are extracted into `shared_examples` for all Payment sources.

Consequently, also the code for re-using existing payment sources in  `order/checkout.rb` had to be adapted.

This is a rather large PR. Please have a careful look at it; I'm happy to integrate comments and criticism.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://magiclabs-allow-non-credit-card-payment-sources.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://magiclabs-allow-non-credit-card-payment-sources.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
I like the concept of the change, but need some time to review it.  First impression though is that it should be added to the release notes.

**Comment by mamhoff** [comment]
Hound would like me to not define methods inside a method, but `order/checkout.rb` has lots of them. There's probably an issue here, but not one I'd like to confront right now :) - Otherwise I think this is done and ready for review. @JDutil If you'd be so nice?

**Comment by mamhoff** [comment]
@JDutil Added a data migration so existing shops don't lose their CC-User associations.

**Comment by Mafi88** [comment]
@mamhoff Could you please rebase this PR with latest master? Thanks!

**Comment by mamhoff** [comment]
@Mafi88 rebased!

**Comment by mamhoff** [comment]
It's unlikely I'll have time to work on this; closing. If anyone wants to pick up the work, feel free to do so.

**Pull request closed without merging**
