### PR TITLE
Add failure error message on product destroy and update controller sp…

### PR DESCRIPTION
**Pull request by tanmay3011**
…ecs avoid using real data

### CODE REVIEW

**Comment by Mafi88** [comment]
@tanmay3011 Why are you stubbing data instead of using factories?

**Comment by tanmay3011** [comment]
@Mafi88 In case of controller specs we just need to check request and response for that specific action. For which we only need stubbed data. We can use factories but they will be slower and data doesn't need to be tested in controller specs. So I prefer stubbing data for controller specs.

**Comment by nishant-cyro** [comment]
@Mafi88 @tanmay3011 - I guess the specs are fine, we should use mocked data for controllers instead of real ones. Please refer - https://github.com/reachlocal/rspec-style-guide#controllers.

**Comment by priyank-gupta** [comment]
:+1: 
@Mafi88 ?

**Pull request merged**
