### PR TITLE
fix product available on spec wrong comparison

### PR DESCRIPTION
**Pull request by arthurtalkgoal**
The original date comparison is incorrect

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://arthurtalkgoal-3-0-stable-product-spec.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://arthurtalkgoal-3-0-stable-product-spec.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
This is a duplicate #6070

**Comment by arthurtalkgoal** [comment]
again, it's not, I have to split the merge into three commits, please see the last few comments in:

https://github.com/spree/spree/pull/6078#issuecomment-75772080

The original PR however is closed.

**Comment by JDutil** [comment]
It is a duplicate of https://github.com/spree/spree/commit/c22caf798c431f93e5406a078f016a0a403eb95b

**Pull request closed without merging**
