### PR TITLE
Fix Spree Issue#6035

### PR DESCRIPTION
**Pull request by edmondchui**
https://github.com/spree/spree/issues/6035

Call `product.touch` at the end of `Spree::Core::Importer::Product#update` to
1. Modify the `updated_at` field of the product so that key-based caching can pick up new changes.
2. Invoke the `after_touch` callback in `Spree::Product` to touch the taxons of the product.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://edmondchui-master.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://edmondchui-master.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by gmacdougall** [comment]
:-1: I don't think this is the correct solution to the problem that you're experiencing.

`update_attributes` will update the time in the updated_at field. If the correct callbacks aren't being thrown then, we should tackle this in a manner which will fix its usage throughout Spree, and not just in this one place.

**Comment by edmondchui** [comment]
@gmacdougall, ```update_attributes``` produces directly SQL and doesn't updated the ```updated_at``` field. I verified that in debugger.

**Comment by JDutil** [comment]
update_attributes should be updating updated_at it's update_columns that would not.

**Pull request closed without merging**
