### PR TITLE
Update Bootstrap to version 4

### PR DESCRIPTION
**Pull request by kushniryb**
Clean version of #8975 
---
This PR updates Bootstrap framework to the latest version and fixes all UI issues, related to this update.

Bootstrap version: **4.1.3**

### General

- [x] ~~Use official bootstrap gem~~
- [x] ~~Update old bootstrap variables~~
- [x] ~~Use glyphicons from another gem (bootstrap is not shipping with icons any more)~~

### Javascript

- [x] ~~Fix jQuery deprecations~~ (@michalprzybysz)

### Frontend:
- [x] ~~Pagination~~
- [x] ~~Product Cards~~
- [x] ~~Product Page~~
- [x] ~~Breadcrumbs~~
- [x] ~~Sidebar Lists~~
- [x] ~~Search~~
- [x] ~~Navbar~~
- [x] ~~Cart~~
- [x] ~~Checkout~~

### Backend:

**Shared Components:**
- [x] ~~Tables~~ (@kaliszKrzysztof)
- [x] ~~Filters~~ (@kaliszKrzysztof)
- [x] ~~Datepicker~~ (@kaliszKrzysztof)
- [x] ~~Well~~ (@kaliszKrzysztof)
- [x] ~~Tabs~~
- [x] ~~Select2~~
- [x] ~~Sidebar~~
- [x] ~~Header~~

**Pages:**
- [x] ~~Orders~~
- [x] ~~Returns~~
- [x] ~~Products~~
- [x] ~~Reports~~
- [x] ~~Promotions~~
- [x] ~~Users~~
- [x] ~~Configurations~~

### Extensions:
- [x] ~~spree_gateway~~ _(nothing to update)_
- [x] ~~spree_auth_devise~~	(@kaliszKrzysztof)  (**PR:** https://github.com/spree/spree_auth_devise/pull/443)
- [x] ~~spree_i18n~~ (@kaliszKrzysztof) (**PR:** https://github.com/spree-contrib/spree_i18n/pull/782)
- [x] ~~spree_multi_currency~~ (@devilcoders) (**PR:** https://github.com/spree-contrib/spree_multi_currency/pull/81)
- [x] ~~spree_sitemap~~ _(nothing to update)_
- [x] ~~spree_analytics_trackers~~ (@devilcoders) (**PR:** https://github.com/spree-contrib/spree_analytics_trackers/pull/14)
- [x] ~~spree_globalize~~ (@kaliszKrzysztof) [gem outdated]
- [x] ~~spree_digital~~ (@devilcoders) (**PR:** https://github.com/spree-contrib/spree_digital/pull/113)
- [x] ~~spree_email_to_friend~~ (@devilcoders) (**PR:** https://github.com/spree-contrib/spree_email_to_friend/pull/69)
- [x] ~~spree_social~~ (@devilcoders) (**PR:** https://github.com/spree-contrib/spree_social/pull/224)
- [x] ~~spree_editor (@kaliszKrzysztof)~~ (**PR:** https://github.com/spree-contrib/spree_editor/pull/138)
- [x] ~~spree_recently_viewed~~ (@kaliszKrzysztof) (**PR:** https://github.com/spree-contrib/spree_recently_viewed/pull/36)
- [x] ~~spree_related_products~~ (@kaliszKrzysztof) (**PR:** https://github.com/spree-contrib/spree_related_products/pull/160)
- [x] ~~spree_address_book~~ (@kaliszKrzysztof) (**PR:** https://github.com/spree-contrib/spree_address_book/pull/129)
- [x] spree_static_content (@kaliszKrzysztof) (**PR:** https://github.com/spree-contrib/spree_static_content/pull/255) [blocked (depends on `spree_globalize`)]
- [x] ~~spree_volume_pricing~~ (@kaliszKrzysztof) (**PR:** https://github.com/spree-contrib/spree_volume_pricing/pull/110) [review required]
- [x] ~~spree_braintree_vzero~~ (@devilcoders) (**PR:** https://github.com/spree-contrib/spree_braintree_vzero/pull/202)
- [x] ~~spree-product-assembly~~ (@devilcoders) (**PR:** https://github.com/spree-contrib/spree-product-assembly/pull/181)
- [x] ~~better_spree_paypal_express~~ (@devilcoders) (https://github.com/spree-contrib/better_spree_paypal_express/pull/206/files)
- [x] ~~spree_avatax_certified~~ (@devilcoders) (**PR**: https://github.com/spree-contrib/spree_avatax_certified/pull/16)

---

### Can't update at the momement:

- [ ] spree-multi-domain (@devilcoders) [bugs found] [blocked]
- [ ] spree_wishlist (@devilcoders) [bugs found] [blocked]
- [ ] spree_active_shipping (@devilcoders) [outdated]

### CODE REVIEW

**Comment by rendekarf** [comment]
@damianlegawiec any plans for releasing this update soon?

**Comment by damianlegawiec** [comment]
hey @rendekarf we're aiming to merge this PR in the first half of December

**Comment by troias** [comment]
So exicted for this! Counting down the days. So hard for noobs working with bootstrap 3 but looking at bootstrap 4 on their website instructions.

**Comment by krtschmr** [comment]
can this be used now?

**Comment by damianlegawiec** [comment]
@krtschmr we'll be merging this PR next week 🙂

**Comment by krtschmr** [comment]
@damianlegawiec better late then never. 

seems like i can't run bootstrap4 gem with current spree since `@import "bootstrap"` will lead to version3.2 from the spree gem. 

hotfix now is to fork the bootstrapgem and rename everything to ` bootstrap4` so that i can do `@import "bootstrap4" inside the frontend

**Comment by damianlegawiec** [comment]
Merged via https://github.com/spree/spree/pull/9244

**Pull request closed without merging**
