### PR TITLE
Add * to all mandatory fields using base_helper

### PR DESCRIPTION
**Pull request by aishmita-aggarwal**

### CODE REVIEW

**Comment by priyank-gupta** [comment]
@aishmita-aggarwal I think we should also generate label using `required_label_markup` helper. So the code should be like
````
<%= f.required_label_markup(:name, Spree.t(:name)) %>
<%= f.text_field :name, :class => 'form-control' %>
````

**Comment by damianlegawiec** [comment]
```
Unfortunately, any field that uses raw like this will be a potential XSS target.
```

https://www.owasp.org/index.php/Ruby_on_Rails_Cheatsheet ( `Cross-site Scripting (XSS)` section)

We should avoid using raw altogether. This is a huge security risk.

**Comment by aishmita-aggarwal** [comment]
@priyank-gupta @damianlegawiec I agree to both of your suggestions. Will update the PR.

**Comment by damianlegawiec** [comment]
@aishmita-aggarwal I think the best approach would be to just leave `content_tag(:span, " *", :class => "required")` to `required_markup` and leave the rest as it is, it's the more flexible way without any additional magic

**Pull request closed without merging**
