### PR TITLE
Refactor sales_total report, better performance when having many orders

### PR DESCRIPTION
**Pull request by imella**
Currently the sales report performs really slow when having a big number of orders (+1000). Basically because it's iterating through each order and adding each value.

This uses the SUM sql operator to boost performance.

### CODE REVIEW

**Comment by JDutil** [comment]
Perhaps there should be a migration to update all legacy null currency orders to have the default currency.

**Comment by jhawthorn** [comment]
:+1: for updating all orders, which will also allow us to remove that code from order.

**Comment by JDutil** [comment]
@imella could you please update this with the migration & remove the Order#currency method.

**Comment by JDutil** [comment]
This breaks the specs I suspect because we removed the Order#currency method, and them needing the default configuration fallback.

**Comment by bbonislawski** [comment]
This PR is stale and I'm closing it for know. If anyone wants to update it with specs, please let me know and I'll reopen this PR.

**Pull request closed without merging**
