### PR TITLE
Optimised Store model

### PR DESCRIPTION
**Pull request by dilpreet92**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://dilpreet92-optimise-store.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://dilpreet92-optimise-store.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by Mafi88** [comment]
:+1: 

@priyank-gupta, any thoughts?

**Comment by priyank-gupta** [comment]
@dilpreet92 Please rebase this with master's latest code.

**Comment by dilpreetwal** [comment]
@priyank-gupta Done

**Comment by dilpreet92** [comment]
@priyank-gupta Done

**Comment by priyank-gupta** [comment]
@dilpreet92 I think your store#current optimised code is no more present in this PR. Have you removed it ?

**Comment by dilpreet92** [comment]
@priyank-gupta - I have removed the current_store logic as it was failing when Store.by_url(domain).first returns nil. So eventually current_store will return nil which will break the application flow.

**Comment by priyank-gupta** [comment]
:+1:

**Pull request merged**
