### PR TITLE
Delete Taxon bug

### PR DESCRIPTION
**Pull request by yurifrl**
Don't know if you still using jconfirm, but it was not working when deleting taxonomies

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://azclick-bug-fix-jconfirm.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by cbrunsdon** [comment]
My vote would be remove jconfirm rather than adding it back in as a dependency.

**Comment by JDutil** [comment]
Deleting taxonomies is working fine for me on master branch, and rails 4.2 branch shouldn't be too out of date but will look into it there as well.

**Comment by yurifrl** [comment]
Sorry, I meant taxon, that little drop-down that display the taxon of a taxonomy

**Pull request closed without merging**
