### PR TITLE
Not all cultures use "@" to delimitate a quantity

### PR DESCRIPTION
**Pull request by rposborne**
this allows this to be translatable.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://burningpony-translate-at-sign.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://burningpony-translate-at-sign.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
That's not a multiplier symbol it's an at symbol meaning the product is being purchased at that price.  Perhaps change the i18n key to be :at_symbol or something like that.

**Comment by rposborne** [comment]
Yea, I wasn't 100% on the name of the key.   ```: at_symbol``` it is.

**Comment by rposborne** [comment]
@JDutil let me know if you need anything else for this.

**Comment by JDutil** [comment]
Thanks

**Pull request closed without merging**
