### PR TITLE
Fix order deadlocks

### PR DESCRIPTION
**Pull request by JDutil**
- Remove unneded DB state cleanup
- Remove unneded stubbing of private interface
- Remove unneded memoization layer
- Remove spec setup duplication
- Fix specification holes for #current_order
- Fix locking for all query paths in #current_order
- Removes Spree::User.last_incomplete_spree order.
- Adds collection Spree::User.incomplete_spree orders for being able to
  lock records in one DB round trip
- Remove redundant persistance call
- Fix public interface smell
  - Refactor options based semantics of current_order out into cart_order
    method.
  - Removes the options paramter, making the methods properly memoizable
- Fix memoizers to memoize nil correctly
  - The current_order helper used to query for the same inexisting rows
    per call to `current_order`. There is only one call side that
    invalidates the current_order cache via active writes to the
    `@current_order` ivar.
- Fix tuple order to be deterministic
- Fix specification holes in #set_current_order
- Add specs that cover all selection logic
- Do not pass redundant user argument to Order#merge!
  When orders are found by current user, there is no need to pass it in.
- Add locking to #set_current_order
- Remove simple_current_order interface
- Refactor Spree::Core::ControllerHelpers::Order#cart_order
- Refactor Spree::Core::ControllerHelpers::Order#current_order
- This change centralizes all the merging of incomplete user and
  anonymous orders.
- Change order to always be associated to the user when set.
- Remove fix for #3346 since the created_by field is always set when
  associating the order to the user.
- Simplify specs to not depend on the implementation of current_order
- Refactor Spree::Core::ControllerHelpers::Order#current_currency
- Remove code that isn't necesarry from the specs and library
- Change Spree::Order.incomplete to return orders from newest to oldest
- Remove Spree::LegacyUser#incomplete_spree_orders
- Remove Spree::Core::ControllerHelpers::Order#current_order_params
- Kill mutations in Spree::Core::ControllerHelpers::Order

Conflicts:
    api/app/controllers/spree/api/orders_controller.rb
    core/app/helpers/spree/base_helper.rb
    core/config/initializers/user_class_extensions.rb
    core/lib/spree/core/controller_helpers/order.rb
    frontend/app/controllers/spree/checkout_controller.rb
    frontend/app/controllers/spree/orders_controller.rb
    frontend/app/controllers/spree/store_controller.rb
    frontend/spec/controllers/spree/orders_controller_spec.rb

Fixes #2683 

/cc @mbj @tesserakt @jasonfb I've attempted to cherry-picking @mbj and his teams work from https://github.com/MountainRoseHerbs/spree/commit/8e040d24daa20f3befba3fe38eebf369fe35ae11#diff-0a7e681efdb2cb600526df2c5af10039 to apply against master branch here.  Will see what specs have to say, and would be good to get your feedback.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://jdutil-fix-2683.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://jdutil-fix-2683.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by tesserakt** [comment]
Fantastic!! 

Would it be possible to add state machine transactions to this? When we did that a lot of our corrupted/double issues went away.

**Comment by JDutil** [comment]
@tesserakt I'm open to the idea, but I don't really have time to track down broken specs if there are any.  Would you want to give it a shot? Can PR against this branch or master when this is complete.

**Comment by tesserakt** [comment]
@JDutil yes I will look at a PR when this is complete. Awesome work again.

**Comment by JDutil** [comment]
@mbj I fixed all but these for specs not sure if you know what's wrong:

```
Failures:

  1) Spree::Core::ControllerHelpers::Order#current_order when the user is present with an incomplete order with a guest token with anonymous orders returns an order
     Failure/Error: controller.current_order
     RuntimeError:
       Can't modify frozen hash
     Shared Example Group: "order found" called from ./spec/lib/spree/core/controller_helpers/order_spec.rb:62
     Shared Example Group: "incomplete order returned" called from ./spec/lib/spree/core/controller_helpers/order_spec.rb:194
     # ./app/models/spree/order.rb:271:in `associate_user!'
     # ./lib/spree/core/controller_helpers/order.rb:78:in `find_order_by_token_or_user'
     # ./lib/spree/core/controller_helpers/order.rb:21:in `current_order'
     # ./spec/lib/spree/core/controller_helpers/order_spec.rb:30:in `apply'
     # ./spec/lib/spree/core/controller_helpers/order_spec.rb:35:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:71:in `block (2 levels) in <top (required)>'

  2) Spree::Core::ControllerHelpers::Order#current_order when the user is present with an incomplete order with a guest token with anonymous orders merges the anonymous order into the incomplete order
     Failure/Error: controller.current_order
     RuntimeError:
       Can't modify frozen hash
     # ./app/models/spree/order.rb:271:in `associate_user!'
     # ./lib/spree/core/controller_helpers/order.rb:78:in `find_order_by_token_or_user'
     # ./lib/spree/core/controller_helpers/order.rb:21:in `current_order'
     # ./spec/lib/spree/core/controller_helpers/order_spec.rb:30:in `apply'
     # ./spec/lib/spree/core/controller_helpers/order_spec.rb:199:in `block (7 levels) in <top (required)>'
     # ./spec/spec_helper.rb:71:in `block (2 levels) in <top (required)>'

  3) Spree::Core::ControllerHelpers::Order#current_order when the user is present with an incomplete order with a guest token with anonymous orders sets the created_by attribute in the order
     Failure/Error: controller.current_order
     RuntimeError:
       Can't modify frozen hash
     Shared Example Group: "order found" called from ./spec/lib/spree/core/controller_helpers/order_spec.rb:62
     Shared Example Group: "incomplete order returned" called from ./spec/lib/spree/core/controller_helpers/order_spec.rb:194
     # ./app/models/spree/order.rb:271:in `associate_user!'
     # ./lib/spree/core/controller_helpers/order.rb:78:in `find_order_by_token_or_user'
     # ./lib/spree/core/controller_helpers/order.rb:21:in `current_order'
     # ./spec/lib/spree/core/controller_helpers/order_spec.rb:30:in `apply'
     # ./spec/lib/spree/core/controller_helpers/order_spec.rb:43:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:71:in `block (2 levels) in <top (required)>'

  4) Spree::Core::ControllerHelpers::Order#current_order when the user is present with an incomplete order with a guest token with anonymous orders returns the incomplete order
     Failure/Error: controller.current_order
     RuntimeError:
       Can't modify frozen hash
     Shared Example Group: "incomplete order returned" called from ./spec/lib/spree/core/controller_helpers/order_spec.rb:194
     # ./app/models/spree/order.rb:271:in `associate_user!'
     # ./lib/spree/core/controller_helpers/order.rb:78:in `find_order_by_token_or_user'
     # ./lib/spree/core/controller_helpers/order.rb:21:in `current_order'
     # ./spec/lib/spree/core/controller_helpers/order_spec.rb:30:in `apply'
     # ./spec/lib/spree/core/controller_helpers/order_spec.rb:65:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:71:in `block (2 levels) in <top (required)>'

  5) Spree::Core::ControllerHelpers::Order#current_order when the user is present with an incomplete order with a guest token with anonymous orders returns a persisted order
     Failure/Error: controller.current_order
     RuntimeError:
       Can't modify frozen hash
     Shared Example Group: "order found" called from ./spec/lib/spree/core/controller_helpers/order_spec.rb:62
     Shared Example Group: "incomplete order returned" called from ./spec/lib/spree/core/controller_helpers/order_spec.rb:194
     # ./app/models/spree/order.rb:271:in `associate_user!'
     # ./lib/spree/core/controller_helpers/order.rb:78:in `find_order_by_token_or_user'
     # ./lib/spree/core/controller_helpers/order.rb:21:in `current_order'
     # ./spec/lib/spree/core/controller_helpers/order_spec.rb:30:in `apply'
     # ./spec/lib/spree/core/controller_helpers/order_spec.rb:39:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:71:in `block (2 levels) in <top (required)>'

  6) Spree::Core::ControllerHelpers::Order#current_order when the user is present with an incomplete order with a guest token with anonymous orders eager loads all adjustments
     Failure/Error: controller.current_order
     RuntimeError:
       Can't modify frozen hash
     Shared Example Group: "order found" called from ./spec/lib/spree/core/controller_helpers/order_spec.rb:62
     Shared Example Group: "incomplete order returned" called from ./spec/lib/spree/core/controller_helpers/order_spec.rb:194
     # ./app/models/spree/order.rb:271:in `associate_user!'
     # ./lib/spree/core/controller_helpers/order.rb:78:in `find_order_by_token_or_user'
     # ./lib/spree/core/controller_helpers/order.rb:21:in `current_order'
     # ./spec/lib/spree/core/controller_helpers/order_spec.rb:30:in `apply'
     # ./spec/lib/spree/core/controller_helpers/order_spec.rb:51:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:71:in `block (2 levels) in <top (required)>'

  7) Spree::Core::ControllerHelpers::Order#current_order when the user is present with an incomplete order with a guest token with anonymous orders sets the last_ip_address attribute in the order
     Failure/Error: controller.current_order
     RuntimeError:
       Can't modify frozen hash
     Shared Example Group: "order found" called from ./spec/lib/spree/core/controller_helpers/order_spec.rb:62
     Shared Example Group: "incomplete order returned" called from ./spec/lib/spree/core/controller_helpers/order_spec.rb:194
     # ./app/models/spree/order.rb:271:in `associate_user!'
     # ./lib/spree/core/controller_helpers/order.rb:78:in `find_order_by_token_or_user'
     # ./lib/spree/core/controller_helpers/order.rb:21:in `current_order'
     # ./spec/lib/spree/core/controller_helpers/order_spec.rb:30:in `apply'
     # ./spec/lib/spree/core/controller_helpers/order_spec.rb:47:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:71:in `block (2 levels) in <top (required)>'

  8) Spree::Core::ControllerHelpers::Order#current_order when the user is present with an incomplete order with a guest token with anonymous orders is idempotent
     Failure/Error: controller.current_order
     RuntimeError:
       Can't modify frozen hash
     Shared Example Group: "idempotent method" called from ./spec/lib/spree/core/controller_helpers/order_spec.rb:195
     # ./app/models/spree/order.rb:271:in `associate_user!'
     # ./lib/spree/core/controller_helpers/order.rb:78:in `find_order_by_token_or_user'
     # ./lib/spree/core/controller_helpers/order.rb:21:in `current_order'
     # ./spec/lib/spree/core/controller_helpers/order_spec.rb:30:in `apply'
     # ./spec/lib/spree/core/controller_helpers/order_spec.rb:22:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:71:in `block (2 levels) in <top (required)>'
```

**Comment by mbj** [comment]
@JDutil There is a reason I was NOT doing this like done in this PR. This patch depends on others in our tree. It *can* work out to apply it standalone, but I expect this to be more work than in order.

Also it requires something like this in `application_controller.rb`

```ruby
class ApplicationController
  # Wrap all actions in a transaction
  around_action :wrap_in_transaction

  TRANSACTION_OPTIONS = IceNine.deep_freeze(isolation: :read_committed)

  # Wrap block in a read_committed transaction
  #
  # @return [undefined]
  #
  # @api private
  #
  def wrap_in_transaction(&block)
    ActiveRecord::Base.transaction(TRANSACTION_OPTIONS, &block)
  end
end
```

RE spec errors: We freeze certain objects that should not be mutated, seems the code in master (or the resolution of merge errors you did) does a mutation to an object that is not supposed to be mutated.

As I'm on vacation right now (thats also the reason I did not contacted you jet for a hangout) I cannot easily look into it right now.

I'll be back next week and will look into this.

**Comment by JDutil** [comment]
Well I was interested to see how it would apply against master so took a shot at it.  Can always wait until the other stuff is done in order, but it should apply to master when ready easier now once I squash commits.

**Comment by tesserakt** [comment]
@mbj How do you handle the case when placing an order of starting the transaction, then someone decrements the inventory after the check that all items are in stock? Wouldn't you want isolation level :serializable to prevent against that?

**Comment by tesserakt** [comment]
@JDutil could we not put the transaction wrapping code in the Spree::BaseController and Spree::Admin::BaseController?

**Comment by tesserakt** [comment]
@mbj also what extra commits are needed?

**Comment by tesserakt** [comment]
@mbj confirmed that only serializable fixes our issue with multiple people trying to change the inventory after you have gotten past the point where the order processing checks if it can fulfill the order (in the payment -> complete step). Perhaps read_committed could go everywhere else.

**Comment by mbj** [comment]
I'll reply deeply later the week, currently too busy with private measures. Also our client project will soon run code closer to master allowing me to upstream this in a more efficient way.

**Comment by tesserakt** [comment]
@mbj any thoughts?

**Comment by mbj** [comment]
> @mbj any thoughts?

We run serializable transactions around all actions. As the original patch fixes all locking paths to lock the order properly all cart related deadlocks are gone for us.

We needed to reduce touching objects a bit to prevent cart actions leaking activity into shared rows.

My clients time is still blocked by other issues, I'll continue to upstream the diff in the order its applied to our spree fork. I cannot easily support @JDutil attemts to apply the patches out of our order at this point.

**Comment by bbonislawski** [comment]
I know that this took a lot of job, but Spree changed so much since that time, that I'm closing this since it's impossible to apply this to current master branch. 

If you think that it's not outdated, please mention me in comment and I'll reopen it

**Pull request closed without merging**
