### PR TITLE
Add disable_with option to prevent multiple request on consecutive clicks

### PR DESCRIPTION
**Pull request by nimish13**

### CODE REVIEW

**Comment by damianlegawiec** [comment]
Hi @nimish13 we've already got a translation for `disable_with` - check:

https://github.com/spree/spree/blob/210cc29b1ad763bae2722e20ccf787619b2db8d2/backend/app/views/spree/admin/shared/_new_resource_links.html.erb#L2

Besides that 👍

**Comment by nimish13** [comment]
Hi @damianlegawiec  the [commit](https://github.com/spree/spree/blob/210cc29b1ad763bae2722e20ccf787619b2db8d2/backend/app/views/spree/admin/shared/_new_resource_links.html.erb#L2) you are referring to is solving only a particular case but what I have fixed is pretty generic and helps at all the places where `button` helper_method is being used. For example.
([return_authorizations](https://github.com/spree/spree/blob/8bfa0824d2a7f6cfa6efc9bd4e32d1d564f6270b/backend/app/views/spree/admin/return_authorizations/new.html.erb#L15), [adjustments/edit]( https://github.com/spree/spree/blob/8bfa0824d2a7f6cfa6efc9bd4e32d1d564f6270b/backend/app/views/spree/admin/adjustments/edit.html.erb#L14), [shared/_edit_resource_links)](https://github.com/spree/spree/blob/210cc29b1ad763bae2722e20ccf787619b2db8d2/backend/app/views/spree/admin/shared/_edit_resource_links.html.erb#L2)

**Comment by tanmay3011** [comment]
@nimish13 Squash commits

**Comment by damianlegawiec** [comment]
@nimish13 rather than using `Spree.t(:disable_with)` let's reuse already existing `Spree.t(:saving)` - that's what I've meant :)

**Comment by nimish13** [comment]
@damianlegawiec @tanmay3011 PR updated

**Comment by damianlegawiec** [comment]
Thanks @nimish13 👍

**Pull request merged**
