### PR TITLE
add product_path for link_to in _line_item

### PR DESCRIPTION
**Pull request by caiqinghua**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://caiqinghua-master.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://caiqinghua-master.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
I don't think this is necessary. Is there a particular reason your doing this?

**Comment by caiqinghua** [comment]
First, if we should modify the product_path to shop_product_path, we will forget this one, because it cant finded by texteditor. 
Second, Look line 13 in this file, should we keep the same style?

**Comment by JDutil** [comment]
We won't be changing the route so that shouldn't be an issue, but for consistency they should all be changed to `spree.product_path(variant.product)` if anything.

**Comment by caiqinghua** [comment]
Can i  pull a request to change them to spree.product_path(variant.product)?

**Comment by JDutil** [comment]
Sure please resubmit separately the other scope changes.

**Pull request closed without merging**
