### PR TITLE
fixes https://github.com/spree/spree/issues/5787 on 2-2-stable

### PR DESCRIPTION
**Pull request by jasonfb**
fixes infinite recursion associated with CreateLineItem promotion action

see https://github.com/spree/spree/issues/5787

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://jasonfb-2-2-stable.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://jasonfb-2-2-stable.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
Would be good to have a regression spec for this.

**Comment by jasonfb** [comment]
Indeed. I will see what I can do about that.

**Comment by jasonfb** [comment]
we have an alternative fix for this. will report back soon.

**Comment by jasonfb** [comment]
replaced with https://github.com/spree/spree/pull/6310

**Pull request closed without merging**
