### PR TITLE
locking rspec-rails at 3.3.x for now

### PR DESCRIPTION
**Pull request by damianlegawiec**

### CODE REVIEW

**Comment by mbj** [comment]
Just curious, why? The commit message `locking rspec-rails at 3.3.x for now` does not really explain the problem this change tries to avoid.

**Comment by damianlegawiec** [comment]
@mbj  rspec-rails 3.4.1 breaks some 3 examples in ability_spec - we have to investigate further

**Comment by mbj** [comment]
Another question why did you merge this PR when a CI was red? Is green CI not considered mandatory anymore? (I know these are indeterminism failures, but if maintainers do not have the time to rebuild before merge the build history of this project becomes less of value).

**Comment by damianlegawiec** [comment]
@mbj all checks are required before the merge (Circle CI and Hound). At the time of merge all was green. It was this one time that I didn't run it twice. Current specs status is funky and it's on top of our list of priorities to fix - it would be great if you could help us with it :)

**Comment by lightcap** [comment]
> It was this one time that I didn't run it twice.

I've found it helpful to require that a team member other than the person that opened the PR be the one to merge.

**Comment by damianlegawiec** [comment]
@lightcap that's our usual workflow, check other PRs

**Pull request merged**
