### PR TITLE
Remove unused method from Spree::OrderUpdater

### PR DESCRIPTION
**Pull request by mbj**
Its dead code. Ideally you guys would run coverage analysis to kill dead code like this during development cycles.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://mountainroseherbs-fix-dead-code.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://mountainroseherbs-fix-dead-code.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by mbj** [comment]
@JDutil Changes you can backport this one to 2-4 and 2-3-stable? Should apply clean AFAIK.

**Comment by JDutil** [comment]
done

**Comment by mbj** [comment]
thx

**Pull request closed without merging**
