### PR TITLE
Strip out ssl options from settings / codebase

### PR DESCRIPTION
**Pull request by cbrunsdon**
ssl_required and ssl_allowed are historical relics of yore.

In 2014 any ecommerce site should enforce SSL on all connections. This
can either be set in rails, or handled at a web server/load balancer
layer, and the logic does not need to leak into the spree engine.

To handle in rails see:
http://api.rubyonrails.org/classes/ActionController/ForceSSL/ClassMethods.html

### CODE REVIEW

**Comment by JDutil** [comment]
I've been pushing for removing this ssl stuff for awhile as I had to update it to allow my store to use config.force_ssl.  I got a bunch of pushback on this though as people wanted the ability to force people back to http for caching or something like that...

I think we should at least probably point people to the rails force_ssl documentation in the guides that are being removed for newbies though, and possibly even have a check to ensure force_ssl is set for production.  If we're not going to check force_ssl is set for the app than we should still be adding force_ssl to the required controllers though.  Inevitably there will be new users who don't get this concept, and them trying to navigate to checkout in production should result in a https request by default whether they've set it up or not.

**Comment by cbrunsdon** [comment]
We don't use config.force_ssl as we do our wrapping/unwrapping and enforcing at the server layer, so I'd be opposed to any checks that forced config.force_ssl to be set in prod. I will update the docs to point to rails config.force_ssl, though.

**Comment by cbrunsdon** [comment]
Okay, I've updated the guides to explain how to force ssl through an application

**Comment by JDutil** [comment]
The places where ssl_required has been removed should have force_ssl at the controller level still to prevent users from mistakingly not setting up SSL.

**Comment by gmacdougall** [comment]
I am opposed to force_ssl at the controller level. Being an e-commerce site, I feel that all requests should be over HTTPS.

This can be managed either at the rails level `config.force_ssl = true` at the rails application level (outside of the Spree engine) or at some level higher in the stack (such as nginx, or a load balancer level. It should be up to the site admin to ensure that their SSL policy is being adhered to.

**Comment by JDutil** [comment]
I understand it's easy to do, and that's how I setup sites I develop.  I think removing the checks enforcing it's usage by default in production underestimates many peoples ability to RTFM, and lack of understanding security best practices.  It doesn't hurt anything to continue enforcing SSL where necessary, and the check won't do anything if you set it at the application level or higher in the stack.  It still allows you to remove this code, and still prevents people from being their own worst enemy in security.

**Comment by JDutil** [comment]
Although just realized the API doesn't enforce ssl at all just backend/frontend so I suppose we're not even doing the default enforcement completely...

**Comment by wuboy0307** [comment]
For those who still need http request in some static pages, you can use rack-ssl-enforcer.
http://stackoverflow.com/questions/10605407/force-ssl-for-specific-routes-in-rails-3-1
https://github.com/tobmatth/rack-ssl-enforcer

**Pull request closed without merging**
