### PR TITLE
Whole Order Discounts That Calculate Tax Per Line Item

### PR DESCRIPTION
**Pull request by MatthewKennedy**
## The Issue #9231
In Spree 2.1 and earlier tax adjustments were applied to the order, as a whole.
As of Spree 2.2 tax is applied to the line items individually, and rightfully so.
https://github.com/spree/spree/blob/98043a957ce3f89f59cf5aaea6a58e392a087b56/core/app/models/spree/calculator/default_tax.rb#L12

But this caused issues moving forward with tax not being calculated properly on whole order discounts. This could be seen when a Discount is created set to the following:
https://github.com/spree/spree/issues/9231#issuecomment-521140416

-  **ACTION:** Whole-order adjustment
-  **CALCULATOR:** Flat Rate
-  **AMOUNT:** $19.99
-  **CURRENCY:** USD

Then add a single $19.99  item to cart that is taxed, proceeds to checkout and enter a U.S. address and proceed to the shipping section of checkout to trigger the sales tax.

Go back to cart and apply your newly created whole order discount code, the order total should be $0.00 but you will still see that the tax is there from the line item, as the whole order discount calculator simply takes the order total and deducts the Flat Rate Amount regardless of taxes.

## This Pull Request
In this pull request the issue is solved* taking whole order discounts and applying them at a line item level.

For Example the Flat Rate calculator in this pull request takes the Flat Rate fixed amount and apportions it amongst the line items in an order proportionally to the line items percentage of subtotal (all line items not including shipping or tax).
https://github.com/MatthewKennedy/spree/blob/dafb55a3bc0ad59721486f1e9fab8a02aebeda03/core/app/models/spree/calculator/flat_rate.rb#L14

## Still Needs Fixing

1. When the promotion is applied, you may need to click the cart update button a second time to properly get the tax calculated. Not sure why this is, possibly need to call the tax update somewhere in this, any advice would be greatly appreciated.

2. Needs testing with various tax scenarios, tax included tax not included, taxed and none taxed items all mixed in the cart together, (until issue 1 is fixed you may need to update the cart a second time make sure correct tax is calculated if new line items have been added or removed).

Please let me know, if you find issues.

### CODE REVIEW

**Comment by MatthewKennedy** [comment]
too much to fix, going to look at at it a fresh

**Comment by Quintasan** [comment]
@MatthewKennedy I'm willing to collaborate on that if you have time to work on this in near future. My company needs this feature pretty soon :)

**Comment by MatthewKennedy** [comment]
@Quintasan Try the forks listed below and tell me what you find, set each up in a fresh local copy of spree.

If you create discounts using the first gem then switch the project over to the second gem you may find issues occur, as the second gem removes the whole-order action, and relies on discounting Line items as that is where the tax is and that's where you want the discount to come off.

### Basic Implementation Not Perfect
`gem 'spree', github: 'spree-versions/spree '` 
This implementation takes the existing Whole Order action and bends it towards line item adjustment.

But really in spree tax is calculated at the line item level so really there should only be line-item based discounts, hence project 2 below.


### Better Way of Working But Has Some Major Changes
`gem 'spree', github: 'matthewkennedy/spree '` 
This second one is a more ideal way of working but if you have a project with existing discounts you would need to delete them and re-create them once you have changed over to this gem, so ideally test this on a separate fresh spree install, clear browser cache possibly.

To Use the second fork (matthewkennedy/spree) with a fixed amount discount that calculates tax set up a discount as in the image below:

Screenshot 2019-08-20 at 10 30 59


**Again, do NOT use any of these on live projects.**

**Comment by Quintasan** [comment]
@MatthewKennedy From my perspective the first approach is better since it wouldn't require any additional work. I have about 16k promotional codes and recreating them would be... tedious to say the least. Is there any "breaking point" of this solution?

Also I think we still have a problem with the amount calculated (zł means PLN)

image

Base price: 60 PLN
Tax (included in price): 60 * 0.23 = 13.8 PLN

Price after discount: 10 PLN
Tax (included in price): 10 * 0.23 = 2.3 PLN

I have no clue how did it come up with  1.87 PLN

**Comment by MatthewKennedy** [comment]
Hi @Quintasan 

1.87 PLN is correct on tax included in 10 PLN see VAT Calculator at:  http://www.vatcalculator.co.uk/
Set the VAT amount to 23% enter 10 and click remove VAT.


Screenshot 2019-08-20 at 14 21 05

**Comment by Quintasan** [comment]
@MatthewKennedy damn, it's almost 4 o'clock and I'm still not running on full-throttle I guess. It does make sense now that I think about how is this supposed to work.

I didn't take a very good look at the code yet but I appears to me that going with the second approach would be the best in the long term.

**Comment by MatthewKennedy** [comment]
@Quintasan I’m going to be doing more testing myself.

The second version would be better for Spree, neater and make more sense, as long as some fallbacks are written in so it doesn’t brake any existing promotions.

In your scenario it might be easiest to Generate a Spree extension with a custom  action and rule specifically for this case if it’s needed soon.

**Comment by MatthewKennedy** [comment]
A mixed order of taxed and none taxed items is also correct depending on rounding, in this example the top 2 items have tax in price last item has no tax.


Screenshot 2019-08-20 at 16 21 33

Screenshot 2019-08-20 at 16 09 39

Line1 new price after discount is:  $95.38 
($100 / $215.99 = 0.462 * $10 = $4.62) ($100 - $4.62 = $95.38 )

Line2 new price after discount is:  $15.25
($15.99 / $215.99 = 0.0740 * $10 = $0.74) ($15.99 - $0.74 = $15.25 )

Line3 no tax no need to worry about that.

95.38 + 15.25 = $110.63 that includes tax in this order.

Screenshot 2019-08-20 at 16 19 55

**Comment by MatthewKennedy** [comment]
@Quintasan Try this Spree Extension and let me know how you get on.
https://github.com/MatthewKennedy/spree_fixed_amount_discount

**Comment by Quintasan** [comment]
@MatthewKennedy works good on my application :D

**Comment by Quintasan** [comment]
@MatthewKennedy Can this discount somehow be applied to LineItem adjustments or it's going to require heavy hackery?

I found out that some products here have `Express Delivery` which adds 30% of the base price as an adjustment and it should be covered using the cupon code as well.

**Comment by MatthewKennedy** [comment]
Hi @Quintasan,

I don’t think that’s something I could do.

There is a also a rounding error that occurs in the I’m currently looking into fixing.

**Comment by MatthewKennedy** [comment]
Hi @Quintasan 

I have fixed the occasional rounding error that occurred in the extension. Prior to this update when a lot of line items where added to the order, occasionally the discounted amount would be 1 cent above or under the specified Fixed Amount.

And also you can now set Product based rules and the fixed amount will divide evenly between just the products that have been set in the promotion products rule.

If you get change on a local project update the extension and let me know how you get on, test out all existing promotions that you use and make sure they all work as before, as this update overrides  a few more files in the spree core to get this extension working properly.

**Comment by Quintasan** [comment]
@MatthewKennedy thanks, this one works but it looks like the scope of the feature I want changed.

In https://github.com/MatthewKennedy/spree_fixed_amount_discount/blob/03caafb517c378f4395f6dc14597cb26c59db9fc/app/models/spree/calculator/line_items_flat_rate.rb#L21 `object.amount` refers to the total cost of LineItem which is calculated by doing `price * quantity`.

Is it somehow possible to include all adjustments done on LineItem into that discount as well?

The case I have is simple: product A costs 35 EUR, we have a discount code for 50 EUR. User can select Express Delivery which adds 30% of the cost of the `LineItem` as an adjustment and we'd like the cupon to cover that as well.

**Pull request closed without merging**
