### PR TITLE
Spree Issue #5842 - Fix i18n for pluralized resource names in backend

### LINKED ISSUE #5842: human(count: :many) raises exception for locales with specific pluralization, such as :ru and is unsafe for :en
rails 4.1.8
config.i18n.default_locale = :en
2.1.5 :001 > Spree::Order.model_name.human(:count=>:one)
 => "Orders"  #used :other
2.1.5 :002 > Spree::Order.model_name.human(:count=>:many)
 => "Orders" #used :other

config.i18n.default_locale = :ru
.human(count: :many)- causes error:
"undefined method `%' for :many:Symbol"

For example, in rails console:
Spree::Order.model_name.human(count: :one)- error
Spree::Order.model_name.human(count: :many)- error
Spree::Order.model_name.human(count: :1)- works right
Spree::Order.model_name.human(count: :5)- works right

### PR DESCRIPTION
**Pull request by RaVbaker**
Fixes #5842 and it's done similar way to https://github.com/activeadmin/activeadmin/pull/2791

It is strongly useful for languages with custom pluralization mechanisms in rails_i18n gem (e.g. Russian, Polish...)

I believe it can be applied to multiple branches. 

If I screwed anything let me know. It's my first contribution to **spree** project.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://ravbaker-fix-plural-i18n.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://ravbaker-fix-plural-i18n.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by reinaris** [comment]
Didn't looked at what you contributed but just :+1: for your first contribution!

**Comment by RaVbaker** [comment]
@JDutil I just rebased it to the latest master for smooth auto-merge. Let's wait for CI to pass.

**Comment by BenMorganIO** [comment]
:+1:

**Comment by JDutil** [comment]
Thanks for the first contribution @RaVbaker

**Pull request closed without merging**
