### PR TITLE
Add case insensitive uniqueness to shipping_method

### PR DESCRIPTION
**Pull request by aishmita-aggarwal**

### CODE REVIEW

**Comment by damianlegawiec** [comment]
@aishmita-aggarwal why `allow_blank: true` ? It kinda total opposite of presence validation already in place. Shipping method needs to have a name :)

**Comment by aishmita-aggarwal** [comment]
@damianlegawiec  Adding allow blank will reduce a query of uniqueness validation in case of blank data input. And without this option, user would receive error messages for both absence and uniqueness, which is again not required for blank data input.

**Comment by damianlegawiec** [comment]
@aishmita-aggarwal this is hacky and can change in future version of rails. Not declarative, not readable. Sorry but not acceptable.

**Comment by damianlegawiec** [comment]
Closing all uniqueness validation PRs in favour of one big PR doing it right (DB level + app level) for 3.2 release.

**Pull request closed without merging**
