### PR TITLE
Delete validators/email.rb in lib/validators and move them to app/validators

### PR DESCRIPTION
**Pull request by nishant-cyro**

### CODE REVIEW

**Comment by priyank-gupta** [comment]
:+1: 
@damianlegawiec @Mafi88 ?

**Comment by priyank-gupta** [comment]
@nishant-cyro Rebase with latest master.

**Comment by nishant-cyro** [comment]
@priyank-gupta - done.

**Comment by damianlegawiec** [comment]
@nishant-cyro why are we moving this to the new destination? What are the pros of this change?

**Comment by nishant-cyro** [comment]
@damianlegawiec - there are two folders for validators - lib/validators and app/validators. So, it will be good to have them in one place.

**Comment by damianlegawiec** [comment]
:-1: 

This will break spree_auth_devise:

https://github.com/spree/spree_auth_devise/blob/master/lib/controllers/frontend/spree/checkout_controller_decorator.rb#L1

**Comment by nishant-cyro** [comment]
@damianlegawiec - Good catch, I guess we should deprecate the lib/validators and remove it in next version. Any thoughts?

**Comment by nishant-cyro** [comment]
@damianlegawiec - Deprecated validators/email.rb instead of removing it. Please let me know if this looks fine to you.

**Comment by nishant-cyro** [comment]
@damianlegawiec - Any update on this?

**Comment by bbonislawski** [comment]
Rebased in #8612

**Pull request closed without merging**
