### PR TITLE
[Admin End] Add missing translations for order state changes

### PR DESCRIPTION
**Pull request by nimish13**
Some translations were missing for order state changes when we go to state changes tab for a particular order.

### CODE REVIEW

**Comment by nnande** [comment]
Hello @nimish13
Actually ```core/config/locales/en.yml``` contains all the state change translations.

payment: https://github.com/spree/spree/blob/master/core/config/locales/en.yml#L1031
shipment: https://github.com/spree/spree/blob/master/core/config/locales/en.yml#L1272

We just have to fix [the view](https://github.com/spree/spree/blob/master/backend/app/views/spree/admin/state_changes/index.html.erb) to the existing translations.
Could you take care of that, please?

**Comment by nimish13** [comment]
@nnande I looked into the code. 
For payment states scope is ``payment_states``
For shipment states scope is ``shipment_states``
For order states scope is ``order_state``
There needs to be consistency among the scope names for these ``state_change`` names.

If we use nested scope here then we may need to change ``order_state`` scope to ``order_states`` everywhere else in SPREE

**Comment by nnande** [comment]
@nimish13 "There needs to be consistency among the scope names for these state_change names."
I totally agree with you, let's switch to ```order_states``` key and refactor the Spree usages!

Having things standarized, we could change [the view](https://github.com/spree/spree/blob/master/backend/app/views/spree/admin/state_changes/index.html.erb) to perform below:
```
Spree.t(state_change.previous_state, scope: "# { state_change.name }_states")
```

I would suggest using ```resource_states``` scoping within locale file, which, in comparison with adding new translations, makes it more organized and clear.

**Comment by nimish13** [comment]
@nnande Changes done. Please review.

**Review by nnande — APPROVED** [review]

**Review by damianlegawiec — CHANGES_REQUESTED** [review]
@nimish13 please fix this failing spec:

```
Order - State Changes for completed order are viewable - spec.features.admin.orders.state_changes_spec
spec/features/admin/orders/state_changes_spec.rb
moreexpected to find text "Cart" in "cart". (However, it was found 1 time using a case insensitive search.)
```

**Comment by nimish13** [comment]
@damianlegawiec Changes done. Please review :)

**Comment by tanmay3011** [comment]
@nimish13 Please squash commits.

**Comment by nimish13** [comment]
@tanmay3011 Done with squashing. Please review :)

**Comment by nimish13** [comment]
@damianlegawiec Any updates on this? :)

**Review by damianlegawiec — APPROVED** [review]

**Comment by damianlegawiec** [comment]
@nimish13 merged, thank you! :)

**Comment by nimish13** [comment]
@damianlegawiec  cheers 👍

**Pull request merged**
