### PR TITLE
Fix spec determinism

### PR DESCRIPTION
**Pull request by mbj**
This PR upstreams the fixes for (almost) all sources of indeterminism we found in the 2-3-stable branch

I see that master build on CircleCI are still affected by all sorts of indeterminism, and sporadic failures. Many of these should go away with this PR.

We also add `--order random` rspec option to the builds on Circle (note NOT to the developers local spec runs, but we highly recommend to do so soon) with this PR allowing to identify even more sources of indeterminism.

For our 2-3-stable fork this patch set reduced the "random failure rate" by both headless and more unit a like specs by a magnitude.

I'll remove the `[WIP]` tag in this branches title once all builds for each commit are green against master.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://mountainroseherbs-fix-spec-determinism.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://mountainroseherbs-fix-spec-determinism.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by mbj** [comment]
@JDutil Under the assumption all builds are green the moment you look at this PR this is ready for review.

**Comment by mbj** [comment]
All green, first build no restarts involved. We still must assume there are more in deterministic specs in the code base but this PR should at least reduce the pain a bit, ideally a magnitude, but we'll see.

**Comment by mbj** [comment]
Sorry, accidentally deleted that branch. @JDutil still ready for review ;)

**Pull request closed without merging**
