### PR TITLE
Replace order strings with symbols/arel_table

### PR DESCRIPTION
**Pull request by wuboy0307**
refer from https://github.com/solidusio/solidus/pull/37

### CODE REVIEW

**Comment by Mafi88** [comment]
@wuboy0307 
It seems to work correctly and looks much nicer.
Since you've already made such modifications, I think it would be much better to also change

https://github.com/wuboy0307/spree/blob/ba51b85f611d3ba39be55928b5c211cdf0d00877/core/app/models/spree/product/scopes.rb#L50
to
```
joins(:master => :default_price).where(Spree::Price.arel_table[:amount].in(low..high))
```
and
https://github.com/wuboy0307/spree/blob/ba51b85f611d3ba39be55928b5c211cdf0d00877/core/app/models/spree/product/scopes.rb#L54
to
```
joins(:master => :default_price).where(Spree::Price.arel_table[:amount].lteq(price))
```
and
https://github.com/wuboy0307/spree/blob/ba51b85f611d3ba39be55928b5c211cdf0d00877/core/app/models/spree/product/scopes.rb#L58
to
```
joins(:master => :default_price).where(Spree::Price.arel_table[:amount].gteq(price))
```

This way changes would be more consistent, and we could remove
https://github.com/wuboy0307/spree/blob/ba51b85f611d3ba39be55928b5c211cdf0d00877/core/app/models/spree/product/scopes.rb#L235

What do you think @damianlegawiec, @jitendra, @priyank-gupta?

Also, changes should be included in specs.

**Comment by Mafi88** [comment]
@wuboy0307 Could you please update specs too?

**Comment by priyank-gupta** [comment]
@wuboy0307 Thanks!!! Are you still available to rebase with latest master and update specs ?

**Comment by bbonislawski** [comment]
I think that this is outdated already. If you think that it's not outdated, please mention me in comment and I'll reopen it

**Pull request closed without merging**
