### PR TITLE
do not submit form if coupon code is invalid at payment step

### PR DESCRIPTION
**Pull request by priyank-gupta**
Fixes issue #6561

### CODE REVIEW

**Comment by Mafi88** [comment]
:+1:

**Comment by damianlegawiec** [comment]
@priyank-gupta 

```
error: (xhr) ->
              ...
              Spree.enableSave(_this_form)
```

you can easily change to just

```
error: (xhr) =>
              ...
              Spree.enableSave($(this))
```

without adding an additional variable

but maybe an easier solution is to just modify `Spree.enableSave` to work similar to `disableSaveOnClick`

```
($ 'form.edit_order').find(':submit, :image').attr('disabled', false).addClass('primary').removeClass 'disabled'`
```

There is always only one edit_form at checkout anyway.

**Comment by priyank-gupta** [comment]
@damianlegawiec Thanks for the feedback. On it.

**Comment by priyank-gupta** [comment]
@damianlegawiec Done.

**Pull request merged**
