### PR TITLE
Replace outdated Spree::Config[:mails_from] with Spree::Store.current.mail_from_address

### LINKED ISSUE #6096: Default from address for Spree::BaseMailer can't be edited in the admin panel
This setting looks outdated: https://github.com/spree/spree/blob/3-0-stable/core/app/mailers/spree/base_mailer.rb#L5
I think, `Spree::Store.current.mail_from_address` should be instead of Spree::Config[:mails_from], b/c it should be editable from the admin panel.

### PR DESCRIPTION
**Pull request by romul**
Fixes #6096 
to edit this setting on /admin/general_settings/edit

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://romul-update-default-mail-setting.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://romul-update-default-mail-setting.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
:+1: thanks

**Comment by JDutil** [comment]
Some frontend specs still need to be updated for the change.

**Comment by romul** [comment]
It can be fixed like this https://github.com/romul/spree/commit/8c55ca3cc15c1adcf6ec3d9b289c67d4f0ad417a
But maybe we should create default store before each spec. It will be more similar to the real situation.

**Comment by JDutil** [comment]
I'm still seeing spec failures for this change.  I'd prefer to only build default store for specs that actually require it so your initial fix should be okay applied where needed.

**Comment by romul** [comment]
@JDutil All specs pass, except one (spec/features/admin/orders/listing_spec.rb:140) unrelated to this PR.

**Pull request closed without merging**
