### PR TITLE
Fix spree/deface#76

### PR DESCRIPTION
**Pull request by drewbug**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://drewbug-patch-1.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://drewbug-patch-1.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
Thanks

**Comment by JDutil** [comment]
Actually this breaks the build must not be up to date on deface perhaps.

**Comment by bbonislawski** [comment]
I think this is not an issue anymore. Closing it for now.

**Pull request closed without merging**
