### PR TITLE
fix: running 'spree install my_store' will hang

### PR DESCRIPTION
**Pull request by orenf**
pretty sure spring has something to do with this

### CODE REVIEW

**Comment by orenf** [comment]
there are a number of issues going on when running
``` spree install my_store```
This one addresses the problem of the `bundle install` command hanging indefinitely.  It doesn't address the issue of an outdated version of Sprockets that's causing `bundle install` to fail.  I'm attaching some screen shots of the failures I'm seeing at the moment.

screen shot 2016-03-02 at 9 05 36 pm

screen shot 2016-03-02 at 9 04 48 pm

**Comment by orenf** [comment]
So to make it hang...

1. create the spree store call it `my_store` as an example (e.g. `spree install my_store`)
2. `cd my_store`, ensure spring is running `spring status`
3. rm my_store
4 create my_store again `spree install my_store`

**Comment by damianlegawiec** [comment]
@orenf we're deprecating the whole installer with Spree 3.1.0 release (https://github.com/spree/spree/pull/7263) so I think we can close it?

**Comment by orenf** [comment]
yeah, absolutely @damianlegawiec!  It's pretty much an edge case anyway.

**Pull request closed without merging**
