### PR TITLE
refactor users controller to set roles, also fix indentation for private...

### PR DESCRIPTION
**Pull request by abhishekjain16**

### CODE REVIEW

**Comment by abhishekjain16** [comment]
@JDutil Did you get any chance to see this?

**Comment by JDutil** [comment]
You might not be changing the code, but you're still refactoring it.  While you're refactoring it is a good time to address these coding style issues such as using ruby 1.9 syntax.  If you could please address the houndci comments that would be great thanks.

**Comment by abhishekjain16** [comment]
@JDutil Sure. No Problem

**Comment by abhishekjain16** [comment]
@JDutil Made the changes with commit 09677023430401327569d7b276a3b1feac9aaa02

**Pull request closed without merging**
