### PR TITLE
adds Spree::Config[:record_order_state_changes] (defaults to current …

### PR DESCRIPTION
**Pull request by jasonfb**
…behavior, true); use to disable creation of records in spree_state_changes

Note: State changes currently have a design flaw in that user_id is not recorded correctly. (It is always the customer's id.). 

Instead of fixing flaw, this prepares for eventual replacement of feature by spinning out all auditing into Spree Extensions. As discussed, the vision is to remove auditing from from core and replace it with two possible extensions: one for acts-as-audited and an alternative for Paper trail, to give developers the choice as to their needs (and tolerance for large audit tables in their DB)

For any users of the state_change table, we have left the preference defaulted to true to preserve existing functionality. I would suggest that we target changing the default here false for this in Spree 4.0, but leave it defaulted to true for at least the rest of the 3.x line. 

TODO:
- [X] add specs
- [ ] refactor for developer-only preferences set on ruby objects Spree::Order.record_state_changes

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://jasonfb-flag-to-disable-recording-order-state-changes.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://jasonfb-flag-to-disable-recording-order-state-changes.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
Could you add a regression spec as well please.

**Comment by jasonfb** [comment]
@JDutil  specs added

**Comment by JDutil** [comment]
I actually really don't like how many preferences we have, and think we should move away from those.  Could you redo this as a module accessor like we do for user class and admin path:
https://github.com/spree/spree/blob/master/core/lib/spree/core.rb#L20-L31

That should also have better performance.

**Comment by jasonfb** [comment]
Sure, but a module accessor on what object? The order object?

And then the customized app would over-ride the module accessor ? Just checking to make sure I'm clear.

**Comment by JDutil** [comment]
I was originally thinking it could be right on the Spree object, but doing on Order object make more sense.  Then in your apps spree.rb initializers you could set `Spree::Order.record_state_changes = false`

**Pull request closed without merging**
