### PR TITLE
Adding expired? method for credit cards

### PR DESCRIPTION
**Pull request by sergiokas**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://sergiokas-master.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://sergiokas-master.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by gmacdougall** [comment]
:-1: This functionality is already provided by ActiveMerchant.

https://github.com/Shopify/active_merchant/blob/v1.47.0/lib/active_merchant/billing/credit_card.rb#L148-L157

```
credit_card.to_active_merchant.expired?
```

**Comment by sergiokas** [comment]
You're right. Thanks!

**Comment by gmacdougall** [comment]
No problem.

**Pull request closed without merging**
