### PR TITLE
Remove OrderPopulator class

### PR DESCRIPTION
**Pull request by jordan-brough**
Help consolidate order update logic by removing an extraneous service object.

Nearly all the logic in OrderPopulator has been moved to OrderContents over time
and there isn't much left that OrderPopulator does except to introduce extra
indirection for the one frontend controller endpoint that uses it.

The "options" hash has also now been added to OrderContents which helps provide
some of the customization that OrderPopulator could theoretically have been used
for.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://jordan-brough-remove-order-populator.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://jordan-brough-remove-order-populator.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
:+1:

**Comment by bcrunsdon** [comment]
Is it really okay to just remove code willy-nilly like this?

**Comment by jordan-brough** [comment]
@bcrunsdon willy-nilly?  :)  Are you objecting to the change?  Or to the lack of discussion around the change?  (This PR is meant to be a catalyst for that discussion)  Or are you perhaps presuming that this would be part of a release that shouldn't introduce big changes like this?  Help me out a bit.

**Comment by cbrunsdon** [comment]
@jordan-brough sorry dude, I was just kidding. I love the change and you personally for your excellent work :(.

**Comment by jordan-brough** [comment]
Hah, my bad missing the joke.  Thanks Clarke. :)

**Comment by JDutil** [comment]
Clarke has removed the most code willy nilly lately anyways ;)  This ones just a bit more significant so added deprecation warning to 2-4-stable.

**Comment by athal7** [comment]
never take anything @bcrunsdon says seriously, he's just trying to instigate

**Comment by JDutil** [comment]
I missed the joke too didn't realize it was Blarke

**Comment by romul** [comment]
@jordan-brough, @JDutil  
That's really odd change for some extensions, like spree_pos.
What is proposed to do if someone need populate order from other controllers?  Copy-paste of 80% populate method? Controller actions should be tiny if it's possible. And such inlining just decrease code quality.

**Comment by JDutil** [comment]
The purpose is to use [OrderContents](https://github.com/spree/spree/blob/master/core/app/models/spree/order_contents.rb) instead.  Some of the code from the populate method like the quantity check should be moved there as well.

**Comment by jordan-brough** [comment]
ditto on what @JDutil said.

@romul Nearly all the logic in OrderPopulator had been moved to OrderContents over time
and there wasn't much left that OrderPopulator was actually doing.

With this update, the controller is doing this:

- Gathering parameters from the request
- Calling `order.contents.add(variant, quantity, options)`
- Redirects/responds as appropriate.

Those feel like appropriate things for the controller to do.  Perhaps the quantity check could be moved into OrderContents but that makes sense as a separate issue imo (and is slightly strange code to begin with :)).

**Comment by romul** [comment]
@JDutil 
> Some of the code from the populate method like the quantity check should be moved there as well.

My point is that this code should not had been moved to `populate` method. 
OrderContents is much more appropriate place than the controller. But this task itself looks pretty useless, there is nothing wrong in a separate class for the processing of raw data and transfer them to another class. And there is much harm in doing that in a controller. 
Spree controllers themselves have too much code, and during refactoring is better extract this code to separate classes, not vice versa. It will simplify testing and controllers' customizations. Based on experience with 50+ Spree extensions I can confidently say that this is the weakest point of Spree. There is nothing worse than controllers' methods overriding by copying dozens lines or trying to introduce tricky callbacks to tamper into the code of some action.

**Comment by JDutil** [comment]
We don't want to bring back OrderPopulator so any improvements to this should be submitted in a PR to improve OrderContents

**Comment by romul** [comment]
Sorry for the harsh tone, but it's sore subject. I'm pretty sure that this commit shows a direction, that directly contrary to a right direction.

**Comment by jordan-brough** [comment]
@romul you've had much more experience with extensions than I have so I don't mind the straight-talk at all personally.   And I don't want to push us in directions that will make extensibility *worse* unnecessarily so I'm all ears to what you have to say.

Could you provide a concrete example of an extension where *this particular* OrderPopulator class would be helpful? I think that would be really helpful for me.

**Comment by JDutil** [comment]
Can this action be done better? Yes.  Do I think we need a new class to accomplish that. No.

I'm not even sure exactly why we need the populate action to begin with rather than just using create/update actions.

What we want to do going forward is single API points to accomplish things like adding/removing items from an order.  There are very specific things in very specific prioritization spree needs to do in order to calculate shipping, taxes, promotions etc.. so we'd like people using a specfiic api point to accomplish what they need to without providing more and more classes to override potentially incorrectly messing with calculations & degrading performance.

**Comment by jordan-brough** [comment]
> I'm not even sure exactly why we need the populate action to begin with rather than just using create/update actions.

@JDutil there isn't a create action on Spree::OrdersController. ;)

**Comment by JDutil** [comment]
@jordan-brough haha I looked that up after my post... I still think we want to remove it anyways, and just use the API controller.

**Pull request closed without merging**
