### PR TITLE
Fixed very long query for taxons on /admin/taxons

### PR DESCRIPTION
**Pull request by Siarhei-Hanchuk**
On /admin/taxons request for taxons very long because of the children

Spree::Taxon.count == 12
Completed 200 OK in 2525ms (Views: 2457.4ms | ActiveRecord: 40.2ms)
vs
Completed 200 OK in 642ms (Views: 580.3ms | ActiveRecord: 26.7ms)

Spree::Taxon.count == 106
Completed 200 OK in 15949ms (Views: 15715.5ms | ActiveRecord: 211.6ms)
vs
Completed 200 OK in 985ms (Views: 865.0ms | ActiveRecord: 89.7ms)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://neschur-taxons-without-children.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://neschur-taxons-without-children.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by Neschur** [comment]
I tested it on 3-0-stable

**Comment by Neschur** [comment]
locally it works on my branch, but on stage get error "private method `content_type' called for #" after "Started GET "/api/v1/taxons?"

**Comment by JDutil** [comment]
https://github.com/spree/spree/pull/6260 should fix your staging error

**Pull request closed without merging**
