### PR TITLE
Payment processing state does not block double submission

### PR DESCRIPTION
**Pull request by shioyama**
We've been experiencing issues where two requests complete an order in rapid succession resulting in two purchase requests being sent to the gateway. This results in a success followed by a failure (double submission) which overwrites the payment state to failed, causing problems down the line.

At first I thought this was something specific to do with the payment gateway or our spree customizations, but this PR confirms that the "processing" state which should prevent this is not working, because it is set within a transaction. AFAICT this would affect any store using Spree. Although here I'm just testing that `ActiveRecord::Base.connection.open_transactions` is zero, I've actually tested parallel requests and confirmed that the "processing" state is not being persisted to the db at any time.

Can someone confirm that this is the case? If so I can try to push up a fix. If I'm misunderstanding something, then some clarification would be great (I'm fairly new to Spree).

Thanks!

### CODE REVIEW

**Comment by tesserakt** [comment]
Just as a follow up, we turned transactions back on in our Spree site and it improved the stability A LOT.

Per the documentation here https://github.com/pluginaweek/state_machine/blob/master/lib/state_machine/integrations/active_record.rb#L286

here is the callback list

  # Callbacks occur in the following order.  Callbacks specific to state_machine
    # are bolded.  The remaining callbacks are part of ActiveRecord.
    # 
    # * (-) save
    # * (-) begin transaction (if enabled)
    # * (1) *before_transition*
    # * (-) valid
    # * (2) before_validation
    # * (-) validate
    # * (3) after_validation
    # * (4) before_save
    # * (5) before_create
    # * (-) create
    # * (6) after_create
    # * (7) after_save
    # * (8) *after_transition*
    # * (-) end transaction (if enabled)
    # * (9) after_commit

**Comment by JDutil** [comment]
@tesserakt could you elaborate on the stability improvement?  Should we turn them back on by default?  I'm pretty sure we've even since removed the regression spec added to this.

**Comment by tesserakt** [comment]
@JDutil We only allow 1 shipment per location in our Spree Store. Without the lock, when the server got slow some customers would double submit on the address page. This created a race condition that sometimes allowed 2 identical shipments to be created for the same location, i.e. duplicates. Adding the transaction back in prevents this.

**Comment by tesserakt** [comment]
@JDutil there were some other weird edge cases we used to see but no longer do after transactions

**Comment by huoxito** [comment]
@tesserakt I think we wanted to disable the transaction only for the payment processing which seems pretty useful to prevent double processing but I dont think it's possible not sure. We'd probably need to decouple the payment processing from state machine callbacks (this alone sounds like a nice change already)

**Comment by JDutil** [comment]
I've seen tons of errors related to the duplicate shipments, and it drove me nuts on 2.2+ stores.  I thought we addressed it by adding the order lock version, which I believe would also have helped resolve double payment processing as well.  I don't recall if we made that lock version change to 2.3 or if it wasn't until 2.4+

I think removing payments from state machine callback would be a good idea too, but not sure how best to accomplish that.

**Comment by tesserakt** [comment]
@huoxito you could write a record outside of the transaction (using a separate thread) that says "Hey I'm processing payments" and then in the transaction check for that.

**Comment by JDutil** [comment]
Well we added it to 2-2-stable+ https://github.com/spree/spree/blob/2-2-stable/core/db/migrate/20141021194502_add_state_lock_version_to_order.rb

**Comment by tesserakt** [comment]
@JDutil we still get double shipments even with that order lock code in 2.3

**Comment by tesserakt** [comment]
@JDutil @huoxito re-enabling transactions on the order requires a little finagling in the finalize method. If you get past processing the payments but then hit a snag, i.e. a random exception gets thrown somewhere in the stack; it is nice to have the finalize code catch the exception, auto void the payment, send the admin an email, then roll back the transaction and notify the user that something went wrong.

**Comment by tesserakt** [comment]
@JDutil can confirm on Spree 2.3 now that transactions are enabled, we are seeing double payment submissions. Going to solve this a different way than removing transactions, however, as our site is much stabler with them.

**Pull request closed without merging**
