### PR TITLE
enable to void invalid payment

### PR DESCRIPTION
**Pull request by odk211**
I face a strange situation.
Administrator can not do anything to invalid state payments.
Administrator want to void it, but can not.

So I simply add the path from "invalid" to "void" transition.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://odk211-enable-to-void-invalid-payment.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://odk211-enable-to-void-invalid-payment.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by odk211** [comment]
If there are some way to deal invalid payment, Could you tell me?
Thanks!

**Comment by JDutil** [comment]
Not sure this necessary.  Why are they trying to void an invalid payment?  The payment shouldn't be invalid unless something had gone wrong with it to begin with.

**Comment by odk211** [comment]
@JDutil Yes, The payment should not be invalid.
But once, invalid payment created, only a `void` link is showed at this payment, and if Administrator click it, it fails.

**Comment by jasonfb** [comment]
seems like invalid is invalid is invalid. Sounds to me like the bug is that the UI shows a "void" button when it shouldn't, not that the state transition isn't supported.

**Comment by JDutil** [comment]
I think so as well @jasonfb

**Comment by odk211** [comment]
@JDutil @jasonfb I got it.
I will fix it if I can.
Thanks!

**Pull request closed without merging**
