### PR TITLE
Reject params[:q][:deleted_at_null] instead of deleting it.

### PR DESCRIPTION
**Pull request by gauravmahajan31**
… its value at view level.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://gauravmahajan31-fix-in-admin-products-controller.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://gauravmahajan31-fix-in-admin-products-controller.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
Could you please fix the hound comments, and the spec failures.

**Comment by gauravmahajan31** [comment]
I have fixed the spec failures as well as hound comments.

**Comment by JDutil** [comment]
Thanks.

**Pull request closed without merging**
