### PR TITLE
Improve Promotions UX

### PR DESCRIPTION
**Pull request by MatthewKennedy**
- Set layout to use full width for all fields in mobile.
- Set Select2 multiple choice fields to have same border radius, and height as other input fields, even when empty.
- Make panels more consistent looking for rules and actions.
- RULE: '_Order total meets these criteria_' now makes more sense on mobile size screens.
- Add date/time picker to promo start from / expires at.

### CODE REVIEW

**Comment by damianlegawiec** [comment]
> The Date picker in promotions was type datetime_field, everywhere else it is type text_field, so I changed it to match the others, what is the best field to use?

This change was made via https://github.com/spree/spree/pull/9450 to enable setting also a time of start/end of promotion as promotions are very time-sensitive :)

**Comment by MatthewKennedy** [comment]
@damianlegawiec Shall I update that date picker to a date/time picker and change the field type back?

**Comment by damianlegawiec** [comment]
@MatthewKennedy that would be awesome, please do! :)

**Comment by MatthewKennedy** [comment]
@damianlegawiec -  I’ll do that today.

**Comment by MatthewKennedy** [comment]
@damianlegawiec I feel that the javascript for the flatpickr.js date and date/time pickers could be written better.

I'll target that in a dedicated PR.

**Review by AleksandraKaminska — APPROVED** [review]

**Review by kaliszKrzysztof — APPROVED** [review]

**Pull request merged**
