### PR TITLE
Fix deprication warning for all on relations

### PR DESCRIPTION
**Pull request by nishant-cyro**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://nishant-cyro-depricated-all.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://nishant-cyro-depricated-all.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by alepore** [comment]
@nishant-cyro thanks, what deprecation message are you referring to?

**Comment by nishant-cyro** [comment]
https://teamtreehouse.com/community/deprecation-warning-relationall-is-deprecated
http://stackoverflow.com/questions/18203712/rails-4-relationall-deprecation

**Comment by alepore** [comment]
After reading some Rails discussions i think the right thing to do here is just a blank `scope`, not a method.

This should work:
```ruby
scope :spree_base_scopes, -> {}
```

**Comment by alepore** [comment]
...but then we can't use `super`... maybe `where(nil)` is the best solution for the anonymous scope

**Pull request closed without merging**
