### PR TITLE
Cdn for production

### PR DESCRIPTION
**Pull request by rdaniels**
Replaced Bootstrap and JQuery gems in /frontend with CDN calls. This loads much faster for optimized production.

```
BENCHMARKS
spree demo site homepage

1005 kb before, now it's 341 kb
62 kb from popular CDNs, so there is also a good chance its already cached in browser
```

### CODE REVIEW

**Comment by tanmay3011** [comment]
Hey @rdaniels, Thanks for the PR.

Regarding the usage of CDN, it has its pros and cons associated with it. 
It does help to load the site faster, but for the development purpose, it won't be available if you're working offline. In case the CDN service hosting the libraries goes down due to some reasons then you'll have to add a fallback to pick those libraries from the local server in order to keep your application running smoothly during the outage period. So using CDN adds an another point of failure to the application. Similarly, there are caching related and few other issues that we need to take care when we are using CDN.

On a single application level, I can understand the usage of the CDN but here in Spree, I would prefer to keep the assets on the local server to maintain a reliable and robust application development.

@damianlegawiec Any thoughts?

**Comment by rdaniels** [comment]
Hey @tanmay3011 , thanks for reviewing the pull request. 
Most websites including my own production sites use CDNs, I've never seen them go down. If you're on a mobile 3g connection, the 800 kb saving for every page is significant. 

You are correct that if you are developing in /frontend you will need Internet connection, but honestly it's very rare that I'm doing development without an Internet connection. 

I think the pros outweigh the cons, especially if you want Spree to perform well in production.

thanks again!

**Comment by mtomov** [comment]
It's a different requirement on production vs development. I certainly want to be able to write code without internet. And to that, here's the rails solution to the problem:

https://github.com/kenn/jquery-rails-cdn

From the readme:

> Automatically fallback to jquery-rails' bundled jQuery when:
You're on a development environment, so that you can work offline.
The CDN is down or unreachable.

**Comment by rdaniels** [comment]
I like the jquery-rails-cdn solution, thanks guys!

**Pull request closed without merging**
