### PR TITLE
validate presence of assocition instead of foreign key

### PR DESCRIPTION
**Pull request by nishant-cyro**
Please refer http://railsguides.net/belongs-to-and-presence-validation-rule1/.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://nishant-cyro-validate-association.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://nishant-cyro-validate-association.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
This breaks the specs.

**Comment by nishant-cyro** [comment]
@JDutil - Please review this PR.

**Comment by JDutil** [comment]
> This branch has conflicts that must be resolved

**Comment by damianlegawiec** [comment]
Hi @nishant-cyro - can you fix merge conflicts and we can accept this? :)

**Comment by nishant-cyro** [comment]
Conflicts resolved.

**Comment by damianlegawiec** [comment]
Thanks @nishant-cyro :)

**Pull request merged**
