### PR TITLE
Add refund_reason spec and return_authorization_reason spec

### PR DESCRIPTION
**Pull request by tanmay3011**
- Add specs for refund_reason and return_authorization_reason

### CODE REVIEW

**Comment by damianlegawiec** [comment]
@tanmay3011  

1. Let's split it into 2 PRs please 
2. Using shoulda-matcher everywhere - I'm not convinced, @Mafi88 what do you think?

**Comment by tanmay3011** [comment]
@damianlegawiec Split this PR into two and respectively updated the description.

**Comment by Mafi88** [comment]
@damianlegawiec I think that we should write validation specs for shoulda-matchers. Indexes and so on - not really.

**Comment by damianlegawiec** [comment]
@Mafi88 :+1: for validations

**Pull request closed without merging**
