### PR TITLE
Item adjustments refactoring

### PR DESCRIPTION
**Pull request by radar**
With my work on [spree_poro](https://github.com/radar/spree_poro), I've been able to figure out several ways that we can make calculations faster within Spree. Attempting to reproduce a small part of the Spree architecture within that project really helped out.

The way forward is to work with more in-memory objects within the tests and stop hitting the database so heavily. There's really no need to do a lot of our DB hits in the tests. Our general abusive nature towards factories is not helping the test speed at all, and so in the process of doing this work I've cut down on a couple of places that used factories and persisted objects. Everything seems to work just the same.

**With this work, I've reduced the number of queries run in core's specs from ~118k, to ~98k. The time for the tests is also 20 seconds faster (2m25s -> 2m5s).**

I've removed the ugly hack in the order state machine which would cause `set_shipments_cost` to be called in some instances when an order was read, mostly when `checkout_steps` was called. This method should be called manually now in the places that we need it, rather than called every single time. I am not sure if this breaks anything that we care about just yet... there's more work to be done on that front. It'd be nice to make sure that orders aren't going from `delivery` to `complete`, completely bypassing the payment step. 

I know there was an issue about that last part, but I can't seem to find it in the over-four-and-a-half-thousand other issues there are on this project.

Here's what's left:
- [ ] Investigate if any more identity caching can be done for line items, shipments and their adjustments
- [x] Core tests passing on SQLite3
- [ ] Core tests passing on PostgreSQL
- [ ] API tests passing
- [ ] Frontend tests passing
- [ ] Backend tests passing
- [x] Ensure shipment cost is set correctly when transitioning from delivery to payment (#2191)
- [x] Ensure order totals are updated when an item is removed

### CODE REVIEW

**Comment by JDutil** [comment]
close:stalled

**Comment by peterberkenbosch** [comment]
close:stalled

**Comment by JDutil** [comment]
close:stalled

**Comment by radar** [comment]
And then you go and close this issue as well!!! Argh. 

The code in this PR (although incomplete, admittedly) did show signs of making Spree faster. I was hoping that someone else would pick up the slack on this PR and get it merged to Spree.

Closing an issue which demonstrably improves spree seems pretty backwards. 

The goal is not to get the issues count to zero. The goal is to make Spree the best ecommerce platform in the world.

**Comment by JDutil** [comment]
We are actively working on the same concepts to accomplish this goal just not from this branch.

**Pull request closed without merging**
