### PR TITLE
Support for Rails 5.2 💥💥💥

### PR DESCRIPTION
**Pull request by bbonislawski**
We're close to finish working on support for Rails 5.2!

Known issues:
-Deleted cache specs since cache was rebuilt in rails 5.2

### CODE REVIEW

**Comment by thomasnal** [comment]
```ruby
rescue PG::ConnectionBad
```
Baked postgres dependency :(

**Comment by bbonislawski** [comment]
@thomasnal great catch. We'll address this issue

**Comment by thomasnal** [comment]
You can solve it this way,
```ruby
    def should_persist?
      @persistence && Spree::Preference.table_exists?
    rescue ActiveRecord::ConnectionNotEstablished, ActiveRecord::NoDatabaseError
      # this is a fix to make Deploy To Heroku button work
      false
    end
```
It save me time to opening a PR against your PR and waiting for merge.  I have done this in my fork.

**Comment by thomasnal** [comment]
With the amendment above, it gives me the actual issue of mine
```ruby
# /bundle/ruby/2.5.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:90:in `connect': Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) (Mysql2::Error::ConnectionError)
```
Just saying it shows a utility.

**Pull request merged**
