### PR TITLE
Minor changes to workaround Globalize bug (backport)

### PR DESCRIPTION
**Pull request by mvz**
Backport of #7831.

### CODE REVIEW

**Comment by damianlegawiec** [comment]
Hey @mvz can you rebase with the current master? It will help with failing specs :)

**Comment by bbonislawski** [comment]
@damianlegawiec target branch is 3-2-stable

**Comment by mvz** [comment]
I included a backport of the fix.

**Comment by mvz** [comment]
Since the fix was applied to 3-2-stable separately, I rebased onto that. Specs are now passing 🎉

**Comment by bbonislawski** [comment]
Thank you @mvz . Merging now 👍

**Pull request merged**
