### PR TITLE
Remove Spree::Alert.

### LINKED ISSUE #6465: CookieOverflow
I don't know how reproduce the issue.

In production airbrake sends me the error `ActionDispatch::Cookies::CookieOverflow: ActionDispatch::Cookies::CookieOverflow` in spree/admin/orders#index

`Gemfile`
https://gist.github.com/artem-russkikh/7f3aea060302f1cea8d8

`Gemfile.lock`
https://gist.github.com/artem-russkikh/bc00bd014afc005fdfdb

Backtrace
https://gist.github.com/artem-russkikh/595924c986d1e13fbd11

Parameters:
```
{
  "action" => "index",
  "controller" => "spree/admin/root"
}
```

Session:
https://gist.github.com/artem-russkikh/ac686d026113cb0fd21b

Here the same error http://stackoverflow.com/questions/9473808/cookie-overflow-in-rails-application
Should i change session_store to active_record_store?

Thank

### PR DESCRIPTION
**Pull request by JDutil**
The initial intent of Spree::Alert was to push notifications from Spree Commerce
to store owners when there were security alerts or new versions released.
This functionality hasn't been used much though in the past several years
with only a couple alerts issued for security updates.  The implementation
was simply sticking the alerts in admin cookies, and has now taken up too much
space causing CookieOverflow errors.  Since this feature isn't really being used,
and most developers rather follow the https://groups.google.com/forum/#!forum/spree-user
mailing list or the Spree Commerce blog & twitter accounts we're just going to
remove it and shut down the alerts.spreecommerce.com service.

Fixes #6465

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://jdutil-remove-alerts.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://jdutil-remove-alerts.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by darbs** [comment]
:+1:

**Comment by alepore** [comment]
:+1:

**Comment by tvdeyen** [comment]
:+1:

**Comment by mamhoff** [comment]
+1

**Comment by joshhepworth** [comment]
Just wanted to say it would have been nice to get one last alert through the service before shutting it down. 

The service being down causes all admin pages to 500 when the system tries to check for a new `Spree::Alert` for versions of Spree deployed that don't have this commit and have the check enabled. It took us a bit to figure out what was going on before disabling the Alert service.

**Comment by davekiss** [comment]
Same here, SO to the rescue.

**Comment by JDutil** [comment]
@joshhepworth @davekiss alerts.spreecommerce.com should be active again we had service outages of several of our applications not just alerts, and removing this was an expedited fix as we no longer push anything out over alerts.

**Comment by eevee** [comment]
This seems to be broken again, and there was never a 2.4.x point release that disables the check.

**Pull request closed without merging**
