### PR TITLE
Remove spree_cmd

### PR DESCRIPTION
**Pull request by wuboy0307**
refer from https://github.com/solidusio/solidus/pull/79

spree_cmd is quite useless since rails generator already take care everything.
In fact spree_cmd still calls rails generator internally.
It only helps you adding spree gem dependencies to Gemfile and run generator for you.

### CODE REVIEW

**Comment by damianlegawiec** [comment]
I'm all for changing the readme and removing the spree "installation" - adding gems and running generators @wuboy0307 

But we don't want to completely remove the spree_cmd - this also has another very important feature - generating boilerplate for extensions developers. 

@priyank-gupta @Mafi88 @jitendra - what do you think guys?

**Comment by wuboy0307** [comment]
@damianlegawiec  you are right. I forget this important feature. However, maybe it could be just a command include in spree_core, I think it's a waste to create a gem just for command line tool only.

**Comment by wuboy0307** [comment]
I add the spree extension command to spree_core
However, I only keep the spree extension command.
spree new command will no longer support.

https://github.com/spree/spree/commit/beec8580c1351f2f426acae3c4f80694cc211296

**Comment by damianlegawiec** [comment]
Looks good @wuboy0307 - we'll review it first thing tomorrow :)

**Comment by wuboy0307** [comment]
Please remember to merge  https://github.com/spree/spree/pull/6933 first.
Otherwise the bin folder won't be included in gem file.

However, I am not quite familiar with spree gem package procedure.
It seems that the bin/spree executable doesn't install in my ruby path.
Please help to check if there's any missing.

**Comment by Mafi88** [comment]
@wuboy0307 @damianlegawiec 
Installation works well, but what about commands like
```
spree -v
```
```
spree extension sth
```

How should they be called now?

**Comment by wuboy0307** [comment]
That's what I talked about, It seems that the spree executable doesn't install in ruby path. I don't know how to do so. Any idea?

**Pull request closed without merging**
