### PR TITLE
Bug Fix on Address Form + Use div for form container elements, not p tags

### PR DESCRIPTION
**Pull request by MatthewKennedy**
There was a bug on the address form, where by, if you had an address saved that did not require a state, then you click edit, and changed to a country that does require a state, the state select element was placed in the dom without the spree flat styling.

Second change is to swap out the p tags for div tags for wrapping form elements.

### CODE REVIEW

**Review by damianlegawiec — APPROVED** [review]

**Comment by MatthewKennedy** [comment]
@damianlegawiec I found other small bugs, and a more robust way to fix this issue while working on the other PR #10227.

**Review by AleksandraKaminska — APPROVED** [review]

**Comment by damianlegawiec** [comment]
@MatthewKennedy we can close this one as https://github.com/spree/spree/pull/10227 was merged, correct?

**Comment by MatthewKennedy** [comment]
Not needed.

**Comment by MatthewKennedy** [comment]
> @MatthewKennedy we can close this one as #10227 was merged, correct?

This is all taken care of in PR #10227 now merged.

**Pull request closed without merging**
