### PR TITLE
Update/clean up payment method display, closes #6421

### LINKED ISSUE #6421: Inconsistent payment methods display behavior
TL;DR I think `PaymentMethod.available` is broken and the respective tests are wrong.

While working on https://github.com/spree/spree/pull/6420 i found an inconsistent behavior on scoping payment methods by `visible_on`:
* objects with `display_on` nil or blank are treated as visibile
* `PaymentMethod.available` and `PaymentMethod.available(:both)` does not return objects with display_on == "front_end" or "back_end"
* `PaymentMethod.available(:frontend)` does not return objects with display_on == "both"
* tests are not well written and allow the above

I can fix this but someone should tell me what the actual expected behavior is.

I would expect:
* `display_on` nil or blank = do not display (or just don't allow this and make default = backend)
* `PaymentMethod.available` should return front_end, back_end, and both
* `PaymentMethod.available(:frontend)` should return objects with display_on == "frontend" and "both"

Thanks!!

### PR DESCRIPTION
**Pull request by alepore**
see discussion on #6421

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://alepore-payment-method-display.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://alepore-payment-method-display.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
@alepore we should add a validation for display_on presence.

**Comment by alepore** [comment]
@JDutil at the moment a blank value is allowed and means "do not display anywhere".
do you think it's useless?
i this case we don't really need this "enum" but just a `display_on_frontend` boolean

**Comment by JDutil** [comment]
Thanks

**Comment by tomash** [comment]
see #6653

**Pull request closed without merging**
