### PR TITLE
Replace select of sku with simple text field in orders filter

### LINKED ISSUE #6225: Browser's freeze in the filter by orders for large stores.
That's really nasty issue in filter orders by SKU. It was introduced by https://github.com/spree/spree/pull/5494
It could lead to a complete freeze of a browser or even to OS freeze (when you click on select), if you have dozens thousands of SKU and orders. And even if you have less SKU's and orders this select have very poor performance.

I think, that we should proceed from the idea that the Spree should be suitable primarily for large stores. Because for small shops there is a bunch of more primitive solutions. So, the such performance downgrades should be fixed for all supported versions as soon as possible. 
In this case, select could be replaced with simple text field without any loss of functionality.

### PR DESCRIPTION
**Pull request by romul**
Replace select of sku with simple text field in orders filter because of big performance issues. 
Fixes #6225

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://romul-fix-6225.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://romul-fix-6225.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by gmacdougall** [comment]
I think this is the correct change (as opposed to the line items having orders one).

This should probably be applied only to master though.

**Comment by JDutil** [comment]
Thanks. I agree with @gmacdougall though and am only applying to master because of how this changes behavior.  Please use your fork to use on older branches.

**Comment by romul** [comment]
@JDutil  Ok, no problem.

When someone run into this issue in released versions, the following quick and dirty fix could be applied:

``` ruby
Deface::Override.new(
  :virtual_path => "spree/admin/orders/index",
  :name => "fix_issue_6225",
  :replace => "erb[loud]:contains('f.select :line_items_variant_id_in')",
  :text => %Q[<%= f.text_field :line_items_variant_sku_eq %>],
  :disabled => false)
```

**Comment by JDutil** [comment]
Nice thanks for workaround.

**Pull request closed without merging**
