### PR TITLE
Use  instead of  to save one count query

### PR DESCRIPTION
**Pull request by vinay-mittal**
Use `present?` instead of `any?` to save one count query if there are more than zero records and `ActiveRecord::Relation` object is not loaded
Earlier two queries were fired -> one count query and one data load query(if count query results greater than 0)
Now only one data load query is fired.

### CODE REVIEW

**Comment by kimquy** [comment]
Probably any improvement need an example to proof that it actually improves. Think that would be more convincing :)

**Comment by damianlegawiec** [comment]
You're saving 1 count query at the cost of query fetching all of the records and time spent on creation of AR objects. :-1:

**Comment by vinayvinsol** [comment]
@damianlegawiec yes i agree that to save one count query, i am fetching all of the records and spending time on creation of AR objects but those records are to be fetched in listing on the same page either way and AR objects are to be created. So why waste a count query for something that is to be done anyway. ?
Am i missing something here ?

**Comment by damianlegawiec** [comment]
@vinayvinsol count query in most cases is quite fast and doesn't bloat memory. So when there aren't any records present it's really fast compared to fetching the list and creating objects in memory.

**Comment by vinayvinsol** [comment]
@damianlegawiec, if there is no data present then data load query will be returning nothing else than null and there are no AR objects created. So in that case there might be a slight difference between data load query and count query but it would be negligible.
And for data existing case, we are saving one count query so comparing to that its negligible. :smile:

**Pull request closed without merging**
