### PR TITLE
Responsive Spree Admin UI

### PR DESCRIPTION
**Pull request by MatthewKennedy**
### Added fully responsive admin UI to Spree.
This pull request makes the Spree admin UI fully responsive with main menu becoming an "off-canvas" slide in menu on small devices.

- Main menu is fully responsive, with nice smooth transition sliding on/off canvas.
- Account nav is moved into a Bootstrap modal for better use on all screen sizes.
- Removed **New Product** button from within an edit product view,  it seems counter intuitive to go into an existing product edit mode to then and have a button to create a new product.
- Removed some now unused helpers that added unnecessary classes to the main menu.
- Added in order currency on the list of order page and on the order summery.
-  Adds the ability to enter country ISO & ISO3 when creating or editing a country. 
- Config file references the colour logo for the admin.
- Spec changed to check inside #main-sidebar not .sidebar 

Please be aware this pull request uses [Body Scroll Lock](https://github.com/willmcpo/body-scroll-lock) I can't see any licensing issues, but double check if this ever gets merged.

### CODE REVIEW

**Comment by luisenrike** [comment]
have you guys seen [tabler](https://preview.tabler.io/)?

I started doing this with tabler but never finished :(

https://github.com/tabler/tabler
https://preview.tabler.io/

**Comment by MatthewKennedy** [comment]
Hi @luisenrike That tabler looks awesome, I tried something like that myself, but I broke so many rails tests and extension in the process by removing some classes and ID's and moving things around, I gave up in the end.

With this attempt I tried to change as little of the existing HTML layout, ID's and classes while using the CSS and JS to add a bit of a new look and most importantly bring as much of the full screen usability into the mobile devises using off canvas menus where needed and letting the CSS do the heave lifting with a simple body class toggle coming from the JS.

There is a lot more polish that could be added, but I figure get a solid usable foundation down and see what people like and dislike from there.

**Comment by luisenrike** [comment]
Yep, I also tried it but it isn't that easy, there is a lot of code to change. Nice work btw.

**Comment by MatthewKennedy** [comment]
see PR #10279

**Comment by zolzaya** [comment]
Oh tablet is awesome. Any news in here?

**Comment by MatthewKennedy** [comment]
@zolzaya The next release of Spree will have the responsive admin.

**Pull request closed without merging**
