### PR TITLE
Replace HABTMs with HMTs

### PR DESCRIPTION
**Pull request by BenMorganIO**
This PR updates Spree so that there is _not one_ spot a `has_and_belongs_to_many` (HABTM) association. Instead, _everything_ has been replaced with `has_many :through`s (HMT).

**What does this mean?**

Well, it means that you now have real AR objects to work with. It means that you will no longer get that `Spree::ShippingMethod::HABTM_Zone` warning message. It means that you will get to actually extend these joins when you need to; like making one paranoid or adding a third association. Finally, it means that Spree is now fully compatible with the [Apartment](https://github.com/influitive/apartment) gem; see influitive/apartment#160 and influitive/apartment#168, influitive/apartment#204, influitive/apartment#136, and influitive/apartment#76 for references to Spree.

(I believe only influitive/apartment#160 is directly related to this PR, but I've referenced the others mainly because they reference Spree. I'm not sure about half of the four other issues, but I'm hoping this PR might help with them.)

Enjoy all you marketplace builders of tomorrow, all you warning message minifiers, and all you spree extension builders :D

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://benmorganio-replace-habtms-with-hmts.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://benmorganio-replace-habtms-with-hmts.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by BenMorganIO** [comment]
The `.table_name=` method was used for its intended purpose while making the HABTM associations: supporting legacy data. I'm going to go forward with making the migrations to remove the usage of the `.table_name=` method and go forward with Rails conventions.

The reason I didn't do this is that I think some people might have actually used those table names to extend Spree. I'm sure its in the <1% so I won't feel bad about renaming the tables. If this is undesired, I'll do a hard reset and remove the commits. Therefore, instead of awaiting feedback on if we want to rename the tables, I'm just going to go ahead and do it anyway; this software is version controlled :D.

Therefore, this comment is simply a breakpoint.

**Comment by darbs** [comment]
:+1:

**Comment by JDutil** [comment]
Thank you.

**Comment by alepore** [comment]
:heart_eyes:

**Comment by mbj** [comment]
Question, why this was merged even CI status shows read?

**Comment by BenMorganIO** [comment]
I think the failure was from a brittle spec. I thought I had fixed all the specs that ended up failing.

**Comment by mbj** [comment]
I wounder if there should be the policy to restart those jobs on CI to prove its not a static failure?

**Comment by mbj** [comment]
I upstreamed several fixes that improved build determinism, fixing races. If we keep merging red builds, situartion will not improve. We should take the "backpressure" in restarting or fixing build determinism.

**Comment by BenMorganIO** [comment]
@mbj I'm going to :+1: you. All new PRs I make, I'll investigate non-related red builds from now on and :-1: merges until that red build is green.

**Comment by mbj** [comment]
@BenMorganIO Cool. Thx.

**Comment by JDutil** [comment]
Will do @mbj @BenMorganIO I had tested this locally fine, but will make sure circle thinks so as well.

**Comment by mbj** [comment]
@JDutil Agreed.

Summary: we need to make sure the circle failures are a real "stop gap". If its a transient failure we need to restart it till it works. Or by a BIG preference: Fix the transient failures.

If we keep merging on red CI: We can just shut it down.

**Pull request merged**
