### PR TITLE
Add validations on name of a tax rate

### PR DESCRIPTION
**Pull request by tanmay3011**
Add uniqueness on name of a tax rate.

### CODE REVIEW

**Comment by priyank-gupta** [comment]
@tanmay3011 Rebase with latest master.

**Comment by tanmay3011** [comment]
@priyank-gupta Done.

**Comment by damianlegawiec** [comment]
@tanmay3011 why `{ case_sensitive: false, allow_blank: true }` - it makes no sense - we're validating presence of name but letting a blank go through?

**Comment by tanmay3011** [comment]
@damianlegawiec Adding allow blank to uniqueness helps me reduce one DB query of uniqueness validation in case of blank input since blank input case is already handled by presence: true we don't need to fire an extra uniqueness query here.

**Comment by priyank-gupta** [comment]
@damianlegawiec `{ case_sensitive: false, allow_blank: true }` seems fine as we have a separate presence validation for the same.

**Comment by damianlegawiec** [comment]
@priyank-gupta it's not fine. It's not declarative. It's hacky.Not acceptable. :-1:

**Comment by priyank-gupta** [comment]
@damianlegawiec Not sure why this seem to be hacky or non declarative as its been already practised by some major gems like [devise](https://github.com/plataformatec/devise/blob/master/lib/devise/models/validatable.rb#L30). Also, used at numerous places in spree itself [zone.rb](https://github.com/spree/spree/blob/master/core/app/models/spree/zone.rb#L15), [option_value.rb](https://github.com/spree/spree/blob/master/core/app/models/spree/option_value.rb#L10), [preference.rb](https://github.com/spree/spree/blob/master/core/app/models/spree/preference.rb#L4) etc.

Let me know if I am missing something or why you consider this unacceptable.

**Comment by damianlegawiec** [comment]
Closing all uniqueness validation PRs in favour of one big PR doing it right (DB level + app level) for 3.2 release.

**Pull request closed without merging**
