### PR TITLE
Fix #7929

### LINKED ISSUE #7929: Missing partials when add a promition stratege.
This happens in the edit view of promotion. When I add a promotion, like 'first order' or 'user logged in' etc.When I click 'add' button, noting happened. Then when I click 'update', it crashes. 

> ActionView::MissingTemplate in Spree::Admin::Promotions#edit
> Showing /usr/local/lib/ruby/gems/2.3.0/gems/spree_backend-3.2.1/app/views/spree/admin/promotions/_promotion_rule.html.erb where line #10 raised:
> 
> Missing partial spree/admin/promotions/rules/_user_logged_in with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder, :rabl], :versions=>[:v1]}. Searched in:
>  "/Users/ronaldoooo/RubymineProjects/mystore/app/views"
>  "/usr/local/lib/ruby/gems/2.3.0/bundler/gems/spree_i18n-07f2b0ff4a09/app/views"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/spree_gateway-3.2.0.beta/lib/views/backend"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/spree_gateway-3.2.0.beta/lib/views/frontend"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/spree_auth_devise-3.2.0.beta/lib/views/backend"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/spree_auth_devise-3.2.0.beta/lib/views/frontend"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/devise-4.0.3/app/views"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/spree_frontend-3.2.1/app/views"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/spree_backend-3.2.1/app/views"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/spree_api-3.2.1/app/views"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/spree_core-3.2.1/app/views"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/kaminari-0.17.0/app/views"

To added with: I use spree 3.2.0, rails 5.0.2

### PR DESCRIPTION
**Pull request by cai-q**
Fix #7929 .

### CODE REVIEW

**Comment by vfonic** [comment]
Hey @ronaldoooo, thanks for contribution!

I'm not sure this is the good way to solve this issue. It's just "hiding" the actual error. I'm don't know how critical that partial is for that page to be displayed. If it's important, it shouldn't fail silently. If we can omit it, better way would be to check if partial exists instead of rescuing from an error. In general it's better to never expect errors, but to use other checks instead.

If you could also provide a test that's not working without your fix and that is passing after your fix is added, that would greatly improve the quality of this code and make sure no one ever wonders why there is `rescue nil` or, even worse, removes it.

**Comment by ronaldoooo** [comment]
@vfonic Thanks for you reply! Actually, I'm new to rails, and I don't really know how to provide a complete unit test for a new feature. I push this PR only because I found this bug(if it is..) in my production environment. (I use 3.2.1-stable, and I found the problem occurs after 3.1.0). I wish if anyone can help me with the issue? Or just help me build an unit test?

**Comment by vfonic** [comment]
Thanks for helping. This is the whole idea of open source: people helping
each other. You can also learn a lot while helping.
I'll find some time in the next couple of days to discover why the bug is
happening. I managed to reproduce it on my local spree installation.

**Comment by ronaldoooo** [comment]
Thanks a lot! I'll wait for a couple of days to see how it goes..

**Comment by vfonic** [comment]
@ronaldoooo I've got the chance to look into this.

If you look at `/spree/backend/app/views/spree/admin/promotions/rules` directory, you'll see that there are several partials there. Those partials are each rendered for one of the rules selected from the dropdown "ADD RULE OF TYPE".
If you select any other option, you'll see that the partial renders either an input field or another dropdown for selecting specific details about the rule. For example, if you select "Product(s)" and click "+ Add", you'll be asked to choose products that apply for this promotion. (Start typing "rails" if you have sample data in your database to see the result.)

Logically, it would make sense to add two more partials: `_user_logged_in.html.erb` and `_first_order.html.erb`. **BUT** if you think again, what extra information you need for this rule to render (look above: either an input field or another dropdown for selecting specific details about the rule), there is no extra information that you need. "First order" is always user's first order and "user logged in" is user that is logged in. So instead of creating a partial, you should skip rendering for those two partials. Something similar to line 5 of the same file: https://github.com/spree/spree/blob/master/backend/app/views/spree/admin/promotions/_promotion_rule.html.erb#L5

To create a test for this, I'd create a feature spec. If you open `/spree/backend/spec/features/`, you'll see that there's `admin/promotions` directory. I'd guess that's where promotion feature specs go. There's even a feature spec for option value rule! That's a great starting point. So I'd definitely write something similar to: `/spree/backend/spec/features/admin/promotions/option_value_rule_spec.rb` in a new file called: `/spree/backend/spec/features/admin/promotions/first_order_rule_spec.rb`
I don't want to go into details of how to write specs. If you need help, I can write those specs and we can close this issue together. If you're not familiar with RSpec and Capybara, you should definitely check them out as those are incredible tools worth time investing for more-less any Rails developer.

**Comment by vfonic** [comment]
Hey @ronaldoooo did you find some time to check my comment?

Do you need any help?

**Comment by dannygreg** [comment]
@vfonic just found this after running into the same issue. Although `rescue nil` may not be the right implementation, I think the approach is correct in spirit. 

The current template appears to assume that all promotion rules need further information provided by the user (hence the need to render a partial), but this isn't the case for some (e.g. the first order rule).

Therefore I think it's acceptable to conditionally not render the partial if one doesn't exist. 

Am I off base? We could really use this fix so I'm happy to open a new PR to solve this if this goes stale 😄

**Comment by ronaldoooo** [comment]
Hey @vfonic ,thank you very much for your suggestion! What you said is right, it's better to explicitly skip these two partials than simply use 'rescue nil'. In the next few days, I'll take my effort to fix it and try to learn things about RSpec and Capybara. Thank you again! 😄

**Comment by dannygreg** [comment]
@vfonic One subtle difference I would propose: we don't just special case those templates, but instead we skip _any_ missing templates. 

This would prevent this problem in future with any other templates added which don't require an additional partial.

**Comment by vfonic** [comment]
@dannygreg ah, so you would only render partial if it exists?

Maybe even better would be to check if selected promotion rule requires additional information.

On this way we'd get an error when promotion rule requires additional information, but the partial is missing (which should be an error).

**Comment by dannygreg** [comment]
> On this way we'd get an error when promotion rule requires additional information, but the partial is missing (which should be an error)

That's a great point. Is there a sensible way we could derive that? It feels like putting a `boolean` flag on the model would be a bit awkward.

**Comment by bbonislawski** [comment]
This issue was fixed in #8200 . If you think that it should be done different way, please let me know and I'll reopen this one. 

Thanks for your contribution!

**Pull request closed without merging**
