### PR TITLE
Fix the destruction cascade of slugs history

### PR DESCRIPTION
**Pull request by ddomingues**
I saw that the add-on of friendly_id was changed from slugged to history to keep the history of slugs, on commit https://github.com/spree/spree/commit/e145a1631788cf7c19e4f1705b8c45a7a181cae6. This add-on creates a relationship [one_to_many](https://github.com/norman/friendly_id/blob/master/lib/friendly_id/history.rb) with a new model [Friendly::Slug](https://github.com/norman/friendly_id/blob/master/lib/friendly_id/slug.rb). However when the product is destroyed the slug history is deleted because it doesn't include **acts_as_paranoid**. So the main idea is lost when the history is deleted.

I tried a lot of alternatives to fix this and as result I did these changes.

Take a look and let me Know what did you think? If you have another idea I could change the PR.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://ddomingues-fixes-cascade-destroy-of-slugs.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://ddomingues-fixes-cascade-destroy-of-slugs.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
Could you add specs please?

**Comment by ddomingues** [comment]
@JDutil, Specs added

**Comment by JDutil** [comment]
Thank you.

**Pull request closed without merging**
