### PR TITLE
Add a check for uniqueness of spree_api_key on user class and add spr…

### PR DESCRIPTION
**Pull request by tanmay3011**
…ee_api_key migration

Add uniqueness to spree_api_token

### CODE REVIEW

**Comment by priyank-gupta** [comment]
@tanmay3011 Rebase with latest master.

**Comment by tanmay3011** [comment]
@priyank-gupta Done.

**Comment by damianlegawiec** [comment]
@tanmay3011 

1. why did you add another migration to add api_key to spree_users? It's already there. 
2. if it's going to be unique why index isn't unique?
3. if we're changing this already why not use https://github.com/robertomiranda/has_secure_token which will be standard in Rails 5?

**Comment by tanmay3011** [comment]
@damianlegawiec 

1. spree_core doesn't have a spree_api_key migration. Well there is a migration in spree_api so just maintaining the consistency added spree_api_key migration to core else LegacyUser won't have a spree_api_key if we only include spree_core.

2. Ahh! uniqueness I missed, will add that. Thanks for pointing it out.

3. Well yes! I wanted to use has_secure_token. Will make another PR using it. Currently just wanted to make the current system consistent and robust.

Any thoughts? Should I just make a PR with has_secure_token and not fix this one. Or fix this one and make an another PR with has_secure_token?

**Comment by damianlegawiec** [comment]
@tanmay3011 I think PR using has_secure_token will do :)

**Comment by tanmay3011** [comment]
@damianlegawiec Cool would do that!

**Comment by tanmay3011** [comment]
#7150 Needs to addressed first

**Pull request closed without merging**
