### PR TITLE
Fix order include duplication

### PR DESCRIPTION
**Pull request by BenMorganIO**
After updating my Gemfile with the following settings:

``` ruby
github 'spree', branch: '3-0-stable' do
  gem 'spree_backend'
  gem 'spree_sample'
end
```

The generate Gemfile.lock references were:

``` yaml
GIT
  remote: git://github.com/spree/spree.git
  revision: 222ae3a9dfa98356d052ff0472a4663d9c5c3f79
  branch: 3-0-stable
  specs:
    spree_api (3.0.3.beta)
      rabl (~> 0.9.4.pre1)
      spree_core (= 3.0.3.beta)
      versioncake (~> 2.3.1)
    spree_backend (3.0.3.beta)
      bootstrap-sass (~> 3.3.1)
      jquery-rails (~> 4.0.3)
      jquery-ui-rails (~> 5.0.0)
      select2-rails (= 3.5.9.1)
      spree_api (= 3.0.3.beta)
      spree_core (= 3.0.3.beta)
      sprockets-rails (~> 2.2)
    spree_core (3.0.3.beta)
      activemerchant (~> 1.47.0)
      acts_as_list (~> 0.6)
      awesome_nested_set (~> 3.0.1)
      cancancan (~> 1.10.1)
      carmen (~> 1.0.0)
      deface (~> 1.0.0)
      ffaker (~> 1.16)
      font-awesome-rails (~> 4.0)
      friendly_id (~> 5.1.0)
      highline (~> 1.6.18)
      httparty (~> 0.11)
      json (~> 1.7)
      kaminari (~> 0.15, >= 0.15.1)
      monetize (~> 1.1)
      paperclip (~> 4.2.0)
      paranoia (~> 2.1.0)
      premailer-rails
      rails (~> 4.2.2)
      ransack (~> 1.4.1)
      responders
      state_machines-activerecord (~> 0.2)
      stringex
      truncate_html (= 0.9.2)
      twitter_cldr (~> 3.0)
    spree_sample (3.0.3.beta)
      spree_core (= 3.0.3.beta)
```

I then booted my rails application with `foreman start`.

``` yaml
# Procfile
web: spring rails server
cache: redis-server config/redis.conf
worker: bundle exec sidekiq -C config/sidekiq.yml
search: elasticsearch --config=/usr/local/opt/elasticsearch/config/elasticsearch.yml
```

The output and the reason for this bug fix is presented here:

``` log
$ fs
21:28:36 web.1    | started with pid 84344
21:28:36 cache.1  | started with pid 84346
21:28:36 worker.1 | started with pid 84348
21:28:36 search.1 | started with pid 84349
21:28:37 search.1 | [2015-07-21 21:28:37,556][INFO ][node                     ] [Sphinx] version[1.5.2], pid[84349], build[62ff986/2015-04-27T09:21:06Z]
21:28:37 search.1 | [2015-07-21 21:28:37,556][INFO ][node                     ] [Sphinx] initializing ...
21:28:37 search.1 | [2015-07-21 21:28:37,562][INFO ][plugins                  ] [Sphinx] loaded [], sites []
21:28:41 search.1 | [2015-07-21 21:28:41,175][INFO ][node                     ] [Sphinx] initialized
21:28:41 search.1 | [2015-07-21 21:28:41,177][INFO ][node                     ] [Sphinx] starting ...
21:28:41 search.1 | [2015-07-21 21:28:41,393][INFO ][transport                ] [Sphinx] bound_address {inet[/127.0.0.1:9300]}, publish_address {inet[/127.0.0.1:9300]}
21:28:41 search.1 | [2015-07-21 21:28:41,428][INFO ][discovery                ] [Sphinx] elasticsearch_brew/DJXdDnCKTVezO1D1ql4tjg
21:28:45 search.1 | [2015-07-21 21:28:45,212][INFO ][cluster.service          ] [Sphinx] new_master [Sphinx][DJXdDnCKTVezO1D1ql4tjg][BENJAMINs-MacBook-Pro.local][inet[/127.0.0.1:9300]], reason: zen-disco-join (elected_as_master)
21:28:45 search.1 | [2015-07-21 21:28:45,233][INFO ][http                     ] [Sphinx] bound_address {inet[/127.0.0.1:9200]}, publish_address {inet[/127.0.0.1:9200]}
21:28:45 search.1 | [2015-07-21 21:28:45,233][INFO ][node                     ] [Sphinx] started
21:28:46 search.1 | [2015-07-21 21:28:46,014][INFO ][gateway                  ] [Sphinx] recovered [1] indices into cluster_state
21:28:47 web.1    | => Booting Puma
21:28:47 web.1    | => Rails 4.2.3 application starting in development on http://0.0.0.0:3000
21:28:47 web.1    | => Run `rails server -h` for more startup options
21:28:47 web.1    | => Ctrl-C to shutdown server
21:28:51 web.1    | Puma 2.11.2 starting...
21:28:51 web.1    | * Min threads: 0, max threads: 16
21:28:51 web.1    | * Environment: development
21:28:51 web.1    | * Listening on tcp://0.0.0.0:3000
21:28:51 worker.1 | Cannot define multiple 'included' blocks for a Concern
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/concern.rb:126:in `included'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/bundler/gems/spree-222ae3a9dfa9/core/app/models/spree/order/checkout.rb:6:in `<module:Checkout>'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/bundler/gems/spree-222ae3a9dfa9/core/app/models/spree/order/checkout.rb:3:in `<class:Order>'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/bundler/gems/spree-222ae3a9dfa9/core/app/models/spree/order/checkout.rb:2:in `<module:Spree>'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/bundler/gems/spree-222ae3a9dfa9/core/app/models/spree/order/checkout.rb:1:in `<top (required)>'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:457:in `load'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:457:in `block in load_file'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:647:in `new_constants_in'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:456:in `load_file'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:354:in `require_or_load'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:317:in `depend_on'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:233:in `require_dependency'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:471:in `each'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:471:in `block in eager_load!'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:469:in `each'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:469:in `eager_load!'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:346:in `eager_load!'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/application/finisher.rb:56:in `each'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
21:28:51 worker.1 | /Users/BenAMorgan/Sites/private/WholeNewHome/config/environment.rb:5:in `<top (required)>'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.3.4/lib/sidekiq/cli.rb:241:in `boot_system'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.3.4/lib/sidekiq/cli.rb:50:in `run'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.3.4/bin/sidekiq:8:in `<top (required)>'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/bin/sidekiq:23:in `load'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/bin/sidekiq:23:in `<main>'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
21:28:51 worker.1 | /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
21:28:51 worker.1 | exited with code 1
21:28:51 system   | sending SIGTERM to all processes
21:28:51 web.1    | Exiting
21:28:51 search.1 | [2015-07-21 21:28:51,765][INFO ][node                     ] [Sphinx] stopping ...
21:28:51 search.1 | [2015-07-21 21:28:51,815][INFO ][node                     ] [Sphinx] stopped
21:28:51 search.1 | [2015-07-21 21:28:51,815][INFO ][node                     ] [Sphinx] closing ...
21:28:51 search.1 | [2015-07-21 21:28:51,821][INFO ][node                     ] [Sphinx] closed
21:28:51 cache.1  | exited with code 0
21:28:51 search.1 | exited with code 143
21:28:52 web.1    | terminated by SIGTERM
```

On investigation, I discovered that @darbs has updated the `Spree::Order::Checkout` module as an `ActiveSupport::Concern` in 11cd50c0f5936af23130b0394c0cd7964e48fdb3. As lovely as this is, this generated a regression inside of Spree. It caused the `Cannot define multiple 'included' blocks for a Concern` error; no class given by Rails, may be nice to give them a PR on this issue with a better error message.

I'm not too sure why this has occurred. My initial thought was that it was because `ActiveRecord::Base` was using  the `#included` method. After looking inside of [`ActiveRecord::Base`](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/base.rb) I wasn't able to see any instances where it was used, even in its dependencies.

Maybe we can change the modules out into concerns when Spree hits 4.0.

Anywho, my first attempt was to remove the `Spree::Base` in be1bc24, that way `ActiveSupport::Concern` doesn't think its working with a table. (It was an idea.) The error that I got from that was:

```
superclass mismatch for class Order
```

Then I realized: Just revert to the legacy since extending from `ActiveSupport::Concern` has generated a regression. After cff2e04 the rails application that I was working on didn't crash on server boot.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://benmorganio-fix-order-include-duplication.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://benmorganio-fix-order-include-duplication.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
This breaks the specs

**Comment by darbs** [comment]
@BenMorganIO my apologies, if i recall correctly i only refactored it into a concern to please hound.

**Comment by BenMorganIO** [comment]
@jdutil it was my shortening of the lines. Let me do a hard reset and remove 228fc0c.

**Comment by BenMorganIO** [comment]
Updated.

**Comment by JDutil** [comment]
Thank you.

**Comment by stephenhmarsh** [comment]
+1 This.  Thanks @BenMorganIO. This also should fix https://github.com/spree/spree/issues/6543

**Pull request closed without merging**
