### PR TITLE
Human Friendly Date Formatting

### PR DESCRIPTION
**Pull request by MatthewKennedy**
Setup FlatPicker to use a standard rails format in the background, but show a human friendly version to the user, allowing users to customise their date format without effecting how the date is saved to the database.

This error was apparent when setting the date plus a time when using the promotions in DE or any language that the date formatting way not typical YYY-MM-DD HH:MM

### CODE REVIEW

**Comment by MatthewKennedy** [comment]
ToDo: Write test in Promotions that tests the date_time input and save formatting.

**Review by AleksandraKaminska — APPROVED** [review]
Works well. Good job 👍

**Comment by MatthewKennedy** [comment]
Hi @AleksandraKaminska 

Just writing some tests for new_promotion_spec.rb, checks the date and time save correctly, amongst other things.

**Comment by damianlegawiec** [comment]
> Hi @AleksandraKaminska
> 
> Just writing some tests for new_promotion_spec.rb, checks the date and time save correctly, amongst other things.

more tests = ❤️

**Comment by MatthewKennedy** [comment]
@damianlegawiec What would be the default human friendly date format? Anything you are for or against?

I've just set it to show **abbreviated month day, year** for standard date:
and **abbreviated month day, year at HH:MM** for date with time:

Date Only
Screenshot 2021-02-05 at 12 54 57

Date and Time
Screenshot 2021-02-05 at 13 03 53

**Comment by damianlegawiec** [comment]
> @damianlegawiec What would be the preferred default human friendly date format? Anything you are for or against?
> 
> I've just set it to show **abbreviated month day, year** for standard date:
> and **abbreviated month day, year at HH:MM** for date with time:
> 
> Date Only
> Screenshot 2021-02-05 at 12 54 57
> 
> Date and Time
> Screenshot 2021-02-05 at 13 03 53

Looks great!

**Review by damianlegawiec — APPROVED** [review]

**Pull request merged**
