### PR TITLE
Enable to override exchanging percentage for gateway

### PR DESCRIPTION
**Pull request by camelmasa**
Spree will changes some prices from dollar to cent when requests to gateway.

e.g. https://github.com/spree/spree/blob/master/core/app/models/spree/payment/gateway_options.rb#L29

``` rb
      ...
      def shipping
        order.ship_total * 100
      end
      ...
```

Some gateways doesn't support cent currency.

I think we need to change `Spree::Payment::GatewayOptions`.
Please check a commit.

And, Please advise nice naming if `exchage_percentage` is not readable. :wink:

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://camelmasa-exchange-percentage-for-gateway.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://camelmasa-exchange-percentage-for-gateway.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
Maybe exchange_rate or exchange_multiplier makes more sense.  Or maybe gateway_multiplier. I think it's more a multiplier than percentage as that would be what you divide by.

**Comment by camelmasa** [comment]
@JDutil Thank you for a comment :wink:  I renamed the method.

Please review if you have time :watch:

**Comment by JDutil** [comment]
Thanks

**Pull request closed without merging**
