### PR TITLE
Disable SSL for Teatro to allow access `/admin`.

### PR DESCRIPTION
**Pull request by divineforest**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://divineforest-fix-teatro-admin.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by gmacdougall** [comment]
This is related to #5827. If we decide to merge that, then this isn't necessary. Actually, I'm not sure why this is even needed in the first place...

**Comment by divineforest** [comment]
@gmacdougall yes #5827 will fix this

**Comment by divineforest** [comment]
@gmacdougall it can be changed. But if you use `production` env you are closer to real production environment.

**Comment by divineforest** [comment]
@gmacdougall it is also possible to use `staging` env

**Comment by gmacdougall** [comment]
It's more a [principle of least astonishment](http://en.wikipedia.org/wiki/Principle_of_least_astonishment) issue. If I were to ask the following question to a member of my team:

By default, Rails creates three environments for every application `development`, `test`, and `production`. Which environment do you think the CI would run when it runs your tests?

I don't think anyone is going to answer production.

**Comment by divineforest** [comment]
@gmacdougall but Teatro does not run tests. It runs a staging server which behaves like a production server.

**Comment by gmacdougall** [comment]
Ah, okay. I apologize for being deeply confused.

**Comment by divineforest** [comment]
@gmacdougall  :)

**Pull request closed without merging**
