### PR TITLE
Add validations to stock items and stock movements

### PR DESCRIPTION
**Pull request by mbj**
Adds more tight validation to prevent invalid data entering the system.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://mountainroseherbs-fix-add-validation-to-stock-movements.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://mountainroseherbs-fix-add-validation-to-stock-movements.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by mbj** [comment]
@JDutil As you before had to refuse style fixes. Are the ones flagged by hound relevant? (I'll fix them in case).

Otherwise this is ready for review.

**Comment by JDutil** [comment]
Yea we'd like to address hound comments as they only occur on lines being changed. It's going back through and just updating code style without actually changing what the code is doing that we prefer to avoid.

**Comment by mbj** [comment]
@JDutil The style issues where addressed, assuming green build this is ready for the next pass.

**Comment by mbj** [comment]
@JDutil Changes you can backport this one to 2-4 and 2-3-stable? Should apply clean AFAIK.

**Comment by JDutil** [comment]
done

**Comment by mbj** [comment]
thx

**Pull request closed without merging**
