### PR TITLE
Adds a spree theme for jstree.

### PR DESCRIPTION
**Pull request by tvdeyen**
The default "apple" theme for the jstree plugin that powers the taxonomies tree adminstration does not really fit the spree backend theme.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://magiclabs-jstree-theme.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://magiclabs-jstree-theme.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
This isn't merging cleanly for some reason.  Might need to rebase this.  Also curious if you could post before/after screenshots since I'm not able to apply this patch and see them in the sandbox.

**Comment by tvdeyen** [comment]
I used the teatro stage. It works well btw. But I will provide screens tomorrow (CEST).
Also encountered a strange behavior on the teatro stage this maybe is related with spree_i18n. Icons where missing in the contextual menu. 
Will check that.

**Comment by JDutil** [comment]
Does look nicer on teatro

**Comment by JDutil** [comment]
Unable to merge thought the patch fails to apply:
```
› git am -3 https://github.com/spree/spree/pull/6378
Applying: Adds a spree theme for jstree.
Using index info to reconstruct a base tree...
error: patch failed: backend/vendor/assets/javascripts/jquery.jstree/themes/apple/style.scss:1
error: backend/vendor/assets/javascripts/jquery.jstree/themes/apple/style.scss: patch does not apply
Did you hand edit your patch?
It does not apply to blobs recorded in its index.
Cannot fall back to three-way merge.
Patch failed at 0001 Adds a spree theme for jstree.
The copy of the patch that failed is found in:
   /Users/JDutil/Code/spree/.git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

**Comment by tvdeyen** [comment]
@JDutil I rebased with latest master and added two new commits, that:

1. Adds icons to the context menu. Spree 2.x had icons and `spree_i18n` still adds these old icons to the context menu. I will send a pull request to update the overwritten view in spree_i18n
2. Fixes the double click to rename feature.

You should be able merge this into master.

## Here are some screenshots

jstree-before
_(before)_

jstree-after
_(after)_

**Comment by JDutil** [comment]
Thanks.

**Comment by tvdeyen** [comment]
Thank you!

**Pull request merged**
