### PR TITLE
Add rubocop-rspec, run rubocop autocorrection in api/spec

### PR DESCRIPTION
**Pull request by artplan1**
Reference: https://github.com/backus/rubocop-rspec

Not sure if it's good thing to include this in such huge project, but I'm ready to run autocorrect and tests in core gems

I ran only in `api` for now, to show what will be changed/fixed

Rubocop output is almost green with this cops disabled:

<details>
<summary>Disabled cops list</summary>

```ruby
RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
```
</details>

### CODE REVIEW

**Comment by bbonislawski** [comment]
It's good idea imo. I did something like this in #8291 . I've separated cops for separate commits to keep  history as good as possible. If you could do something like this with this one, I'd be really grateful

**Comment by artplan1** [comment]
@bbonislawski 
yes, that's exactly what I wanted to do. One gem - one commit.

One thing I need you guys to help me - define list of disabled cops and metrics. In PR I posted list with disabled cops which allows almost green build.

Maybe it will be good thing to do - disable those cops in config, run autofix in gems and add task somewhere like `enable disabled cop and fix issues`?

**Comment by bbonislawski** [comment]
Yeah. Defining issue like that could be pretty useful. I'm OK with disabling these cops and adding them to config.

**Comment by bbonislawski** [comment]
Thanks @artplan1 . Last 1 thing. Can you rebase against current master to resolve conflicts? I want to merge it then

**Comment by artplan1** [comment]
@bbonislawski 
`core` gem left here, I want to fix it too before merge

will do rebase anyway, thanks

**Comment by artplan1** [comment]
@bbonislawski 
all done

I need your assistance on lines:

https://github.com/spree/spree/blob/7cc2d8005afbfd4e130a88c37ab8b6d38a49eef8/core/spec/models/spree/order/state_machine_spec.rb#L141
https://github.com/spree/spree/blob/7cc2d8005afbfd4e130a88c37ab8b6d38a49eef8/core/spec/models/spree/order/state_machine_spec.rb#L204

These specs contains no expectations, maybe can be deleted?

**Comment by bbonislawski** [comment]
@artplan1 specs are far from perfect. If you see obvious things like that, just remove them ;)

**Comment by bbonislawski** [comment]
and ignore warnings about duplication

**Comment by artplan1** [comment]
@bbonislawski yep, ready

**Comment by bbonislawski** [comment]
tenor-2

**Pull request merged**
