### PR TITLE
Updates pre_tax_total for items without tax rates

### PR DESCRIPTION
**Pull request by tommiller1**

### CODE REVIEW

**Comment by damianlegawiec** [comment]
Hi @tommiller1  - there are some specs failing https://circleci.com/gh/spree/spree/4674

**Comment by damianlegawiec** [comment]
@tommiller1  can you describe more this PR? What issues it resolves? Thanks!

**Comment by tommiller1** [comment]
The pre_tax_total is supposed to contain the total item price (price * quantity) minus any taxes, but its not getting updated for products that have no taxes (it is 0 for such items). 

This is because tax_rate.rb:70 makes a call to store_pre_tax_amount for lineitems that have a tax_category, but not for items without a tax_category. We added a couple lines at the end of the function which ensure that store_pre_tax_amount is also called for items without any tax categories.

The only visible impact we found of this bug was that when you go to the reimbursement page, the default refund amount shows up as 0 which is annoying.

**Comment by damianlegawiec** [comment]
Thanks @tommiller1  for explaining - could you also fix specs? They need updating for the new behaviour.

**Comment by tommiller1** [comment]
Specs have already been updated, tests are passing in ci.

**Comment by damianlegawiec** [comment]
@tommiller1 sorry, missed that one!

**Pull request merged**
