### PR TITLE
Improved UI when cancelling 'edit a line item'

### PR DESCRIPTION
**Pull request by reinaris**
The cancel button had exact the same layout as the delete button..

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://reinaris-patch-2.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://reinaris-patch-2.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
Merged w/ 2e6f6f2dbc0fec9061f70962b1023452bdcd2120

**Comment by psingha2** [comment]
i can't run migrations on spree, it says spree_payment_methods not found
and all later migrations canceled.Please help as this is the only step
stopping me from running my server
Parth Singhal

**Comment by reinaris** [comment]
@psingha2 does that have anything todo with this issue?
Please read the contributing guidelines before filing in issue: https://guides.spreecommerce.com/developer/contributing.html#filing-an-issue

**Pull request closed without merging**
