### PR TITLE
Fix method name and add i18n to shipping_method validator

### PR DESCRIPTION
**Pull request by aishmita-aggarwal**

### CODE REVIEW

**Comment by priyank-gupta** [comment]
@aishmita-aggarwal Rebase with latest master.

**Comment by aishmita-aggarwal** [comment]
@priyank-gupta Done with the changes. Please check. :)

**Comment by damianlegawiec** [comment]
@aishmita-aggarwal `at least` is the correct form, not `atleast` https://www.quora.com/What-is-the-difference-between-atleast-and-at-least . Please change it and we can merge it.

**Comment by aishmita-aggarwal** [comment]
@damianlegawiec Thank you for the correction. Done with the changes, please check! :)

**Pull request merged**
