### PR TITLE
[SD-870] Change default orders count to 15

### PR DESCRIPTION
**Pull request by kaliszKrzysztof**

### CODE REVIEW

**Review by AleksandraKaminska — APPROVED** [review]

**Comment by damianlegawiec** [comment]
@kaliszKrzysztof why do we need to limit it to 15? 25 is just fine :)

**Comment by kaliszKrzysztof** [comment]
@damianlegawiec because of this issue https://spark-solutions.atlassian.net/browse/SD-870, we can stick with 25 items if you think so

**Comment by damianlegawiec** [comment]
> @damianlegawiec because of this issue https://spark-solutions.atlassian.net/browse/SD-870, we can stick with 25 items if you think so

We want to have 25 there, 15 is too little

**Comment by kaliszKrzysztof** [comment]
> > @damianlegawiec because of this issue https://spark-solutions.atlassian.net/browse/SD-870, we can stick with 25 items if you think so
> 
> We want to have 25 there, 15 is too little

Sure, do we want any additional changes then? For example additional value `25` in `per page select` element or maybe change `15` value into `25`?

**Comment by damianlegawiec** [comment]
> > > @damianlegawiec because of this issue https://spark-solutions.atlassian.net/browse/SD-870, we can stick with 25 items if you think so
> > 
> > 
> > We want to have 25 there, 15 is too little
> 
> Sure, do we want any additional changes then? For example additional value `25` in `per page select` element or maybe change `15` value into `25`?
> Screenshot 2020-07-06 at 10 13 18

Let's change it to 25/50/75 in per page dropdown please

**Review by damianlegawiec — APPROVED** [review]

**Pull request merged**
