### PR TITLE
Modify spree.js.coffee.erb and backend.js to use Spree.admin_path in js too.

### PR DESCRIPTION
**Pull request by nishant-cyro**
Fixes https://github.com/spree/spree/issues/6865

### CODE REVIEW

**Comment by damianlegawiec** [comment]
:+1:

**Comment by nishant-cyro** [comment]
@damianlegawiec - Fixed :)

**Comment by damianlegawiec** [comment]
@nishant-cyro format for the preference should be `/admin` - let's add the trailing slash in code, not force the user/developer to do it

**Comment by nishant-cyro** [comment]
@damianlegawiec - cool, I will look into it.

**Comment by nishant-cyro** [comment]
@damianlegawiec - Done with the changes, you suggested :)

**Comment by damianlegawiec** [comment]
@nishant-cyro any updates? This is a welcome change when done right :)

**Comment by nishant-cyro** [comment]
@damianlegawiec - Done, please let me know if there is still any issue in it.

**Comment by damianlegawiec** [comment]
@nishant-cyro there is (maybe) one edge case more (don't hate me! :)  - when someone adds this with a trailing dash like `/admin/` it will result with `admin//` - can you check this also?

**Comment by nishant-cyro** [comment]
@damianlegawiec - thanks :+1:

**Comment by damianlegawiec** [comment]
@nishant-cyro thank you :)

**Pull request merged**
