### PR TITLE
Avoid destroying state and countries if associated addresses present,…

### PR DESCRIPTION
**Pull request by tanmay3011**
… use dependent restrict_with_error option

### CODE REVIEW

**Comment by priyank-gupta** [comment]
@tanmay3011 If we choose to go with this approach then I think we should also remove code where default country is been assigned to address.

**Comment by tanmay3011** [comment]
@priyank-gupta Those specs are for a specific feature of destroying a country and what happens after we destroy a country. Since I'm restricting admin from destroying a country if associated that feature spec becomes useless.

**Comment by priyank-gupta** [comment]
:+1:

**Comment by Mafi88** [comment]
@tanmay3011 Please rebase with latest master

**Comment by tanmay3011** [comment]
@Mafi88 Done

**Pull request merged**
