### PR TITLE
Add validation for analytics tracker

### PR DESCRIPTION
**Pull request by dilpreet92**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://dilpreet92-fix-tracker.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://dilpreet92-fix-tracker.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by priyank-gupta** [comment]
:+1: 

@damianlegawiec @Mafi88 ?
@dilpreet92 There are some failing specs around this change. Please fix.

**Comment by dilpreet92** [comment]
@priyank-gupta Fixed specs for the analytics tracker

**Comment by Mafi88** [comment]
:+1:

**Comment by priyank-gupta** [comment]
:+1:

**Pull request merged**
