### PR TITLE
Replace rails #current method with ruby #now since #current is not ac…

### PR DESCRIPTION
**Pull request by tanmay3011**
…cessible in template

### CODE REVIEW

**Comment by nishant-cyro** [comment]
:+1:

**Comment by Mafi88** [comment]
According to this commit: https://github.com/spree/spree/commit/ab5d64dec0e5240b71e85da42171429d9e10e49f I think it should be ```Time.zone.now```.

**Comment by tanmay3011** [comment]
@Mafi88   zone is also not defined in ruby on Time Class so Time.zone.now won't work in this case.

**Comment by Mafi88** [comment]
@tanmay3011 Indeed! :+1:

**Pull request merged**
