### PR TITLE
[Documentation] REST API custom endpoints

### PR DESCRIPTION
**Pull request by mfdeveloper**
I've search by how to add new endpoints to Spree **REST API** and I coundn't find them. I had that see the spree source code to see like do this, and created this new documentation page for me and others that search for this (e.g do e-commerce platforms benchmarks).

One question: Why Spree don't uses [rails-api](https://github.com/rails-api/rails-api) that was merged into Rails core? Some legacy reason?

### CODE REVIEW

**Comment by bbonislawski** [comment]
Hello @mfdeveloper , thanks for your contribution. We'll look through it soon and get back to you.


To answer your question, Spree API was created looong before rails-api was a thing. We're working on Spree API V2 with rails-api, JSON API format, OAuth and many good things.

**Comment by mfdeveloper** [comment]
Great @bbonislawski !! Thank you for your response!

I'm so glad for the next Spree API V2. Seems be a very interesting for me! I commented in the issue #8339 about use of SPA Component based JS frameworks, and can be connected with this next features mentioned by you!

Thank your so much for your hard work, guys!!

**Comment by bbonislawski** [comment]
@mfdeveloper it's really good and it can be a little bit better.
It would be nice to  add information about authorization and securing access to resources (but it's not required at the moment. we can do it later) and there are few things that can be "more english":

- "We will do this on the extension `spree_simple_sales` created in Extensions tutorial" -> "We will use `spree_simple_sales` extension created in Extensions tutorial for it"
- "If you don't see before" -> "If you haven't seen before"
- "with a action" -> "with an action"
- "So, create a new file in the directory we just created called sales_controller.rb and add the following content to it"
-> "In the directory we just created add a new file called `sales_controller.rb` with the the following content:"
- "all products with sale price" -> "all products with a sale price"


Thank you for your hard work and waiting for these fixes.

**Comment by bbonislawski** [comment]
@mfdeveloper there are 2 ways to pass api token.
1. As param `token` 
2. As header 'X-Spree-Token'. You can use `request.headers['X-Spree-Token'] = 'YourToken'` in spec before calling `get` method

**Comment by mfdeveloper** [comment]
@bbonislawski Thank you for your help. But, the methods mentioned by you works only request the endpoint by url directly (browser, postman...), not into a spec test. So, I've used the `stub_authentication!` method into the spec file, like this:

```ruby
...

before do
     stub_authentication!
end
```

And it works!! I've updated the documentation with the steps to create a spec integration test, and verify the returned json!

Can you accept this by now? :smiley:

**Comment by bbonislawski** [comment]
Yeah, thanks @mfdeveloper !

**Pull request merged**
