### PR TITLE
Update Kaminari in Spree 3.1

### PR DESCRIPTION
**Pull request by kimadactyl**
This is creating a dependency clash with ActiveAdmin.

### CODE REVIEW

**Comment by krzysiek1507** [comment]
I'm not sure if we should enforce `~> 1.0.1` for 3.1. We should try to allow `~> 0.17` as well.

**Comment by kimadactyl** [comment]
I'm new to this kinda thing, what's the reasoning behind keeping it back? As long as it allows 1.x I'm happy though :)

**Comment by krzysiek1507** [comment]
We shouldn't enforce developers to upgrade their applications to a new major version of gem in a patch release. I'm pretty sure that you wouldn't be happy if you had to upgrade Rails to 5.0 from 4.2 because of patch release. ;)

**Comment by krzysiek1507** [comment]
We'll check if `~> 0.17` and `~> 1.0.1` are compatible.

**Comment by kimadactyl** [comment]
Oh right, that makes total sense :+1: :smile: 

And thanks!

**Comment by krzysiek1507** [comment]
You are welcome! We'll back to this PR as soon as possible!

**Comment by damianlegawiec** [comment]
Done via https://github.com/spree/spree/pull/8304

**Pull request closed without merging**
