### PR TITLE
Add allow_blank to uniqueness validation of option type name

### PR DESCRIPTION
**Pull request by tanmay3011**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://tanmay3011-use-allow-blank.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://tanmay3011-use-allow-blank.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
Why allow blank if presence is required?  To prevent both messages from showing at once?

**Comment by tanmay3011** [comment]
Well uniqueness validation fires a query. Incase the attribute is blank presence validation will always give a error and we can avoid unnecessary query for uniqueness. If attribute is present then only we shoul check uniqueness.

So this is a kind of optimisation by which we can save a query.

**Comment by JDutil** [comment]
Thanks

**Pull request merged**
