### PR TITLE
add Reimbursement mailer lacking html view #7744

### PR DESCRIPTION
**Pull request by mohsen-alizadeh**
For Reimbursement mailer, a HTML view added

#7744

### CODE REVIEW

**Comment by mohsen-alizadeh** [comment]
reimbursement_email_html

**Comment by mohsen-alizadeh** [comment]
@damianlegawiec please merge this one too.

**Comment by damianlegawiec** [comment]
Hi @mohsen-alizadeh please fix failing spec -> https://circleci.com/gh/spree/spree/5446?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mohsen-alizadeh** [comment]
@damianlegawiec thank you for your comment.
I changed the spec test to cover both templates.
Please merge

**Comment by damianlegawiec** [comment]
Thank you @mohsen-alizadeh 👍

**Pull request merged**
