### PR TITLE
Moved all namespaced controllers to corresponding v1 folder

### PR DESCRIPTION
**Pull request by detierno**
I just updated the spree and notice a Rails load error.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://detierno-master.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://detierno-master.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by BenMorganIO** [comment]
There were quite a few commits that didn't reach master.

**Comment by BenMorganIO** [comment]
This should have been merged in.

**Comment by JDutil** [comment]
@BenMorganIO should I merge this?  It looks like your PR that you started does this as well, but isn't rebase with master to include the security changes.

**Comment by BenMorganIO** [comment]
@JDutil It looks like the commit I cherry picked ignored the security updates. Merge @detierno's work and I'll merge his work into mine to get the smaller work back to par.

**Pull request closed without merging**
