### PR TITLE
Modified database.yml template for generating dummy test app

### PR DESCRIPTION
**Pull request by vishalzambre**
add provision to set db username and password while running `bash build.sh` on local

### CODE REVIEW

**Comment by Mafi88** [comment]
@vishalzambre Could you please explain why setting username and password for dummy db is important?

**Comment by zambrevishal** [comment]
@Mafi88 No one is using database without username and password. to run spree specs on local it creates dummy database.yml and that time its giving error. If user have configuration to set username and password it avoid to hard code in template. otherwise user has to hardcode in spree database.yml template then only he can able to run specs.

Also I have provided default value to it, If user don'e want to provide then also will work.

**Comment by vishalzambre** [comment]
@Mafi88 No one is using database without username and password. to run spree specs on local it creates dummy database.yml and that time its giving error. If user have configuration to set username and password it avoid to hard code in template. otherwise user has to hardcode in spree database.yml template then only he can able to run specs.

Also I have provided default value to it, If user don'e want to provide then also will work.

**Comment by Mafi88** [comment]
It works properly.

@priyank-gupta what do you think?

**Comment by vishalzambre** [comment]
@Mafi88 It works properly, but nice to have config to provide username and password if required.

**Comment by priyank-gupta** [comment]
:+1:

**Comment by Mafi88** [comment]
@vishalzambre I meant that everything works properly with this PR :)

**Pull request merged**
