### PR TITLE
compatible friend_id with i18n

### PR DESCRIPTION
**Pull request by arthurtalkgoal**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://arthurtalkgoal-3-0-stable.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://arthurtalkgoal-3-0-stable.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by arthurtalkgoal** [comment]
Hi @TeatrolO,

Sorry to ask you a simple question. It's my second time to see the "Open Stage" comments in my pull request. What it means? and what's the difference between normal pull request?

**Comment by pusewicz** [comment]
@arthurtalkgoal It means that there is a staging environment for this pull request, where you can test your changes.

**Comment by arthurtalkgoal** [comment]
Thanks much @pusewicz ,  

I wonder I should it's my permission problem? both times I click the Open stage link , it got ***Failed to start this branch.*** error
stage

**Comment by arthurtalkgoal** [comment]
Hi Seems the failure are know issues - 

https://github.com/spree/spree/issues/6074#issuecomment-75487553

Can spree merge my pull request? as I have another pull request for the db/seeds for sqlite, current seeds has syntax error in sqlite. I can upload after this merge.

**Pull request closed without merging**
