### PR TITLE
Use current_store with last_incomplete_spree_order

### PR DESCRIPTION
**Pull request by alexandre025**
last_incomplete_spree_order should retrieve an incomplete order in the context of the current_store

This is particulary essential when we add spree-multi-domain contrib. I think this pull request belongs to Spree::Core instead of spree-multi-domain because Spree::Store is a core concept.

### CODE REVIEW

**Comment by damianlegawiec** [comment]
Hi @alexandre025 unfortunately some specs are failing: 

```
expected: #<Spree::Order id: 838, number: "R600291989", item_total: #<BigDecimal: 0.0>, total: #<BigDecimal: 0....: 0, taxable_adjustment_total: #<BigDecimal: 0.0>, non_taxable_adjustment_total: #<BigDecimal: 0.0>>
     got: nil

(compared using ==)

./spec/lib/spree/core/controller_helpers/order_spec.rb:33:in `block (4 levels) in <top (required)>'
```

**Comment by alexandre025** [comment]
Hi @damianlegawiec, I've fixed it

**Comment by damianlegawiec** [comment]
Hi @alexandre025 can you also rebase your branch against master? Thank you :)

**Comment by alexandre025** [comment]
Done ;)

**Comment by damianlegawiec** [comment]
Via https://github.com/spree/spree/pull/8078

**Pull request closed without merging**
