### PR TITLE
seeds for sqlite

### PR DESCRIPTION
**Pull request by arthurtalkgoal**
db/seeds do not support sqlite now, namely the multi values is different from mysql.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://arthurtalkgoal-3-0-stable-seeds.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://arthurtalkgoal-3-0-stable-seeds.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
sqlite sample specs pass fine for me. do you have steps to reproduce the error?

**Comment by gmacdougall** [comment]
What is your SQLite version?

**Comment by BenMorganIO** [comment]
@gmacdougall good question. I'm also wondering what version of SQLite CircleCI is using.

**Comment by JDutil** [comment]
circleci just runs postgres but running the latest sqlite3 1.3.10 locally passes fine for me locally

**Comment by arthurtalkgoal** [comment]
My sqlite3 is ```sqlite3 (1.3.10)``` and it works too.

**Comment by JDutil** [comment]
I don't understand the need for this then if it's working for you now as well so closing it out.

**Comment by arthurtalkgoal** [comment]
Sqlite3 only works with my PR codes. The existing spree seeds fails in sqlite (since sqlite doesn't support
```
values()
(a,b,c),
(a,b,c),
(a,b,c),
```
syntax as mysql does.

**Comment by JDutil** [comment]
They work for me on same version of sqlite as you. Can you provide the failing backtrace?

**Comment by arthurtalkgoal** [comment]
I think it depends on the system sqlite3 version, not the sqlite gem 

http://stackoverflow.com/questions/1609637/is-it-possible-to-insert-multiple-rows-at-a-time-in-an-sqlite-database

my sqlite is 3.6.20 so it doesn't work as the above post stated *** SQLite 3.7.11 and above now supports the simpler syntax of the original post***

```
[railsu@localhost wireframe.git]$ sqlite3  -version
3.6.20
```

**Comment by BenMorganIO** [comment]
```
"The new multi-valued insert is merely syntactic suger (sic) for the compound insert. There is no performance advantage one way or the other."
```

@arthurtalkgoal do you know if MySQL or PostgreSQL will support union select? If so, then I would recommend to drop the case statement and we could rename the PR to Spree now supporting ... older ... databases.

What are your thoughts on `UNION SELECT` @gmacdougall? I hear you have a DB background.

**Comment by arthurtalkgoal** [comment]
Hi @BenMorganIO ,

I use Mysql most and a few projects use Postgresql.  Honestly, I haven't tried to use ***union select*** in ***any mysql*** or see them in the mysql articles so far.

I bet for Mysql ppl, ***Union*** usually relate to ***JOIN*** but not select.

btw, I am surprised that I found the sqlite3 error in spree, since many ppl shd find the error in their testing or development environment (for agile development, I usually run in sqlite alone).

**Comment by JDutil** [comment]
My sqlite3 version is 3.8.5 I'm going to say anyone using a 3.6.x version should upgrade because I don't think anyone is using sqlite3 in production.  Thanks for providing a fix, but I don't think it's necessary if people use up to date software.

**Comment by BenMorganIO** [comment]
@arthurtalkgoal thanks for the work and teaching us about `UNION` and `JOIN`!

**Comment by arthurtalkgoal** [comment]
Hi @BenMorganIO , nothing much. Since the computer I am developing have lots of old app!  The Fedora is years again and i can't update.

**Pull request closed without merging**
