### PR TITLE
Ffaker bump

### PR DESCRIPTION
**Pull request by jormon**
FFaker at versio 2.0 namespaces itself to FFaker, instead of overriding the Faker namespace used by the similar/related faker gem.  (EmmanuelOga/ffaker#179)

This allows other rails apps using Spree to also use faker without getting namespace collisions.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://jormon-ffaker-bump.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://jormon-ffaker-bump.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by jormon** [comment]
Hey -- do you want me to tackle the style issues in this diff/

**Comment by JDutil** [comment]
Yea that would be great.

**Comment by jormon** [comment]
@JDutil I fixed the hound issues, although they wre pretty unrelated to my change.  Cheers

**Pull request closed without merging**
