### PR TITLE
Add received scope

### PR DESCRIPTION
**Pull request by athal7**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://bonobos-received-scope-master.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://bonobos-received-scope-master.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by peterberkenbosch** [comment]
Thanks Andrew, any change you also add a spec for this?

**Comment by athal7** [comment]
I certainly can. Chose not to because it seemed like a waste of test execution time given how straightforward it currently is. Let me know if you think otherwise and I can add.

**Comment by peterberkenbosch** [comment]
Yeah, make sense. Edge case for me, code is pretty strait forward and good to understand when looking at it. No need to add specs for the sake of adding specs. Let's merge and when other think otherwise we can still add it.

**Pull request merged**
