### PR TITLE
stop Number Generation producing collisions

### PR DESCRIPTION
**Pull request by gjselten**
The problem was reported in #7822; the number generator sometimes creates nummers that collide. After this fix we have not experienced this problem again.

As discussed in #7824, i'm going for an Array.shuffle! as it maintains continuity to the existing structure. I have also not included migrations to make the database fields for number unique (as was included in #7815) as that might not be backwards compatible for users that update their spree version. I'm not sure how to solve that, as that migration would have to change numbers from existing collisions, but at the same time it is not desirable to change the identifier of order/payments/shipments.

### CODE REVIEW

**Comment by gjselten** [comment]
The build on circle has failed- one feature test in 'backend' (creating and capturing payments with a check) failed with message 'execution expired'. When i run these specs on my machine,I do not get this failure. I think it is doubtful that my PR changed anything that would cause that spec to fail. I'm unsure how to proceed.

**Comment by wuboy0307** [comment]
I am fine with NumberGenerator. However, I still think unique index on database is important. It's our final gate to protect our system. How about we print a warning message if there are duplicate numbers?

For example:

```
    # use group by to check if there's any number that use more than 1 time.
    if (Spree::Order.group(:number).count.values.uniq.length == 1)
      remove_index :spree_orders, :number
      add_index :spree_orders, :number, :unique => true
    else
      # print those duplicate numbers to user
      duplicates = Spree::Order.group(:number).count.delete_if { |k, v| v==1 }.keys
      puts("Spree Order has duplicate numbers, please correct #{duplicates.inspect} and rerun this migration")
    end
```

**Comment by gjselten** [comment]
Sure, this sounds like a good plan. I'll make the adjustments

**Comment by damianlegawiec** [comment]
@wuboy0307 we'll be adding unique indexes to all fields, but we also need a migration process for people on older spree versions with duplicates. For larger stores this can be a huge task.

**Review by mauazua — APPROVED** [review]

**Pull request merged**
