### PR TITLE
Remove useless unless setting i18n locale

### PR DESCRIPTION
**Pull request by wuboy0307**
refer from https://github.com/solidusio/solidus/pull/560/files

### CODE REVIEW

**Comment by damianlegawiec** [comment]
:+1:

@priyank-gupta @Mafi88 @jitendra ?

**Comment by Mafi88** [comment]
@damianlegawiec  lgtm :+1:

**Comment by priyank-gupta** [comment]
@wuboy0307 I think the available_locale check is necessary, instead the statement should be like
`locale = I18n.default_locale unless I18n.available_locales.map(&:to_s).include?(locale)` i.e. without memoization.

**Comment by priyank-gupta** [comment]
@wuboy0307 Are you looking into this ?

**Comment by priyank-gupta** [comment]
Closed against https://github.com/spree/spree/pull/7235.

**Pull request closed without merging**
