### PR TITLE
fix issue:  all prices will be found by product active scope

### PR DESCRIPTION
**Pull request by caiqinghua**
``` ruby
irb(main):057:0> Spree::Product.all.active.map(&:id)
  Spree::Product Load (0.9ms)  SELECT `spree_products`.* FROM `spree_products` INNER JOIN `spree_variants` ON `spree_variants`.`product_id` = `spree_products`.`id` AND `spree_variants`.`is_master` = 1 AND `spree_variants`.`deleted_at` IS NULL INNER JOIN `spree_prices` ON `spree_prices`.`variant_id` = `spree_variants`.`id` AND `spree_prices`.`deleted_at` IS NULL WHERE `spree_products`.`deleted_at` IS NULL AND (`spree_products`.deleted_at IS NULL or `spree_products`.deleted_at >= '2015-08-01 07:41:21.556990') AND (`spree_products`.available_on <= '2015-08-01 07:41:21.557380')
=> [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10, 10, 11, 11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16, 17, 18, 19, 20]
```

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://caiqinghua-fix-product-active-scope.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://caiqinghua-fix-product-active-scope.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
This breaks some specs, and I'm not really clear on the intention here by the issue description.  What are you trying to resolve? You should add specs for these changes.

**Comment by priyank-gupta** [comment]
@caiqinghua :+1: 
Are you still active to submit/fix specs for this change ?

**Comment by saiqulhaq** [comment]
I'm agree with @JDutil 
this PR needs more description

**Comment by bbonislawski** [comment]
I think that this is outdated already. If you think that it's not outdated, please mention me in comment and I'll reopen it

**Pull request closed without merging**
