### PR TITLE
Remove unused stock movement pages

### PR DESCRIPTION
**Pull request by smartacus**
I stumbled across a few views that I don't believe are being used. I haven't worked with stock movements very much, so I might not understand what these views are supposed to do. The specs run without them. If the views are still needed, I'll update this PR with a few new specs instead of removing them.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://trialguides-remove-unused-stock-movement-pages.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://trialguides-remove-unused-stock-movement-pages.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
It appears these are linked to from the stock locations index page, and apparently not covered by specs. Doesn't look like they were properly updated for bootstrap either.

**Comment by smartacus** [comment]
If stock is added through admin/products/:friendly_id/stock and transferred through admin/stock_transfers, what is the purpose of these forms? I guess you can remove stock from a stock location by submitting a negative quantity on the stock movement forms. That doesn't seem very intuitive from a user's perspective.

**Comment by JDutil** [comment]
@smartacus yea I'm fine with removing them, but I think we should also remove the controller actions/routes as well.

**Comment by jasonfb** [comment]
How else are you supposed to load stock into the catalog when you first set up a new product? Our merchandiser uses these screens daily -- it is an essential part of his workflow and it should not be removed.

**Comment by JDutil** [comment]
You can setup stock under the "Stock Management" tab of the product page. This is a stock form on the stock location itself so I think it would only really be used if you were creating a new stock location not new products.

**Pull request closed without merging**
