### PR TITLE
Add validation to line_item.rb

### PR DESCRIPTION
**Pull request by ankit1910**
1. add order presence validation
2. fix ensure_proper_currency

### CODE REVIEW

**Comment by damianlegawiec** [comment]
@ankit1910 

```
validate :ensure_proper_currency, if: -> { order.present? }
```

Why are we checking if order exists? All line items must be associated to order, after adding presence validation it isn't required to have this check.

**Comment by ankit1910** [comment]
@damianlegawiec : Thanks for your feedback. 
In case when line items are not associated with order. and we call line_item.valid? on any object then it will raise an exception inside ensure_proper_currency method.

**Comment by damianlegawiec** [comment]
@ankit1910 you've added presence validation, so what's the purpose of even checking for order once again? Record won't be created if order doesn't exist.

**Comment by ankit1910** [comment]
Removing this condition will make system run validation `ensure_proper_currency` even in case when order is nil and this method will call currency on order that is nil at this time. This will raise an exception inside `ensure_proper_currency`.

NoMethodError:
  undefined method `currency' for nil:NilClass
  # ./app/models/spree/line_item.rb:153:in `ensure_proper_currency'
  # /Users/ankit/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.1/lib/active_support/callbacks. rb:432:in `block in make_lambda'
  # /Users/ankit/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:192:in `call'
  # /Users/ankit/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:192:in `block in simple'
  # /Users/ankit/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `call'

**Comment by priyank-gupta** [comment]
@ankit1910 Agreed!!!
@damianlegawiec This seems fine.

**Pull request merged**
