### PR TITLE
Refactor Spree::Zone #country_ids, #state_ids, #country?, #state? and…

### PR DESCRIPTION
**Pull request by tanmay3011**
… refactor specs

### CODE REVIEW

**Comment by priyank-gupta** [comment]
:+1:

**Comment by priyank-gupta** [comment]
@damianlegawiec @Mafi88 ?

**Comment by damianlegawiec** [comment]
@tanmay3011 why do we need another method which is just a shortcut for `kind.eql?(_kind)` ? It just creates another layer of abstraction which we should avoid.

**Comment by tanmay3011** [comment]
@damianlegawiec It's more of a DRY-ing up of code. We shouldn't have multiple methods checking the same thing which could be handled using a argument. Currently we're using state and country what another type gets added.

I'm more in favor for deprecating country? and state? instead only using kind?(_kind).

**Pull request closed without merging**
