### PR TITLE
Switch from Rabl to Active Model Serializers

### PR DESCRIPTION
**Pull request by radar**
I'd like to propose this change on Spree. Rabl was a good decision to start building our API but as it has grown more and more complex, Rabl is beginning to fall apart. For instance, the [orders/show template](https://github.com/spree/spree/blob/3c0277cdb5e6c142d6279c22d784cdc0e3cbcd43/api/app/views/spree/api/orders/show.v1.rabl) is rather messy and un-DRY (WET?). 

Compare that to the [OrderSerializer from this branch](https://github.com/radar/spree/blob/04cb344ba6f966ecce27dd69aef75bddd9d925eb/api/app/serializers/spree/order_serializer.rb). imo, it's much neater.

The only really messy thing in this branch now is the TaxonomyController which uses a couple of different serializers. That's the only bad thing that I know of from this branch, other than of course the gigantic concept shift that AMS will bring.

One good thing is that this will automatically produce proper results. When we go to `/products` atm we'll see a top-level key of `products`:

``` json
{
  products: {
    { 
      id: 1,
      ...
    }
  }
}
```

The `/products/1` route produces this result though:

```
{ 
  id: 1,
}
```

Notice here how there's no root key. This lack of a root key causes problems for frameworks such as Ember Data. While it's possible to work with Ember and not Ember Data, I think it's best if we provided a consistent response for the endpoints of our API.

There's also a problem with the pagination data being returned at the root of the result: Ember expects it to be something that it can load. AMS allows us to [use a `meta` key](https://github.com/radar/spree/blob/04cb344ba6f966ecce27dd69aef75bddd9d925eb/api/app/controllers/spree/api/products_controller.rb#L15-L17), which means that the pagination data will be underneath a `meta` key in the result, rather than at the top-level.

Ultimately, this PR will move our API to something that is [less confusing than Rabl](https://twitter.com/pusewicz/status/439037936026533889), and also works on making our API more compatible with the guidelines that Ember follows and many people expect an API to follow along to.

I don't expect this PR to be merged for a while. I just thought I would get the discussion going now.

/cc @schof @BDQ @cbrunsdon @gmacdougall @JDutil @GeekOnCoffee et. al

### CODE REVIEW

**Comment by JDutil** [comment]
Closing this out as stalled, and I believe people started a fresh implementation.

**Comment by BenMorganIO** [comment]
For column names and caching:

```ruby
module Spree
  class BaseSerializer < ActiveModel::Serializer
    cached

    def self.column_names
      to_s.sub("Serializer", "").constantize.column_names
    end
  end
end
```

OrderSerializer example:

```ruby
module Spree
  class OrderSerializer < Spree::BaseSerializer
    attributes *column_names
  end
end
```

And it would be cached as well.

**Comment by athal7** [comment]
https://github.com/rails-api/active_model_serializers#maintenance-please-read and https://github.com/rails-api/active_model_serializers/pull/693 give me a bit of pause with that approach

**Comment by BenMorganIO** [comment]
@athal7 I believe 0.8 still has it implemented.

**Comment by athal7** [comment]
yes you are right, and they recommend using 0.8. my mistake

**Comment by BenMorganIO** [comment]
@athal7 Was confused as well. Do you know of a recommended way to test serializers?

Looking at [active_model_serializers-matchers](https://github.com/activars/active_model_serializers-matchers). There's forks for 0.8 and 0.9.

**Comment by athal7** [comment]
I've not tried that before, it might be good. If you call .as_json on the serializer, you get a hash of the attributes, seems that could be a nice dependency-less way to go.

**Comment by BenMorganIO** [comment]
I was hoping for a small DSL for testing serializers via RSpec. AMS matchers isn't working out well:

```
  1) Spree::OrderSerializer should have many shipments
     Failure/Error: it { should have_many :shipments }
     NoMethodError:
       undefined method `reflect_on_association' for Class:Class
     # /Users/benmorgan/.rvm/gems/ruby-2.2.0/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/active_record/association_matchers/model_reflector.rb:21:in `reflect_on_association'
     # /Users/benmorgan/.rvm/gems/ruby-2.2.0/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/active_record/association_matchers/model_reflector.rb:17:in `reflection'
     # /Users/benmorgan/.rvm/gems/ruby-2.2.0/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/active_record/association_matcher.rb:749:in `reflection'
     # /Users/benmorgan/.rvm/gems/ruby-2.2.0/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/active_record/association_matcher.rb:903:in `association_exists?'
     # /Users/benmorgan/.rvm/gems/ruby-2.2.0/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/active_record/association_matcher.rb:845:in `matches?'
     # ./spec/serializers/spree/order_serializer_spec.rb:8:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:44:in `block (3 levels) in <top (required)>'
     # /Users/benmorgan/.rvm/gems/ruby-2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/generic/base.rb:15:in `cleaning'
     # /Users/benmorgan/.rvm/gems/ruby-2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/base.rb:92:in `cleaning'
     # /Users/benmorgan/.rvm/gems/ruby-2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /Users/benmorgan/.rvm/gems/ruby-2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:87:in `call'
     # /Users/benmorgan/.rvm/gems/ruby-2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:44:in `block (2 levels) in <top (required)>'
     # /Users/benmorgan/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
     # /Users/benmorgan/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `block in load'
     # /Users/benmorgan/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
     # /Users/benmorgan/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
     # /Users/benmorgan/.rvm/gems/ruby-2.2.0/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
     # -e:1:in `<main>'
```

**Comment by BenMorganIO** [comment]
Actually, I think [this gem](https://github.com/tonyta/active_model_serializers_matchers) would be a much better fix for testing AMS.

**Pull request closed without merging**
