### PR TITLE
Fix n + 1 queries for order users on admin/orders#index

### PR DESCRIPTION
**Pull request by aishmita-aggarwal**

### CODE REVIEW

**Comment by damianlegawiec** [comment]
Adding includes in admin/orders#index messes up filtering/sorting/searching - this was intentionally left with those n+1 queries.

**Comment by aishmita-aggarwal** [comment]
In that case, we can use preload instead of includes. What do you think?

**Comment by damianlegawiec** [comment]
@aishmita-aggarwal preload will result with the same as includes :)

> lazyoading other models here (via includes) may result in an invalid query
          e.g. SELECT  DISTINCT DISTINCT "spree_orders".id, "spree_orders"."created_at" AS alias_0 FROM "spree_orders"

**Comment by aishmita-aggarwal** [comment]
@damianlegawiec I think using preload will give us seperate queries and would not affect existing queries. 
Reference: http://blog.bigbinary.com/2013/07/01/preload-vs-eager-load-vs-joins-vs-includes.html

**Comment by damianlegawiec** [comment]
@aishmita-aggarwal I think you're right :)

**Comment by aishmita-aggarwal** [comment]
@damianlegawiec Thank you. I would modify the PR with preload. :)

**Comment by aishmita-aggarwal** [comment]
Done.
@damianlegawiec @priyank-gupta

**Pull request merged**
