### PR TITLE
allow optional checkout steps numbers

### PR DESCRIPTION
**Pull request by alepore**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://alepore-checkout-numbers.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://alepore-checkout-numbers.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
Please add a regression spec for the option.

**Comment by alepore** [comment]
@JDutil :+1: added specs

**Comment by JDutil** [comment]
Thanks

**Pull request merged**
