### PR TITLE
Adding approve action to api orders controller

### PR DESCRIPTION
**Pull request by softr8**
Also, adding ability to track who cancelled an order.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://softr8-api-orders-approve.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://softr8-api-orders-approve.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by priyank-gupta** [comment]
@softr8 This looks fine.
I think a spec is missing for `canceler_id`.

**Comment by priyank-gupta** [comment]
@damianlegawiec @Mafi88 ?

**Comment by Mafi88** [comment]
@softr8 @priyank-gupta I agree that it needs spec for ```canceler```. Also, it would be really nice if you could address the houndci issues.

**Comment by softr8** [comment]
@Mafi88 @priyank-gupta done!

**Comment by Mafi88** [comment]
Thanks @softr8 

lgtm :+1:

**Comment by priyank-gupta** [comment]
:+1:

**Pull request merged**
