### PR TITLE
Added method in signle line

### PR DESCRIPTION
**Pull request by arvindvyas**
Can we make this method in single line

### CODE REVIEW

**Comment by damianlegawiec** [comment]
@arvindvyas please fix hound issues

**Comment by arvindvyas** [comment]
@damianlegawiec fixed the hound issue please check

**Comment by damianlegawiec** [comment]
@priyank-gupta @mauazua any thoughts? IMHO I don't see this as something improving the codebase...

**Comment by mauazua** [comment]
@damianlegawiec I personally prefer declaring methods with an empty body in one line, but as far as I know both versions are correct.

**Comment by vishalzambre** [comment]
@damianlegawiec @priyank-gupta Why we kept empty methods in api controller and specially new method, I don't think so that methods are useful anywhere?

**Comment by arvind-vyas** [comment]
I am not sure who is reviewing and taking decision @damianlegawiec @vishalzambre it would be better to close PR if you guys not looking it useful.

**Pull request closed without merging**
