### PR TITLE
Only allow Spree::Order filtering for ordered Variants.

### PR DESCRIPTION
**Pull request by parndt**
This is to address #6181

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://parndt-patch-8.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://parndt-patch-8.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by parndt** [comment]
This yields the following SQL:

```sql
(1.0ms)  SELECT "spree_variants"."sku", "spree_variants"."id" FROM "spree_variants" INNER JOIN "spree_line_items" ON "spree_line_items"."variant_id" = "spree_variants"."id" WHERE "spree_variants"."deleted_at" IS NULL
```
With the result set taking far, far longer than that to populate the select list.  I imagine that this will get slower with the more orders that you have but by default it will be markedly improved.
vs before, with 1.2M variants:

```sql
(834.5ms)  SELECT "spree_variants"."sku", "spree_variants"."id" FROM "spree_variants"  WHERE "spree_variants"."deleted_at" IS NULL
```

**Comment by parndt** [comment]
With feedback from both @GeekOnCoffee and @radar, I've improved the patch.  Now the SQL looks like this:

```sql
   (1.2ms)  SELECT DISTINCT "spree_variants"."sku", "spree_variants"."id" FROM "spree_variants" INNER JOIN "spree_line_items" ON "spree_line_items"."variant_id" = "spree_variants"."id" WHERE "spree_variants"."deleted_at" IS NULL  ORDER BY "spree_variants"."sku" ASC
```

The main difference being that it's guaranteeing unique `sku` and `id` pairs and it's ordered by sku, which makes for better UX.

**Comment by gmacdougall** [comment]
Thanks for your work on this @pardnt. The code as it it is looks like it will be an improvement in speed for stores with lots of variants, many of which haven't sold.

I foresee that as the number of variants that are ordered, the performance of this will degrade and eventually approach your initial behaviour (when all variants have been ordered).

An alternate solution might be a simple configuration which will allow a site admin to disable this select box, or replace it with a text input. At that point, no SKU's would need to be loaded in order to render the page.

I'm sure that some stores will require that as they upgrade to Spree 3.0 and encounter the same problem that you're having.

**Pull request closed without merging**
