### PR TITLE
move user class extensions to a module

### PR DESCRIPTION
**Pull request by alepore**
(some code taken from Solidus, @deereb and @forkata)
this is a cleaner solution and allow easier User modification

I also had to update the ransack whitelisting to work like all the other models

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://alepore-user-methods.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://alepore-user-methods.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by cbrunsdon** [comment]
:+1:

**Comment by jhawthorn** [comment]
:+1: Just for proper credit this change came from @deereb and @forkata

**Comment by alepore** [comment]
right, i tried some proper cherry-picking at first but that was not straightforward...
description updated!

**Pull request merged**
