### PR TITLE
Prevent last admin from getting destroyed

### PR DESCRIPTION
**Pull request by nimish13**

### CODE REVIEW

**Comment by damianlegawiec** [comment]
@nimish13 specs are failing :(

**Comment by nimish13** [comment]
@damianlegawiec Thanks for reviewing it. I just saw ``admin?`` method defined in ``spree_auth_devise`` is not accessible here. I will figure it out and fix the specs soon. :)

**Comment by nimish13** [comment]
Hi @damianlegawiec, the failing rspecs has been fixed. Please review.

**Comment by damianlegawiec** [comment]
Giving it a second thought - this could be an overkill and be really troublesome in development...

**Pull request closed without merging**
