### PR TITLE
Update Spree::Order::PAYMENT_STATES with valid states

### PR DESCRIPTION
**Pull request by akshay-vishnoi**
cc: @priyank-gupta

### CODE REVIEW

**Comment by priyank-gupta** [comment]
@akshay-vishnoi This constant is seemingly ambiguous in terms of `payment_state` attribute in `spree_orders` and `state` attribute in `spree_payments`. But as this is a constant in Order model we can expect it to signify `payment_state`s of order and not `state` of payments. Also, the usage of this constant is [here](https://github.com/spree/spree/blob/master/backend/app/views/spree/admin/orders/index.html.erb#L60), which is orders/index.
This PR seems fine to me unless there is any hidden expectation here.
@damianlegawiec Let us know your thoughts.

**Comment by damianlegawiec** [comment]
@priyank-gupta I'm assigning @Mafi88 to this :)

**Comment by priyank-gupta** [comment]
@Mafi88 Discussion regarding this change is #6143

**Comment by Mafi88** [comment]
@priyank-gupta thanks for discussion link.

It seems fine, removed states can't be set as order.payment state anyway

@akshay-vishnoi thanks!

**Comment by akshay-vishnoi** [comment]
:yellow_heart:

**Pull request merged**
