### PR TITLE
Fix bug where line item quantity cannot be set to zero for out-of-stock items.

### PR DESCRIPTION
**Pull request by mbj**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://mountainroseherbs-fix-bug-quantity-zero-out-of-stock.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://mountainroseherbs-fix-bug-quantity-zero-out-of-stock.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by mbj** [comment]
@JDutil Again, hount issues. I'm fine to fix these all. Can you state whatever hount sais is the recommended style, so I can fix them proactively? Is the config for rubocop available somewhere so I can do checks locally before submitting?

**Comment by dkubb** [comment]
@mbj in this code I think we were just trying to follow existing code conventions, however I probably would just use plain double quotes than to use the more exotic quoting operators -- I tend only to look towards those when single or double quotes isn't as clean.

**Comment by JDutil** [comment]
Yea we would like to address hound comments in order to improve coding style moving forward, but we're open to adjusting the rubocop rules where appropriate as well.

Configs are:
https://github.com/spree/spree/blob/master/.rubocop.yml
https://github.com/spree/spree/blob/master/.hound.yml

**Comment by mbj** [comment]
@JDutil Thx. I'll fix the remaining code style issues and ping you back.

**Comment by mbj** [comment]
@JDutil The style issues where addressed, assuming a green build this is ready for the next pass.

**Comment by mbj** [comment]
@JDutil Changes you can backport this one to 2-4 and 2-3-stable? Should apply clean AFAIK.

**Comment by JDutil** [comment]
done

**Comment by mbj** [comment]
thx

**Pull request closed without merging**
