### PR TITLE
Show backend shipment methods in admin order UI

### PR DESCRIPTION
**Pull request by paultyng**
Fixes the issue where backend only shipment methods do not display in the backend UI.

The master branch interfaces changed a bit, so will need to rework this slightly to apply to master.

Am I missing something on the backend shipment methods? They should be available in this list, correct?

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://ratioclothing-pt-backend-shipment-rates.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://ratioclothing-pt-backend-shipment-rates.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
I believe we only fixed this on 3+ because it changed the public api of those methods that extensions may be overriding.

**Comment by paultyng** [comment]
Ah that makes sense.  I could add a new method so that the signatures aren't modified if that makes it acceptable in 2.4.  That would at least get the UI fixed.

**Comment by paultyng** [comment]
Or check the arity, but that seems overly complex.

**Pull request closed without merging**
