### PR TITLE
Spree REST image API returning successful status code on create or update api although it has error.

### PR DESCRIPTION
**Pull request by vishalzambre**
Resolve issue #6741
Image api returning wrong status code on error while create or update.

### CODE REVIEW

**Comment by tanmay3011** [comment]
@vishalzambre Does this really resolves #6741?

Plus please provide specs too.

**Comment by vishalzambre** [comment]
@tanmay3011  Spec is not changed, its failing for order detail feature, which you fixed in https://github.com/spree/spree/pull/7092, will rebase my branch after your PR merged

**Comment by tanmay3011** [comment]
@vishalzambre Specs are not written for the else part which you have added. So add specs for failure of object creation and failure of object updation.

**Comment by vishalzambre** [comment]
@tanmay3011 updated with specs for added else part

**Comment by vishalzambre** [comment]
@tanmay3011 can you please check spec.

**Comment by tanmay3011** [comment]
:+1:

**Comment by priyank-gupta** [comment]
:+1:

**Pull request merged**
