### PR TITLE
Improved email validation

### PR DESCRIPTION
**Pull request by metade**
We've noticed a few invalid emails slip through our application so we're proposing a change to the Regex used for email validation.

The regex is adapted from here: http://stackoverflow.com/questions/4770133/rails-regex-for-email-validation

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://lostmyname-improved-email-validation.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://lostmyname-improved-email-validation.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by metade** [comment]
Hmm, not sure about this. Regexes for validating emails are fiddly. Probably best to use a third party gem that does this properly!

**Comment by JDutil** [comment]
Thanks

**Comment by metade** [comment]
Thanks for merging, but we actually gave up on this approach and ended up using the `valid_email` gem in our app - the Regex was too fiddly and was too restrictive on actual valid emails.

**Comment by felixbuenemann** [comment]
Yepp, this already ignores valid TLDs like .fitness.

**Pull request closed without merging**
