### PR TITLE
Fix problem with infinite loop of redirects in API

### PR DESCRIPTION
**Pull request by VygovskySergey**
#8953

### CODE REVIEW

**Comment by kushniryb** [comment]
@damianlegawiec 
What's the reason behind redirecting from `/products` to `v1/products`?
Do we really need this functionality?
It's not apparent whether you've made a mistake or not due to the redirect and it introduces unnecessary complexity on top of it. Maybe it would be a good idea to remove this piece completely?

**Comment by damianlegawiec** [comment]
@kushniryb before Spree 3.1 API wasn't versioned. There's a LOT of integrations out there that rely on the API v1 to be available at `https://example.com/api/orders.json` - that's why this redirect was introduced.

**Comment by bbonislawski** [comment]
It's part of versioncake Gem. I think this whole thing should be deprecated(and extracted into separate gem) with Spree 4.x since everyone should use api v2

**Comment by damianlegawiec** [comment]
@bbonislawski yep, but until 4.0 we should keep this

**Review by damianlegawiec — APPROVED** [review]

**Pull request merged**
