### PR TITLE
Allow resources within modules to use ResourcesController.

### PR DESCRIPTION
**Pull request by MattDunbar**
This will apply cleanly on 2-2, 2-3 and 2-4, unconfirmed for prior releases.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://mattdunbar-master.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://mattdunbar-master.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by MattDunbar** [comment]
@cbrunsdon I have resolved the code duplication.

**Comment by cbrunsdon** [comment]
Can we get some kind of test to go with this too, please?

**Comment by MattDunbar** [comment]
@cbrunsdon I've added tests.

I've disregarded the hound issues coming up as they are a result of keeping consistent with the existing tests in this spec. Let me know if they should be implemented.

**Comment by JDutil** [comment]
@MattDunbar would be good to address the hound comments as well please.

**Comment by MattDunbar** [comment]
@JDutil Formatting has been based on hound.

**Comment by gmacdougall** [comment]
@MattDunbar I like the functionality that this change allows. However, the complexity in resource controller is a bit difficult to understand.

Have you thought about extracting the model name/class/object name to a separate class.

Give it a path and then ask it what the model_name, model_class and object_name are. At a minimum, it will give you better interface to test.

**Comment by MattDunbar** [comment]
Disregard the last commit - I accidentally copied code from 2-3-stable back to master.

**Comment by MattDunbar** [comment]
Working on tests now then this should be wrapped.

**Comment by MattDunbar** [comment]
This PR should now have sufficient tests on the resource model and be ready to merge. Let me know if you have further concerns with merging this.

**Comment by JDutil** [comment]
@MattDunbar there are still several backend spec failures which appear to mostly be uninitialized constant errors.  Could you have another look please?  Thanks!

**Comment by MattDunbar** [comment]
@JDutil apologies, I overlooked the failing tests I introduced splitting logic out of the resources controller.

If anyone who has a few minutes cares to dig into the remaining failing tests it'd be greatly appreciated. I'm having a hard time finding a solution for the remaining 2 failing tests (very likely the same issue).

**Comment by MattDunbar** [comment]
Actually, upon digging further it looks like these issues are unrelated and were existing on master when I made the PR.

Please confirm and merge, or let me know which are new.

**Comment by JDutil** [comment]
The remaining specs aren't broken on master branch, but I'm not sure why your change even affects them.  I'm not sure why the url helpers aren't defined there.  There is a very similar spec here:
https://github.com/spree/spree/blob/master/backend/spec/features/admin/homepage_spec.rb#L61-L79

Which is passing fine without hitting the undefined method error.  It's like the routes are coming undone or something during the spec run.

**Comment by JDutil** [comment]
Actually that would be because of your rewriting & reloading routes in:
https://github.com/spree/spree/pull/5954/files#diff-d39c34ac52242598fd564473683289eaR191 

Working on a fix.

**Comment by JDutil** [comment]
I'm also having trouble getting the specs to pass.  It appeared to be an issue of wanting to use frontend root_path, which doesn't exist so if you stub a route the cancan ability authorization is still failing which is why we're seeing the failure to begin with.  Not sure how/where it's happening, but for some reason the custom authorization block for those specs isn't working properly to just give access to the Spree::Product model.

So I think the changes to the resource controller may be altering how cancan is authorizing the index action.

**Comment by MattDunbar** [comment]
I believe this is specific to moving the functionality from the controller to the model, although, I don't know exactly how. It may take some time but I'll see if I can get someone from our side to dig into this a bit deeper in the next week or so.

**Comment by GeekOnCoffee** [comment]
I've sent a PR into this one to readd the `model_class` method, without it https://github.com/spree/spree/blob/master/backend/app/controllers/spree/admin/base_controller.rb#L18 was falling back to controller_name.to_sym causing us to authorize against the wrong thing 

https://github.com/MattDunbar/spree/pull/1 should get it right.

**Comment by MattDunbar** [comment]
@GeekOnCoffee Looks like that solved part of the issue and I've merged the changes, but we're failing 2 new tests now. Please look if you can. Thanks!

**Comment by JDutil** [comment]
@MattDunbar @GeekOnCoffee awesome thanks that looks like it did the trick.  The failing spec I see left is the known one we haven't figured out how to fix its frailness yet https://github.com/spree/spree/issues/5877

**Comment by MattDunbar** [comment]
@JDutil got it, looks like we're good to merge then?

Any chance we can get this applied to 2-3-stable and 2-4-stable?

**Comment by JDutil** [comment]
Sorry I don't think this refactoring should be done in the stable branches.

**Comment by MattDunbar** [comment]
No problem, was hoping we could get it in so that I could rely on it for a few internal builds but understood.

**Comment by GeekOnCoffee** [comment]
@JDutil it might be worth adding a `frail` tag to that test, just so if people run into it failing in the future they know to retry...

**Pull request closed without merging**
