### PR TITLE
Redirect unauthorized access to route not url

### PR DESCRIPTION
**Pull request by GeekOnCoffee**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://geekoncoffee-unauthorized-route.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://geekoncoffee-unauthorized-route.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by gmacdougall** [comment]
:+1:

**Comment by JDutil** [comment]
This breaks the build, and it should also be: spree.unauthorized_path

**Comment by JDutil** [comment]
Thanks for updating this @GeekOnCoffee I'm stumped as to why it breaks the build though... Also fyi good to ping me after you address feedback otherwise I never know that new commits were pushed ;)

**Comment by bbonislawski** [comment]
I think that this is outdated already. If you think that it's not outdated, please mention me in comment and I'll reopen it

**Pull request closed without merging**
