### PR TITLE
Use built in leaf? method for detecting no children.

### PR DESCRIPTION
**Pull request by parndt**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://parndt-feature-awesome-nested-set-apis.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://parndt-feature-awesome-nested-set-apis.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by gmacdougall** [comment]
:+1:

This is a slight change in logic, but given my understanding of awesome_nested_set, I believe both to be correct, with this one being significantly more efficient.

Thanks for your work on this.

**Comment by parndt** [comment]
That's right, this is a change in logic but uses nested set logic instead of expensive database queries.

**Comment by JDutil** [comment]
Is this something you wanted back to 2-4-stable as well?

**Comment by parndt** [comment]
Yes please :)

**Comment by JDutil** [comment]
Done

**Pull request closed without merging**
