### PR TITLE
acts_as_paranoid not work in default_price

### PR DESCRIPTION
**Pull request by wuboy0307**
It seems that where scope in has_one relationship didn't use acts_as_paranoid.

### CODE REVIEW

**Comment by krzysiek1507** [comment]
@wuboy0307 please check this [commit](https://github.com/spree/spree/blob/master/core/app/models/concerns/spree/default_price.rb#L21-L23) and history

**Comment by wuboy0307** [comment]
I see. So now the problem will be: Why should we unscoped it?
In my production environment, I try to deleted a variant. The system alarm me that the variant can't be deleted. Which is correct since the variant already bought by some people. However, the variant's price become weird.in some pages it become zero, in other pages it shows original price. Also, I can't edit the price in variant editing page. That's because "deleted_at" is already set. Some pages honer acts_as_paranoid setting and show zero, some pages don't. It 

The problem is from here:
https://github.com/spree/spree/blob/master/core/app/models/spree/variant.rb#L15-L17
https://github.com/spree/spree/blob/a140d564ae7b37476070c2435c6c39709ebe7b9e/core/app/models/spree/variant.rb
As you can see, this is a before_destroy callback sorting issue: https://github.com/rails/rails/issues/3458

According to the discussion, The correct fix is to place "include Spree::DefaultPrice" after "before_destroy :ensure_no_line_items". Otherwise the default_price will be deleted first, then variant delete got exception.

**Comment by krzysiek1507** [comment]
@wuboy0307 I'm not sure if this it good solution but if we want to fix it that way, we need specs for it to avoid it again

**Comment by wuboy0307** [comment]
I am really not a RSpec fan. But I already tested in my environment. Before this code change, when I try to deleted a variant which already been bought, the variant can't be deleted but the price has been deleted. After code change, the variant still can't be deleted, but this time price is also not deleted. Which is expected result.

**Comment by krzysiek1507** [comment]
@wuboy0307 it is regression so spec for it is double important

**Comment by damianlegawiec** [comment]
Merged via https://github.com/spree/spree/pull/8008

**Pull request closed without merging**
