### PR TITLE
Refactoring_sample

### PR DESCRIPTION
**Pull request by holylance**

### CODE REVIEW

**Comment by holylance** [comment]
I squashed all commits but it has some conflicts so I had to make another commit to fix the conflicts in github.
How was your thinking @bbonislawski ?

**Comment by holylance** [comment]
I squashed all commits so it is just one commit now.
Please check it, @bbonislawski.

**Comment by bbonislawski** [comment]
There are some double quotes left here https://github.com/holylance/spree/blob/b005675fc58cd5a8748158ad335553ae5d055492/sample/db/samples/taxons.rb#L8 . Can you change them?

**Comment by bbonislawski** [comment]
@holylance pull newest master and when on your branch, use `git rebase master`. Then fix conflicts, add files with git and do `git rebase --continue`. Remember to pull newest master from `spree/spree` and not your fork

**Comment by holylance** [comment]
I tried to fix the conflict many times but it was not working.

I think we have two options

one, make two commits in this PR.
two, undo the conflicts code and fix next time.

How about you? @bbonislawski

**Comment by bbonislawski** [comment]
@holylance I've cherry-picked your changes and rebased against current master on #8695 since rebasing can be quite tricky. Thanks for your contribution and I'm closing this one

**Comment by holylance** [comment]
Thanks a lot.

**Pull request closed without merging**
