### PR TITLE
Add id to HABTM tables which were converted to has_many: through

### PR DESCRIPTION
**Pull request by tanmay3011**

### CODE REVIEW

**Comment by priyank-gupta** [comment]
:+1: 
@damianlegawiec @Mafi88 ?

**Comment by nishant-cyro** [comment]
:+1:

**Comment by vishalzambre** [comment]
@tanmay3011  Its not good to have id in each HABTM table, It should be added only if required.

**Comment by tanmay3011** [comment]
@vishalzambre The associations related to these tables have already changed from HABTM to has_many through so it's good to have id in has_many through tables.

**Comment by vishalzambre** [comment]
:+1:

**Pull request merged**
