### PR TITLE
change class methods to scopes for activerecord chaining

### PR DESCRIPTION
**Pull request by dilpreet92**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://dilpreet92-scope-class-methods.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://dilpreet92-scope-class-methods.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by priyank-gupta** [comment]
@dilpreet92 Rebase and push.

**Comment by dilpreet92** [comment]
@priyank-gupta Done

**Comment by Mafi88** [comment]
:+1:

**Comment by priyank-gupta** [comment]
:+1:

**Pull request merged**
