### PR TITLE
Fixing #6173

### PR DESCRIPTION
**Pull request by frankmt**
https://github.com/spree/spree/issues/6173

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://frankmt-2-4-stable.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://frankmt-2-4-stable.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
Thanks

**Comment by frankmt** [comment]
@JDutil was this merged? Sorry, a bit confused on what happened.

**Comment by JDutil** [comment]
Yup, into 2-4-stable, 3-0-stable, and master. Thanks.

**Pull request closed without merging**
