### PR TITLE
Remove elements from display only when they are successly removed

### PR DESCRIPTION
**Pull request by tanmay3011**

### CODE REVIEW

**Comment by priyank-gupta** [comment]
:+1:

**Comment by Mafi88** [comment]
@tanmay3011 Could you please explain how this change helps?

There is ajax request with ```success``` and ```error```. Element was only removed on ```success```. Why check for success flash alert?

**Comment by tanmay3011** [comment]
@Mafi88 Since we don't have status codes set in our controllers for destroy action we will end up in success callback always even in case of error. So if an element is not destroyed it still gets faded out and on refresh it'll reappear.

**Expected Behaviour:** The element should only fade-out when it gets destroyed.

Solution: So added a check, the element should only fadeout when we have a success message. In case of error it shouldn't fadeout.

**Comment by Mafi88** [comment]
@tanmay3011 Thanks :)

**Pull request merged**
