### PR TITLE
Store: add default to permitted attributes

### PR DESCRIPTION
**Pull request by joshRpowell**
This patch fixes `ActionController::UnpermittedParameters: found unpermitted parameter: :default` when updating here `/store/admin/stores/1/edit`: 
slack - nasb-milner 2018-05-07 10-38-20

### CODE REVIEW

**Review by damianlegawiec — APPROVED** [review]
👍

**Comment by bbonislawski** [comment]
Actually, I wouldn't add it to permitted attributes but remove option to edit `Default` in form. We have `set_default` action for this and in my opinion we shouldn't be able to edit in form. Keeping this in form can complicate some things and introduce unneeded coupling. What do you think @damianlegawiec @joshRpowell ?

**Comment by damianlegawiec** [comment]
@b0ni yep you're idea is better

**Comment by joshRpowell** [comment]
@bbonislawski good call. I prefer that as well. Updated.

**Comment by bbonislawski** [comment]
@joshRpowell can you add some information if store is default or not instead of form field for that? Just some information without option to edit it

**Pull request merged**
