### PR TITLE
Add slug history to taxons master

### PR DESCRIPTION
**Pull request by berkes**
PR #6873, version for master branch.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://berkes-add-slug-history-to-taxonomies-master.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://berkes-add-slug-history-to-taxonomies-master.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by damianlegawiec** [comment]
@berkes could you sync with master?

**Comment by berkes** [comment]
@damianlegawiec sorry for the long wait. I was busy on non-spree projects. Rebased, pushed and the build now passes.

**Comment by damianlegawiec** [comment]
:+1:

**Pull request merged**
