### PR TITLE
Make store credits optional, instead of automatic

### PR DESCRIPTION
**Pull request by mleglise**
Merges spree/master into spree/add-store-credits

Removes the automatic application of Store Credit to a given Order. Instead, the user is prompted in `Checkout#payment` to apply their store credit. This mimics Amazon's functionality, allowing the user to decide whether to save their store credit for later or use it immediately.

Includes various bug fixes, including charging the 2nd payment method the correct remaining amount, instead of the order total.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://mleglise-add-store-credits.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://mleglise-add-store-credits.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
Thanks

**Comment by mleglise** [comment]
@tomash I believe that the changes to handling blank `display_on` were made in master. They only appear in this branch because I merged master into `add-store-credits`.

**Comment by tomash** [comment]
@mleglise yes, this comment shouldn't appear under this pull request. it's all fixed in #6653 now :)

**Pull request merged**
