### PR TITLE
Improvement / refactoring sample

### PR DESCRIPTION
**Pull request by holylance**
I fixed some errors in sample directory.

And I think double_quotes is better than single_quotes to express strings.

### CODE REVIEW

**Comment by bbonislawski** [comment]
Hello @holylance ,

thanks for your contribution but I think that single_quotes are better than double_quotes. Please change it back since you generate 14040 issues on codeclimate with that change. We're sticking to single_quotes. After that I'll check changes made by you since now it's hard to distinct them from changing quotes

**Comment by holylance** [comment]
Dear bbonislawski,
Oh, okay. I will change from double_quotes to single_quotes again.
It is easy job.
Best

**Comment by holylance** [comment]
What happen in api directory?
It has an rspec error.
Please check the rspec error in api directory.
I just touch at a sample directory.

**Comment by bbonislawski** [comment]
Thanks @holylance . Could you squash everything into 1 commit so I can merge it?

**Comment by holylance** [comment]
I squashed all commits. You think that is it correct, @bbonislawski?

**Comment by bbonislawski** [comment]
Now you have 5 commits instead of 1 :( 

Accepted answer here https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git is correct. Please do it this way and then git push  with `--force` option so you'll overwrite this PR.

**Pull request closed without merging**
