### PR TITLE
Adds the ability to set a reason why a state change happened on a order

### PR DESCRIPTION
**Pull request by alex-handley**
I think it would be useful to be able to store the reason why an order was canceled. For example found cheaper somewhere else.
Before I start building the frontend I wanted to check if this would be something you would consider merging?

Also can this be merge into 2.4 or are you only accepting new features on 3.0?

Thanks!

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://alex-handley-features-track-reasons-for-state-changes.spree-spree-9ed724b77adec04c49c2.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://alex-handley-features-track-reasons-for-state-changes.spree-spree-9ed724b77adec04c49c2.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by JDutil** [comment]
New features are just going into master branch. I think it's useful to be able to store information about the state change if you'd like. What did you have in mind for frontend?

**Comment by alex-handley** [comment]
@JDutil Ok, I was thinking to add a reasons column to the order state changes page.
If its going on master a could change the cancel button to open a bootstrap modal so the user can enter a reason and then submit.

Thoughts?

**Comment by JDutil** [comment]
@alex-handley I don't undertstand how that would work the state changes page is just meant to list the state changes that occurred it doesn't allow you to change the state...

**Comment by alex-handley** [comment]
@JDutil Wrote that pre-coffee.. you would be able to view the reasons on the state changes page. Adding the reason would be done via a modal which would appear when clicking cancel on the orders page.

**Comment by alex-handley** [comment]
@JDutil Would you be happy to accept this?

**Comment by JDutil** [comment]
@alex-handley if you write up the ux for it, and some release note added to https://github.com/spree/spree/blob/master/guides/content/release_notes/3_1_0.md

**Comment by jasonfb** [comment]
@alex-handley -- We actually have a feature request for this in our pipeline. Would it be a worse design (loaded question) to add a cancel_reason (VARCHAR 255) on the spree_orders table directly?

The reason I ask is that it is unclear to me what the benefit of storing only the cancellation reasons off in the state_changes table (which, BTW is so huge in my database I rarely include it in my dumps)

I'm only chiming in here because our Ops team has specifically requested this, and also we want a way to cancel fraud-flagged orders

**Pull request closed without merging**
