### PR TITLE
Add INVALID_STATES constant and use it in valid scope and in a few more methods, write specs for same

### PR DESCRIPTION
**Pull request by nishant-cyro**

### CODE REVIEW

**Comment by priyank-gupta** [comment]
@nishant-cyro Please address hound issues.

**Comment by nishant-cyro** [comment]
@priyank-gupta - Fixed!

**Comment by priyank-gupta** [comment]
@nishant-cyro Rebase with latest master.

**Comment by nishant-cyro** [comment]
@priyank-gupta - done!

**Comment by Mafi88** [comment]
:+1:

**Pull request merged**
