### PR TITLE
Split spec_helper in extension template, apply rubocop fixes

### PR DESCRIPTION
**Pull request by artplan1**

### CODE REVIEW

**Review by damianlegawiec — APPROVED** [review]
Nice 👍

**Comment by artplan1** [comment]
@damianlegawiec do you think it will be good thing to add `rubocop.yml` to extension template and `rubocop-rspec` to dev deps?

**Comment by damianlegawiec** [comment]
@artplan1 why not - @bbonislawski what do you think about it?

**Comment by bbonislawski** [comment]
@artplan1 yeah, that would be great. Do you want to add it here or should I merge this and you'll do next PR?

**Comment by artplan1** [comment]
@bbonislawski thank you. I'll add it here.

**Comment by artplan1** [comment]
hm, adding rubocop-rspec to `cmd/lib/spree_cmd/templates/extension/spec/.rubocop.yml` somehow triggers adding rubocop-rspec to whole project on codeclimate

**Comment by bbonislawski** [comment]
@artplan1 I'll try to fix it

**Comment by bbonislawski** [comment]
@artplan1 can you try adding 
```
    file: '.rubocop.yml'
``` on line 5 in .codeclimate.yml?

**Comment by artplan1** [comment]
@bbonislawski it didn't work, I'll try `codeclimate cli` locally to figure

**Comment by bbonislawski** [comment]
@artplan1 oh, my fault. Can you squash commits? There are too many commits now for these changes. Try to group them and avoid having `Fix X` commits

**Comment by bbonislawski** [comment]
Awesome! Thanks @artplan1

**Pull request merged**
